## File discovery

In [ ]:
import os, glob
from pathlib import Path

# Change USERNAME if needed
DATA_DIR = Path.home() / "Desktop" / "Carrier project"

print("Data directory exists:", DATA_DIR.exists())
print("Files in directory:")
for f in DATA_DIR.iterdir():
    print("-", f.name)

Data directory exists: True
Files in directory:
- .ipynb_checkpoints
- 2025-02-19 Nunner offer  OUTBOUND version Final 1.1 Valid 2025.xlsx
- 2025-06-26 Nunner offer INBOUND version Final 3.0 valid 2025.xlsx
- 2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-090556-629.xlsx
- Carrier_Allocation_Simulation.ipynb
- Carrier_Optimization_Full_Project_Plan.docx
- Carrier_Optimization_Project_and_Thesis_Overview.docx
- Carrier_Selection_Detailed_Report.pdf
- Carrier_Selection_Full_Presentation.pptx
- Copy of Freight Spend CMI Belgium_Jan'25_Nov'25.xlsx
- desktop.ini
- DHL MasterData2025.xlsx
- DHL-GEODIS-NUNNER
- DHL.zip
- dhl_rate_fact_final.csv
- dhl_rate_fact_parsed.csv
- Freight Spend CMI Belgium_Jan'25_Nov'25.xlsb
- freight_config.json
- Freight_Optimization_Final_Report.docx
- Freight_Spend_Optimization_Executive_Summary.docx
- Freight_Spend_Optimization_Full_Executive_Report.docx
- Geodis.zip
- geodis_negotiation_target_card.csv
- geodis_rate_fact_final.csv
- Notebook_00_Run_Any_Country.ipynb
- Notebook_00_Run_Any_Country_v5.ipynb
- Notebook_01_France_Oracle_Config..ipynb
- Notebook_02_GEODIS_Rate_Normalization.ipynb
- Notebook_03_DHL_Rate_Normalization.ipynb
- Notebook_04_France_Optimization_GEODIS_vs_DHL.ipynb
- Notebook_04_France_Optimization_GEODIS_vs_DHL_FINAL.ipynb
- Notebook_05_Invoice_Freight_Spend_France_GEODIS_DHL.ipynb
- Notebook_06_GEODIS_Deep_Dive_GENERIC_v2.ipynb
- Notebook_06_GEODIS_France_Deep_Dive_Invoices.ipynb
- Notebook_06_GEODIS_France_Deep_Dive_Invoices_FINAL.ipynb
- Notebook_07_GEODIS_France_Internal_Savings.ipynb
- Notebook_08_France_Structural_Simulation_GEODIS_vs_DHL_OPTIMIZED.ipynb
- Notebook_08_Structural_Simulation_GENERIC.ipynb
- Notebook_09_Executive_Dashboard_GENERIC.ipynb
- Notebook_09_France_Executive_Dashboard.ipynb
- Nunner.zip
- nunner_in_rate_fact_final.csv
- nunner_in_rate_fact_final_v2.csv
- nunner_out_rate_fact.csv
- nunner_out_rate_fact_final.csv
- nunner_out_rate_fact_final_v2.csv
- oracle_road_weight_breaks_summary.csv
- oracle_weight_breaks_all.csv
- oracle_weight_breaks_road.csv
- output
- PDC invoice
- PDC_Transportation_Matrix_20251222060506.xlsx
- QMP_Transportation_Matrix_20251222060644.xlsx
- Rates Geodis.xlsx
- Thesis report.docx
- Thesis.docx
- Updated_Carrier_Optimization_Meeting_Brief.docx
- Updated_Carrier_Optimization_Meeting_Brief.pdf
- Weight Break and costs optimization.pptx
- Weight_Break_Project 0.ipynb
- Weight_Break_Project 1.ipynb
- Weight_Break_Project_Final_Graphs.ipynb
- Weight_Break_Project_FIXED_v4.ipynb
- Weight_Break_Project_FIXED_v4_CORRECTED.ipynb
- Weight_Break_Project_FIXED_v5-Copy1.ipynb
- Weight_Break_Project_FIXED_v5.ipynb
- Weight_Break_Project_NEGOTIATION_NOTEBOOK.ipynb
- Weight_Break_Project_NEGOTIATION_NOTEBOOK_v2.ipynb

In [ ]:
xlsx_files = sorted(glob.glob(str(DATA_DIR / "*.xlsx")))
xlsb_files = sorted(glob.glob(str(DATA_DIR / "*.xlsb")))

print("Found .xlsx files:", len(xlsx_files))
for f in xlsx_files:
    print("-", os.path.basename(f))

print("\nFound .xlsb files:", len(xlsb_files))
for f in xlsb_files:
    print("-", os.path.basename(f))

Found .xlsx files: 8
- 2025-02-19 Nunner offer  OUTBOUND version Final 1.1 Valid 2025.xlsx
- 2025-06-26 Nunner offer INBOUND version Final 3.0 valid 2025.xlsx
- 2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-090556-629.xlsx
- Copy of Freight Spend CMI Belgium_Jan'25_Nov'25.xlsx
- DHL MasterData2025.xlsx
- PDC_Transportation_Matrix_20251222060506.xlsx
- QMP_Transportation_Matrix_20251222060644.xlsx
- Rates Geodis.xlsx

Found .xlsb files: 1
- Freight Spend CMI Belgium_Jan'25_Nov'25.xlsb

In [ ]:
import re

def pick_file(files, must_include=(), any_include=()):
    """
    Pick the best matching file from a list.
    - must_include: all terms must appear
    - any_include: at least one term appears (optional)
    """
    def score(fn):
        name = fn.lower()
        s = 0
        for t in must_include:
            if t.lower() in name:
                s += 10
            else:
                return -1
        if any_include:
            s += sum(1 for t in any_include if t.lower() in name)
        return s

    ranked = sorted(files, key=score, reverse=True)
    best = ranked[0] if ranked and score(ranked[0]) >= 0 else None
    return best

In [ ]:
FILES = {}

FILES["oracle_pdc"] = pick_file(
    xlsx_files, must_include=("pdc", "transportation", "matrix")
)

FILES["oracle_qmp"] = pick_file(
    xlsx_files, must_include=("qmp", "transportation", "matrix")
)

FILES["dhl_be"] = pick_file(
    xlsx_files, must_include=("id_", "emea"), any_include=("dhl", "be")
)

FILES["geodis"] = pick_file(
    xlsx_files, must_include=("geodis",)
)

FILES["nunner_out"] = pick_file(
    xlsx_files, must_include=("nunner", "outbound")
)

FILES["nunner_in"] = pick_file(
    xlsx_files, must_include=("nunner", "inbound")
)
FILES["dhl_invoice"] = pick_file(
    xlsx_files,
    must_include=("dhl",),
    any_include=("masterdata", "2025", "invoice")
)

FILES

{'oracle_pdc': 'C:\\Users\\atb6113\\Desktop\\Carrier project\\PDC_Transportation_Matrix_20251222060506.xlsx',
 'oracle_qmp': 'C:\\Users\\atb6113\\Desktop\\Carrier project\\QMP_Transportation_Matrix_20251222060644.xlsx',
 'dhl_be': 'C:\\Users\\atb6113\\Desktop\\Carrier project\\2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-090556-629.xlsx',
 'geodis': 'C:\\Users\\atb6113\\Desktop\\Carrier project\\Rates Geodis.xlsx',
 'nunner_out': 'C:\\Users\\atb6113\\Desktop\\Carrier project\\2025-02-19 Nunner offer  OUTBOUND version Final 1.1 Valid 2025.xlsx',
 'nunner_in': 'C:\\Users\\atb6113\\Desktop\\Carrier project\\2025-06-26 Nunner offer INBOUND version Final 3.0 valid 2025.xlsx',
 'dhl_invoice': 'C:\\Users\\atb6113\\Desktop\\Carrier project\\DHL MasterData2025.xlsx'}

Cell 1 — Map files automatically

This uses keywords to match the right files even if timestamps differ.

In [ ]:
import re

def pick_file(files, must_include=(), any_include=()):
    """
    Pick the best matching file from a list.
    - must_include: all terms must appear
    - any_include: at least one term appears (optional)
    """
    def score(fn):
        name = fn.lower()
        s = 0
        for t in must_include:
            if t.lower() in name:
                s += 10
            else:
                return -1
        if any_include:
            s += sum(1 for t in any_include if t.lower() in name)
        return s

    ranked = sorted(files, key=score, reverse=True)
    best = ranked[0] if ranked and score(ranked[0]) >= 0 else None
    return best

FILES = {}
FILES["oracle_pdc"] = pick_file(xlsx_files, must_include=("pdc", "transportation", "matrix"))
FILES["oracle_qmp"] = pick_file(xlsx_files, must_include=("qmp", "transportation", "matrix"))
FILES["dhl_be"]     = pick_file(xlsx_files, must_include=("id_", "emea"), any_include=("dhl", "be"))
FILES["geodis"]     = pick_file(xlsx_files, must_include=("geodis",))
FILES["nunner_out"] = pick_file(xlsx_files, must_include=("nunner", "outbound"))
FILES["nunner_in"]  = pick_file(xlsx_files, must_include=("nunner", "inbound"))
FILES["dhl_invoice"] = pick_file(xlsx_files,must_include=("dhl",),any_include=("masterdata", "2025", "invoice"))

for k,v in FILES.items():
    print(f"{k:12s} -> {v}")

oracle_pdc   -> C:\Users\atb6113\Desktop\Carrier project\PDC_Transportation_Matrix_20251222060506.xlsx
oracle_qmp   -> C:\Users\atb6113\Desktop\Carrier project\QMP_Transportation_Matrix_20251222060644.xlsx
dhl_be       -> C:\Users\atb6113\Desktop\Carrier project\2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-090556-629.xlsx
geodis       -> C:\Users\atb6113\Desktop\Carrier project\Rates Geodis.xlsx
nunner_out   -> C:\Users\atb6113\Desktop\Carrier project\2025-02-19 Nunner offer  OUTBOUND version Final 1.1 Valid 2025.xlsx
nunner_in    -> C:\Users\atb6113\Desktop\Carrier project\2025-06-26 Nunner offer INBOUND version Final 3.0 valid 2025.xlsx
dhl_invoice  -> C:\Users\atb6113\Desktop\Carrier project\DHL MasterData2025.xlsx

Cell 2 — Read sheets safely (multi-sheet ready)

In [ ]:
import pandas as pd

def list_sheets(path):
    xls = pd.ExcelFile(path)
    return xls.sheet_names

for k, path in FILES.items():
    if path:
        sheets = list_sheets(path)
        print(k, "|", os.path.basename(path), "| sheets:", len(sheets))
        print("  first sheets:", sheets[:8])

oracle_pdc | PDC_Transportation_Matrix_20251222060506.xlsx | sheets: 1
  first sheets: ['Sheet']
oracle_qmp | QMP_Transportation_Matrix_20251222060644.xlsx | sheets: 1
  first sheets: ['Sheet']
dhl_be | 2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-090556-629.xlsx | sheets: 24
  first sheets: ['BE Customer Cover', 'BE Zones TDI Export', 'BE Zones TDI Import', 'BE TD Exp WW', 'BE TD Imp WW', 'BE Zones TD 3rdCtry', 'BE Matrix TD 3rdCtry', 'BE TD 3rdCtry WW']
geodis | Rates Geodis.xlsx | sheets: 6
  first sheets: ['Tarifs MES ', 'Tarif express >30Kgs ', 'Tarifs express <30Kgs ', 'Tarifs AFF ', 'Tarifs Eurodirect', 'Charges']
nunner_out | 2025-02-19 Nunner offer  OUTBOUND version Final 1.1 Valid 2025.xlsx | sheets: 42
  first sheets: ['General Remarks', 'Fuel Matrix', 'AL', 'AT', 'BA', 'BE', 'BG', 'CH']
nunner_in | 2025-06-26 Nunner offer INBOUND version Final 3.0 valid 2025.xlsx | sheets: 19
  first sheets: ['General Remarks', 'Change History', 'Fuel Matrix', 'AT to BE', 'Sotragal', 'BE to BE', 'BG70 to BE', 'Domestic Volume PuursZwijdrecht']
dhl_invoice | DHL MasterData2025.xlsx | sheets: 2
  first sheets: ['DHL MasterData_2025', 'Sheet3']

Loadig new file of DHL Invoice file

In [ ]:
dhl_file = FILES["dhl_invoice"]

dhl_raw = pd.read_excel(
    dhl_file,
    sheet_name="DHL MasterData_2025"
)

# clean column names
dhl_raw.columns = [str(c).strip() for c in dhl_raw.columns]

print("DHL raw shape:", dhl_raw.shape)
dhl_raw.head()

DHL raw shape: (78531, 22)

,Invoice No,Invoice Date,Company Name,Account Number,Line Number,Item ID,DHL Product Description,PAL/COL,Amount,Weight Charge,...,Tax Amount,Tax Code,AWB Number,Weight,Shipper Reference,Shipment Date,Origin Code,Destination Code,Shipper Details,Receiver Details
0,BRUR005574697,2025-01-06,BV CMI FILTRATION BELGIUM,276860414.0,1,NaN,EXPRESS WORLDWIDE eu,1.0,307.93,NaN,...,64.67,A,9450038651,209.5,18300814,2024-12-09,BRUSSELS,LIL. LILLE,FIEGE NV - PLATFORM PUURS;BRABANTSTRAAT 4;PUUR...,APROLIS PIECES DE RECHANGES;207 IMPASSE NIKOLA...
1,BRUR005574697,2025-01-06,BV CMI FILTRATION BELGIUM,276860414.0,2,NaN,ADDRESS CORRECTION,1.0,11.00,NaN,...,2.31,A,9450038651,0.0,18300814,2024-12-09,BRUSSELS,LIL. LILLE,FIEGE NV - PLATFORM PUURS;BRABANTSTRAAT 4;PUUR...,APROLIS PIECES DE RECHANGES;207 IMPASSE NIKOLA...
2,BRUR005574697,2025-01-06,BV CMI FILTRATION BELGIUM,276860414.0,3,NaN,NON STACKABLE PALLET,1.0,137.50,NaN,...,28.88,A,9450038651,0.0,18300814,2024-12-09,BRUSSELS,LIL. LILLE,FIEGE NV - PLATFORM PUURS;BRABANTSTRAAT 4;PUUR...,APROLIS PIECES DE RECHANGES;207 IMPASSE NIKOLA...
3,BRUR005574697,2025-01-06,BV CMI FILTRATION BELGIUM,276860414.0,4,NaN,OVERWEIGHT PIECE,1.0,47.50,NaN,...,9.98,A,9450038651,0.0,18300814,2024-12-09,BRUSSELS,LIL. LILLE,FIEGE NV - PLATFORM PUURS;BRABANTSTRAAT 4;PUUR...,APROLIS PIECES DE RECHANGES;207 IMPASSE NIKOLA...
4,BRUR005574697,2025-01-06,BV CMI FILTRATION BELGIUM,276860414.0,5,NaN,FUEL SURCHARGE,1.0,136.17,NaN,...,28.60,A,9450038651,0.0,18300814,2024-12-09,BRUSSELS,LIL. LILLE,FIEGE NV - PLATFORM PUURS;BRABANTSTRAAT 4;PUUR...,APROLIS PIECES DE RECHANGES;207 IMPASSE NIKOLA...

In [ ]:
print(dhl_raw.columns.tolist())

['Invoice No', 'Invoice Date', 'Company Name', 'Account Number', 'Line Number', 'Item ID', 'DHL Product Description', 'PAL/COL', 'Amount', 'Weight Charge', 'Discount Amount', 'Discount Code', 'Tax Amount', 'Tax Code', 'AWB Number', 'Weight', 'Shipper Reference', 'Shipment Date', 'Origin Code', 'Destination Code', 'Shipper Details', 'Receiver Details']

In [ ]:
# ==============================
# DHL STANDARDIZATION
# ==============================

dhl = dhl_raw.copy()

# Clean column names just in case
dhl.columns = [str(c).strip() for c in dhl.columns]

# Standardize to project schema
dhl = dhl.rename(columns={
    "Invoice No": "INVOICE_NO",
    "Invoice Date": "INVOICE_DATE",
    "AWB Number": "SHIPMENT_ID",
    "DHL Product Description": "SERVICE_LEVEL_TYPE",
    "Amount": "INVOICED_LINEHAUL_AMOUNT",
    "Weight": "BILLABLE_WEIGHT",
    "Shipment Date": "SHIPMENT_DATE",
    "Origin Code": "ORIGIN_CODE",
    "Destination Code": "DESTINATION_CODE"
})

# Add required model columns
dhl["CARRIER"] = "DHL"
dhl["DIRECTION"] = "OUTBOUND"

# Numeric conversion
for c in ["INVOICED_LINEHAUL_AMOUNT", "BILLABLE_WEIGHT", "Weight Charge", "Discount Amount", "Tax Amount"]:
    if c in dhl.columns:
        dhl[c] = pd.to_numeric(dhl[c], errors="coerce")

# Dates
for c in ["INVOICE_DATE", "SHIPMENT_DATE"]:
    if c in dhl.columns:
        dhl[c] = pd.to_datetime(dhl[c], errors="coerce")

# Build a shipment key
dhl["SHIP_KEY"] = (
    dhl["SHIPMENT_ID"].astype(str).str.strip() + "|" +
    dhl["INVOICE_NO"].astype(str).str.strip() + "|DHL"
)

# Keep a clean modeling table
dhl_model = dhl[[
    "SHIP_KEY",
    "SHIPMENT_ID",
    "INVOICE_NO",
    "INVOICE_DATE",
    "SHIPMENT_DATE",
    "CARRIER",
    "DIRECTION",
    "SERVICE_LEVEL_TYPE",
    "ORIGIN_CODE",
    "DESTINATION_CODE",
    "BILLABLE_WEIGHT",
    "INVOICED_LINEHAUL_AMOUNT"
]].copy()

print("DHL model shape:", dhl_model.shape)
dhl_model.head()

DHL model shape: (78531, 12)

,SHIP_KEY,SHIPMENT_ID,INVOICE_NO,INVOICE_DATE,SHIPMENT_DATE,CARRIER,DIRECTION,SERVICE_LEVEL_TYPE,ORIGIN_CODE,DESTINATION_CODE,BILLABLE_WEIGHT,INVOICED_LINEHAUL_AMOUNT
0,9450038651|BRUR005574697|DHL,9450038651,BRUR005574697,2025-01-06,2024-12-09,DHL,OUTBOUND,EXPRESS WORLDWIDE eu,BRUSSELS,LIL. LILLE,209.5,307.93
1,9450038651|BRUR005574697|DHL,9450038651,BRUR005574697,2025-01-06,2024-12-09,DHL,OUTBOUND,ADDRESS CORRECTION,BRUSSELS,LIL. LILLE,0.0,11.00
2,9450038651|BRUR005574697|DHL,9450038651,BRUR005574697,2025-01-06,2024-12-09,DHL,OUTBOUND,NON STACKABLE PALLET,BRUSSELS,LIL. LILLE,0.0,137.50
3,9450038651|BRUR005574697|DHL,9450038651,BRUR005574697,2025-01-06,2024-12-09,DHL,OUTBOUND,OVERWEIGHT PIECE,BRUSSELS,LIL. LILLE,0.0,47.50
4,9450038651|BRUR005574697|DHL,9450038651,BRUR005574697,2025-01-06,2024-12-09,DHL,OUTBOUND,FUEL SURCHARGE,BRUSSELS,LIL. LILLE,0.0,136.17

In [ ]:
dhl_model[["INVOICED_LINEHAUL_AMOUNT", "BILLABLE_WEIGHT"]].describe()

       INVOICED_LINEHAUL_AMOUNT  BILLABLE_WEIGHT
count              78531.000000     78531.000000
mean                  77.761689        35.105824
std                  166.544389        96.378115
min                    0.000000         0.000000
25%                   10.000000         0.000000
50%                   30.410000         0.000000
75%                   70.280000         7.000000
max                 5384.740000      3087.000000

In [ ]:
dhl[["INVOICED_LINEHAUL_AMOUNT", "Weight Charge", "Discount Amount", "Tax Amount"]].describe()

       INVOICED_LINEHAUL_AMOUNT  Weight Charge  Discount Amount    Tax Amount
count              78531.000000            0.0              0.0  78531.000000
mean                  77.761689            NaN              NaN     15.750320
std                  166.544389            NaN              NaN     33.369334
min                    0.000000            NaN              NaN      0.000000
25%                   10.000000            NaN              NaN      1.760000
50%                   30.410000            NaN              NaN      6.080000
75%                   70.280000            NaN              NaN     14.130000
max                 5384.740000            NaN              NaN   1130.800000

Part 1 start “analytical approach: Oracle weight breaks

*   List item
*   List item


Load Oracle Transportation Matrix (PDC + QMP) cleanly

In [ ]:
import pandas as pd
import numpy as np
import re
from pathlib import Path

pd.set_option("display.max_columns", 200)

def clean_cols(df):
    df = df.copy()
    df.columns = [re.sub(r"\s+", "_", str(c).strip().upper()) for c in df.columns]
    return df

def assert_path(p, key):
    if p is None:
        raise ValueError(f"FILES['{key}'] is None -> file picker did not find a match. Check filenames in DATA_DIR.")
    p = Path(p)
    if not p.exists():
        raise FileNotFoundError(f"FILES['{key}'] points to a path that does not exist:\n{p}")
    return str(p)

def load_oracle_tm(path, site):
    df = pd.read_excel(path, engine="openpyxl")  # explicit engine for .xlsx
    df = clean_cols(df)
    df["SITE"] = site
    for c in ["BEGINNING_WEIGHT", "ENDING_WEIGHT"]:
        if c in df.columns:
            df[c] = pd.to_numeric(df[c], errors="coerce")
    return df

# --- checks ---
if "FILES" not in globals():
    raise NameError("FILES is not defined in this notebook. Run your FILES picker cell first.")

oracle_pdc_path = assert_path(FILES.get("oracle_pdc"), "oracle_pdc")
oracle_qmp_path = assert_path(FILES.get("oracle_qmp"), "oracle_qmp")

print("oracle_pdc ->", oracle_pdc_path)
print("oracle_qmp ->", oracle_qmp_path)

# --- load ---
pdc = load_oracle_tm(oracle_pdc_path, "PDC")
qmp = load_oracle_tm(oracle_qmp_path, "QMP")

oracle = pd.concat([pdc, qmp], ignore_index=True)
print("Oracle rows:", oracle.shape[0], "cols:", oracle.shape[1])
oracle.head(3)

oracle_pdc -> C:\Users\atb6113\Desktop\Carrier project\PDC_Transportation_Matrix_20251222060506.xlsx
oracle_qmp -> C:\Users\atb6113\Desktop\Carrier project\QMP_Transportation_Matrix_20251222060644.xlsx
Oracle rows: 7333 cols: 31

,ACCOUNT_NUMBER,CUSTOMER_NAME,SITE_USE_CODE,PARTY_SITE_NUMBER,SHIP_TO_LOCATION,BEGINNING_WEIGHT,ENDING_WEIGHT,CARRIER_CODE,CARRIER,MODE_OF_TRANSPORT,CREATED_BY,USER_NAME,CREATION_DATE,DEFAULT_FLAG,DEMAND_CLASS,WEIGHT_UOM,FREIGHT_TERMS,ORG_ID,SHIPMENT_PRIORITY,ADDRESS1,ADDRESS2,ADDRESS3,ADDRESS4,CITY,POSTAL_CODE,COUNTRY,COUNTRY_DESCRIPTION,MINIMUM_ORDER_VALUE,ENFORCE_PACK_QTY,BACKORDER_HOLD,SITE
0,333225,ALKHALIJ ENTERPRISES,SHIP_TO,4863263,F50331-ALKHALIJ ENTERPRISES,0.0,999999.0,CRA02,CRANE OCEAN,SEA,83604.0,Devopam Sarkar,2024-11-06 12:09:57.000,Y,PDC_STOCK,Kilogram,CFR,809,PDC_FO_DS,AL QUOZ ON SHEIKH ZAYED ROAD,Jebel Ali Port,NaN,NaN,DUBAI,0000,AE,United Arab Emirates,0.0,NO,NO,PDC
1,333225,ALKHALIJ ENTERPRISES,SHIP_TO,4863263,F50331-ALKHALIJ ENTERPRISES,0.0,999.0,DHL01,DHL EXPRESS EOB,AIR,84318.0,Ganna Pesliak,2025-02-05 22:14:15.000,N,PDC_STOCK,Kilogram,FCA,809,PDC_FO_DS,AL QUOZ ON SHEIKH ZAYED ROAD,Jebel Ali Port,NaN,NaN,DUBAI,0000,AE,United Arab Emirates,0.0,NO,NO,PDC
2,333225,ALKHALIJ ENTERPRISES,SHIP_TO,4863262,F5033-ALKHALIJ ENTERPRISES,251.0,999999.0,CUST03,AIR CUSTOMER PICK UP,AIR,84318.0,Ganna Pesliak,2025-01-28 14:37:44.000,N,PDC_STOCK,Kilogram,FCA,809,PDC_FO_DS,AL QUOZ ON SHEIKH ZAYED ROAD,NaN,NaN,NaN,DUBAI,0000,AE,United Arab Emirates,0.0,NO,NO,PDC

Cell 3 — Extract ROAD weight break table

In [ ]:
keep_cols = [
    "SITE","COUNTRY","COUNTRY_DESCRIPTION","MODE_OF_TRANSPORT",
    "CARRIER","CARRIER_CODE","SHIPMENT_PRIORITY","DEMAND_CLASS",
    "WEIGHT_UOM","BEGINNING_WEIGHT","ENDING_WEIGHT"
]
keep_cols = [c for c in keep_cols if c in oracle.columns]

oracle_wb = oracle[keep_cols].copy()

# keep only rows where weights exist
oracle_wb = oracle_wb.dropna(subset=["BEGINNING_WEIGHT","ENDING_WEIGHT"], how="any")

# ROAD only
oracle_wb_road = oracle_wb[oracle_wb["MODE_OF_TRANSPORT"].astype(str).str.upper().eq("ROAD")].copy()

oracle_wb_road = oracle_wb_road.drop_duplicates()

print("All weight breaks:", oracle_wb.shape)
print("ROAD weight breaks:", oracle_wb_road.shape)

oracle_wb_road.head(10)

All weight breaks: (3428, 11)
ROAD weight breaks: (324, 11)

,SITE,COUNTRY,COUNTRY_DESCRIPTION,MODE_OF_TRANSPORT,CARRIER,CARRIER_CODE,SHIPMENT_PRIORITY,DEMAND_CLASS,WEIGHT_UOM,BEGINNING_WEIGHT,ENDING_WEIGHT
61,PDC,RS,Serbia,ROAD,NUNNER EASTER EUROPE,NUN02,PDC_FO_DS,PDC_STOCK,Kilogram,150.0,999999.00
63,PDC,RS,Serbia,ROAD,DHL Economy,DHL02,PDC_FO_DS,PDC_STOCK,Kilogram,0.0,149.99
64,PDC,SE,Sweden,ROAD,NUNNER SCAND/GERM/EXPRESS,NUN03,PDC_FO_DS,PDC_STOCK,Kilogram,150.0,999999.00
66,PDC,SE,Sweden,ROAD,DHL Economy,DHL02,PDC_FO_DS,PDC_STOCK,Kilogram,0.0,149.99
72,PDC,RO,Romania,ROAD,DHL Economy,DHL02,PDC_FO_DS,PDC_STOCK,Kilogram,0.0,149.99
73,PDC,RO,Romania,ROAD,NUNNER EASTER EUROPE,NUN02,PDC_FO_DS,PDC_STOCK,Kilogram,150.0,999999.00
74,PDC,NL,Netherlands,ROAD,NUNNER BENELUX,NUN01,PDC_DS,PDC_STOCK,Kilogram,150.0,999999.00
75,PDC,NL,Netherlands,ROAD,DHL Economy,DHL02,PDC_DS,PDC_STOCK,Kilogram,0.0,149.99
76,PDC,UZ,Uzbekistan,ROAD,ROAD CUSTOMER PICK UP,CUST01,PDC_FO_DS,PDC_STOCK,Kilogram,0.0,999999.00
81,PDC,UA,Ukraine,ROAD,ROAD CUSTOMER PICK UP,CUST01,PDC_FO_DS,PDC_STOCK,Kilogram,0.0,999999.00

Cell 4 — Summary table: how Oracle is set up per country/carrier/service

In [ ]:
grp = ["SITE","COUNTRY","CARRIER","CARRIER_CODE","SHIPMENT_PRIORITY","WEIGHT_UOM"]

road_summary = (
    oracle_wb_road
    .groupby(grp, dropna=False)
    .agg(
        n_rows=("BEGINNING_WEIGHT","size"),
        min_begin=("BEGINNING_WEIGHT","min"),
        max_end=("ENDING_WEIGHT","max"),
        unique_begin=("BEGINNING_WEIGHT","nunique"),
        unique_end=("ENDING_WEIGHT","nunique"),
    )
    .reset_index()
    .sort_values(["SITE","COUNTRY","CARRIER","SHIPMENT_PRIORITY"])
)

road_summary.head(25)

,SITE,COUNTRY,CARRIER,CARRIER_CODE,SHIPMENT_PRIORITY,WEIGHT_UOM,n_rows,min_begin,max_end,unique_begin,unique_end
0,PDC,AE,DHL EXPRESS EOB,DHL01,PDC_FO_DS,Kilogram,1,0.0,999999.00,1,1
1,PDC,AE,ROAD CUSTOMER PICK UP,CUST01,PDC_FO_DS,Kilogram,1,0.0,999999.00,1,1
2,PDC,AL,DHL Economy,DHL02,PDC_FO_DS,Kilogram,1,0.0,149.99,1,1
3,PDC,AL,NUNNER EASTER EUROPE,NUN02,PDC_FO_DS,Kilogram,2,150.0,999999.00,1,2
4,PDC,AM,ROAD CUSTOMER PICK UP,CUST01,PDC_FO_DS,Kilogram,1,0.0,999999.00,1,1
5,PDC,AT,DHL Economy,DHL02,PDC_DS,Kilogram,1,0.0,149.99,1,1
6,PDC,AT,DHL Economy,DHL02,PDC_FO_DS,Kilogram,1,0.0,149.99,1,1
7,PDC,AT,DHL Economy,DHL02,PDC_FO_TU/FR,Kilogram,1,0.0,149.99,1,1
8,PDC,AT,DHL Economy,DHL02,PDC_MO,Kilogram,1,0.0,149.99,1,1
9,PDC,AT,NUNNER SCAND/GERM/EXPRESS,NUN03,PDC_DS,Kilogram,1,150.0,999999.00,1,1
10,PDC,AT,NUNNER SCAND/GERM/EXPRESS,NUN03,PDC_FO_DS,Kilogram,1,150.0,999999.00,1,1
11,PDC,AT,NUNNER SCAND/GERM/EXPRESS,NUN03,PDC_FO_TU/FR,Kilogram,1,150.0,999999.00,1,1
12,PDC,AT,NUNNER SCAND/GERM/EXPRESS,NUN03,PDC_MO,Kilogram,1,150.0,999999.00,1,1
13,PDC,AZ,ROAD CUSTOMER PICK UP,CUST01,PDC_FO_DS,Kilogram,1,0.0,999999.00,1,1
14,PDC,BA,DHL Economy,DHL02,PDC_FO_DS,Kilogram,1,0.0,149.99,1,1
15,PDC,BA,NUNNER EASTER EUROPE,NUN02,PDC_FO_DS,Kilogram,2,0.0,999999.00,2,1
16,PDC,BA,NUNNER FTL,NUN FTL,PDC_FO_DS,Kilogram,1,0.0,999999.00,1,1
17,PDC,BE,DHL Economy,DHL02,PDC_DS,Kilogram,2,0.0,999999.00,1,2
18,PDC,BE,DHL Economy,DHL02,PDC_FO_DS,Kilogram,3,0.0,999999.00,1,3
19,PDC,BE,DHL Economy,DHL02,PDC_TU/FR,Kilogram,1,0.0,149.99,1,1
20,PDC,BE,FIEGE SCRAP,FIEGE SCRAP,PDC_FO_DS,Kilogram,1,0.0,999999.00,1,1
21,PDC,BE,Fiege,FIE01,PDC_DS,Kilogram,2,0.0,999999.00,2,1
22,PDC,BE,Fiege,FIE01,PDC_FO_DS,Kilogram,1,0.0,999999.00,1,1
23,PDC,BE,Fiege,FIE01,PDC_TU/FR,Kilogram,1,150.0,999999.00,1,1
24,PDC,BE,NUNNER BENELUX,NUN01,PDC_DS,Kilogram,1,150.0,999999.00,1,1

Cell 5 — Data-quality checks (gaps/overlaps in weight breaks)

In [ ]:
def lane_continuity(df_lane):
    d = df_lane.sort_values(["BEGINNING_WEIGHT","ENDING_WEIGHT"]).copy()
    d["NEXT_BEGIN"] = d["BEGINNING_WEIGHT"].shift(-1)
    d["GAP_TO_NEXT"] = d["NEXT_BEGIN"] - d["ENDING_WEIGHT"]
    return d

# pick one lane (the biggest group) to inspect automatically
lane_key = (oracle_wb_road.groupby(grp).size().sort_values(ascending=False).index[0])
lane = oracle_wb_road.set_index(grp).loc[lane_key].reset_index()

print("Example lane:", lane_key)
lane_check = lane_continuity(lane)
lane_check[["BEGINNING_WEIGHT","ENDING_WEIGHT","NEXT_BEGIN","GAP_TO_NEXT"]].head(30)

Example lane: ('QMP', 'FR', 'GEODIS MESSAGERIE', 'GEO02', 'PDC_DS', 'Kilogram')

C:\Users\atb6113\AppData\Local\Temp\ipykernel_10960\373692806.py:9: PerformanceWarning: indexing past lexsort depth may impact performance.
  lane = oracle_wb_road.set_index(grp).loc[lane_key].reset_index()

    BEGINNING_WEIGHT  ENDING_WEIGHT  NEXT_BEGIN  GAP_TO_NEXT
9                0.0         1000.0         0.0      -1000.0
8                0.0         9999.0         0.0      -9999.0
4                0.0        99999.0         0.0     -99999.0
6                0.0       100000.0         0.0    -100000.0
2                0.0       999999.0         0.0    -999999.0
5                0.0      1000000.0         0.0   -1000000.0
10               0.0      9999999.0        30.1   -9999968.9
1               30.1         1000.0        30.1       -969.9
0               30.1       999999.0       150.0    -999849.0
7              150.0       999999.0      2500.0    -997499.0
3             2500.0       999999.0         NaN          NaN

Interpretation:

GAP_TO_NEXT > 0 ⇒ uncovered weight range (gap)

GAP_TO_NEXT < 0 ⇒ overlap (two breaks cover same weight range)

In [ ]:
oracle_wb.to_csv("oracle_weight_breaks_all.csv", index=False)
oracle_wb_road.to_csv("oracle_weight_breaks_road.csv", index=False)
road_summary.to_csv("oracle_road_weight_breaks_summary.csv", index=False)

print("Saved:",
      "oracle_weight_breaks_all.csv, oracle_weight_breaks_road.csv, oracle_road_weight_breaks_summary.csv")

Saved: oracle_weight_breaks_all.csv, oracle_weight_breaks_road.csv, oracle_road_weight_breaks_summary.csv

##Next (Part 2): Rate card ingestion

Part 2A — DHL rate card → standardized table

Inspect DHL workbook (sheet list + quick preview)

In [ ]:
import pandas as pd

dhl_path = FILES["dhl_be"]
print("DHL file:", dhl_path)

xls = pd.ExcelFile(dhl_path)
print("Number of sheets:", len(xls.sheet_names))
print("Sheets:")
for i, sh in enumerate(xls.sheet_names):
    print(f"{i:02d} - {sh}")

# Preview first 3 sheets (top 12 rows, no header to see structure)
for sh in xls.sheet_names[:3]:
    print("\n---", sh, "---")
    preview = pd.read_excel(dhl_path, sheet_name=sh, header=None, nrows=12)
    display(preview)

DHL file: C:\Users\atb6113\Desktop\Carrier project\2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-090556-629.xlsx
Number of sheets: 24
Sheets:
00 - BE Customer Cover
01 - BE Zones TDI Export
02 - BE Zones TDI Import
03 - BE TD Exp WW
04 - BE TD Imp WW
05 - BE Zones TD 3rdCtry
06 - BE Matrix TD 3rdCtry
07 - BE TD 3rdCtry WW
08 - BE TD Domestic
09 - BE Zones TD 3rdCtry Dom
10 - BE Matrix TD 3rdCtry Dom
11 - BE TD 3rdCty Dom
12 - BE Zones DDI Exp+Imp
13 - BE DD Exp Economy
14 - BE DD Imp Economy
15 - BE Zones DDI 3rdCtry
16 - BE Matrix DD 3rdCtry
17 - BE DD 3rdCty Economy
18 - S&S Published
19 - S&S Special Agreement
20 - Accounts
21 - BE Service Conditions
22 - BE Commercial Terms
23 - Payment Terms

--- BE Customer Cover ---

                                 0   1              2
0                      Cover Sheet NaN            NaN
1                              NaN NaN            NaN
2                      DHL Express NaN            NaN
3                          Belgium NaN            NaN
4  OFFER REFERENCE: 105852_01_EMEA NaN            NaN
5                      Version: 01 NaN            NaN
6                  Proposal for:\n NaN  Cummins Inc\n
7                 Proposal Date:\n NaN  07-Jul-2025\n
8             Offer Valid Until:\n NaN  06-Aug-2025\n

--- BE Zones TDI Export ---

,0,1,2,3,4,5,6,7,8,9,10
0,TIME DEFINITE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,DHL Express Belgium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Customer: Cummins Inc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,DHL EXPRESS INTERNATIONAL EXPORT ZONING,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Countries & Territories,Zone,NaN,Countries & Territories,Zone,NaN,Countries & Territories,Zone,NaN,Countries & Territories,Zone
5,Afghanistan (AF),12,NaN,Egypt (EG),11,NaN,Libya (LY),12,NaN,San Marino (SM),6
6,Albania (AL),8,NaN,El Salvador (SV),11,NaN,Liechtenstein (LI),6,NaN,Sao Tome And Principe (ST),12
7,Algeria (DZ),11,NaN,Eritrea (ER),12,NaN,Lithuania (LT),5,NaN,Saudi Arabia (SA),11
8,American Samoa (AS),12,NaN,Estonia (EE),5,NaN,Luxembourg (LU),1,NaN,Senegal (SN),12
9,Andorra (AD),6,NaN,Eswatini (SZ),12,NaN,Macau SAR China (MO),11,NaN,"Serbia, Rep. Of (RS)",8
10,Angola (AO),12,NaN,Ethiopia (ET),12,NaN,Madagascar (MG),12,NaN,Seychelles (SC),12
11,Anguilla (AI),12,NaN,Falkland Islands (FK),12,NaN,Malawi (MW),12,NaN,Sierra Leone (SL),12

--- BE Zones TDI Import ---

,0,1,2,3,4,5,6,7,8,9,10
0,TIME DEFINITE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,DHL Express Belgium,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Customer: Cummins Inc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,DHL EXPRESS INTERNATIONAL IMPORT ZONING,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Countries & Territories,Zone,NaN,Countries & Territories,Zone,NaN,Countries & Territories,Zone,NaN,Countries & Territories,Zone
5,Afghanistan (AF),12,NaN,El Salvador (SV),11,NaN,Libya (LY),12,NaN,Sao Tome And Principe (ST),12
6,Albania (AL),8,NaN,Eritrea (ER),12,NaN,Liechtenstein (LI),6,NaN,Saudi Arabia (SA),11
7,Algeria (DZ),11,NaN,Estonia (EE),5,NaN,Lithuania (LT),5,NaN,Senegal (SN),12
8,American Samoa (AS),12,NaN,Eswatini (SZ),12,NaN,Luxembourg (LU),1,NaN,"Serbia, Rep. Of (RS)",8
9,Andorra (AD),6,NaN,Ethiopia (ET),12,NaN,Macau SAR China (MO),11,NaN,Seychelles (SC),12
10,Angola (AO),12,NaN,Falkland Islands (FK),12,NaN,Madagascar (MG),12,NaN,Sierra Leone (SL),12
11,Anguilla (AI),12,NaN,Faroe Islands (FO),8,NaN,Malawi (MW),12,NaN,Singapore (SG),10

Read all DHL sheets “raw” + provenance

In [ ]:
import re
import numpy as np

def clean_cols(cols):
    return [re.sub(r"\s+", "_", str(c).strip().upper()) for c in cols]

def read_sheet_raw(path, sheet):
    df = pd.read_excel(path, sheet_name=sheet, header=None)
    df["__SOURCE_SHEET"] = sheet
    return df

dhl_raw_sheets = []
for sh in pd.ExcelFile(dhl_path).sheet_names:
    df = read_sheet_raw(dhl_path, sh)
    dhl_raw_sheets.append(df)

dhl_raw = pd.concat(dhl_raw_sheets, ignore_index=True)
print("Raw rows (all sheets stacked):", dhl_raw.shape)

Raw rows (all sheets stacked): (1737, 21)

Find “candidate” sheets that likely contain rate tables

This heuristic looks for keywords like ZONE / RATE / KG / WEIGHT in the first ~30 rows.

In [ ]:
KEYWORDS = ["ZONE", "RATE", "RATES", "KG", "KGS", "WEIGHT", "EXPORT", "IMPORT", "ECONOMY", "EXPRESS"]

def sheet_keyword_score(path, sheet, nrows=30):
    df = pd.read_excel(path, sheet_name=sheet, header=None, nrows=nrows)
    text = " ".join(df.astype(str).fillna("").values.flatten()).upper()
    score = sum(1 for k in KEYWORDS if k in text)
    return score

dhl_scores = []
for sh in pd.ExcelFile(dhl_path).sheet_names:
    dhl_scores.append((sh, sheet_keyword_score(dhl_path, sh)))

dhl_scores = sorted(dhl_scores, key=lambda x: x[1], reverse=True)
print("Top candidate sheets:")
for sh, sc in dhl_scores[:10]:
    print(f"{sc:02d}  {sh}")

Top candidate sheets:
07  BE Zones DDI Exp+Imp
06  BE Matrix DD 3rdCtry
05  BE Matrix TD 3rdCtry
05  BE Matrix TD 3rdCtry Dom
05  BE DD Exp Economy
05  BE DD Imp Economy
05  BE Zones DDI 3rdCtry
05  S&S Special Agreement
04  BE TD Exp WW
04  BE TD Imp WW

Auto-detect the header row for each candidate sheet

Many carrier files have a few “title rows” before the real table header.

In [ ]:
def detect_header_row(path, sheet, max_scan_rows=40):
    df = pd.read_excel(path, sheet_name=sheet, header=None, nrows=max_scan_rows)
    # look for a row that contains likely column headers
    # (zone, weight, kg, etc.)
    for i in range(min(max_scan_rows, len(df))):
        row = df.iloc[i].astype(str).str.upper().fillna("")
        row_text = " ".join(row.values)
        if ("ZONE" in row_text or "WEIGHT" in row_text or "KG" in row_text) and (row.nunique() > 3):
            return i
    return None

candidates = [sh for sh, sc in dhl_scores if sc >= 3][:12]  # adjust threshold if needed
print("Candidate sheets considered:", candidates)

header_map = {}
for sh in candidates:
    header_row = detect_header_row(dhl_path, sh)
    header_map[sh] = header_row
    print(f"{sh:40s} header_row={header_row}")

Candidate sheets considered: ['BE Zones DDI Exp+Imp', 'BE Matrix DD 3rdCtry', 'BE Matrix TD 3rdCtry', 'BE Matrix TD 3rdCtry Dom', 'BE DD Exp Economy', 'BE DD Imp Economy', 'BE Zones DDI 3rdCtry', 'S&S Special Agreement', 'BE TD Exp WW', 'BE TD Imp WW', 'BE DD 3rdCty Economy', 'S&S Published']
BE Zones DDI Exp+Imp                     header_row=None
BE Matrix DD 3rdCtry                     header_row=8
BE Matrix TD 3rdCtry                     header_row=8
BE Matrix TD 3rdCtry Dom                 header_row=8
BE DD Exp Economy                        header_row=6
BE DD Imp Economy                        header_row=6
BE Zones DDI 3rdCtry                     header_row=None
S&S Special Agreement                    header_row=8
BE TD Exp WW                             header_row=6
BE TD Imp WW                             header_row=6
BE DD 3rdCty Economy                     header_row=6
S&S Published                            header_row=7

Read candidate sheets using detected headers (clean columns)

In [ ]:
def read_with_header(path, sheet, header_row):
    df = pd.read_excel(path, sheet_name=sheet, header=header_row)
    df.columns = clean_cols(df.columns)
    df["__SOURCE_FILE"] = Path(path).name
    df["__SOURCE_SHEET"] = sheet
    df["__HEADER_ROW"] = header_row
    return df

dhl_tables = []
for sh, header_row in header_map.items():
    if header_row is None:
        continue
    try:
        t = read_with_header(dhl_path, sh, header_row)
        # drop fully empty columns
        t = t.dropna(axis=1, how="all")
        dhl_tables.append(t)
        print("Loaded:", sh, "| shape:", t.shape)
    except Exception as e:
        print("Skip:", sh, "| error:", e)

print("Loaded tables:", len(dhl_tables))

Loaded: BE Matrix DD 3rdCtry | shape: (10, 10)
Loaded: BE Matrix TD 3rdCtry | shape: (15, 15)
Loaded: BE Matrix TD 3rdCtry Dom | shape: (15, 15)
Loaded: BE DD Exp Economy | shape: (90, 13)
Loaded: BE DD Imp Economy | shape: (90, 13)
Loaded: S&S Special Agreement | shape: (12, 9)
Loaded: BE TD Exp WW | shape: (168, 23)
Loaded: BE TD Imp WW | shape: (163, 19)
Loaded: BE DD 3rdCty Economy | shape: (110, 17)
Loaded: S&S Published | shape: (68, 9)
Loaded tables: 10

Quick profiling to identify the “real” rate table(s)

This prints column names + sample rows so we can see which sheet is the tariff matrix.

In [ ]:
def profile_table(df, n=5):
    print("Sheet:", df["__SOURCE_SHEET"].iloc[0])
    print("Columns:", list(df.columns))
    display(df.head(n))

for t in dhl_tables[:6]:
    profile_table(t, n=8)

Sheet: BE Matrix DD 3rdCtry
Columns: ['ORIGIN_ZONE', '1', 'A', 'E', 'G', 'L', 'I', '__SOURCE_FILE', '__SOURCE_SHEET', '__HEADER_ROW']

,ORIGIN_ZONE,1,A,E,G,L,I,__SOURCE_FILE,__SOURCE_SHEET,__HEADER_ROW
0,NaN,2.0,E,B,H,L,J,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE Matrix DD 3rdCtry,8
1,NaN,3.0,G,H,C,L,K,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE Matrix DD 3rdCtry,8
2,NaN,4.0,L,L,L,F,L,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE Matrix DD 3rdCtry,8
3,NaN,5.0,I,J,K,L,D,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE Matrix DD 3rdCtry,8
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE Matrix DD 3rdCtry,8
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE Matrix DD 3rdCtry,8
6,● How to lookup 3rd Country Zone and Price:\n1...,NaN,NaN,NaN,NaN,NaN,NaN,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE Matrix DD 3rdCtry,8
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE Matrix DD 3rdCtry,8

Sheet: BE Matrix TD 3rdCtry
Columns: ['ORIGIN_ZONE', '1', 'A', 'B', 'C', 'D', 'E', 'D.1', 'E.1', 'F', 'D.2', 'F.1', '__SOURCE_FILE', '__SOURCE_SHEET', '__HEADER_ROW']

,ORIGIN_ZONE,1,A,B,C,D,E,D.1,E.1,F,D.2,F.1,__SOURCE_FILE,__SOURCE_SHEET,__HEADER_ROW
0,NaN,2.0,B,B,C,E,E,E,F,F,D,F,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE Matrix TD 3rdCtry,8
1,NaN,3.0,C,C,C,E,F,F,F,F,E,G,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE Matrix TD 3rdCtry,8
2,NaN,4.0,E,F,G,B,C,D,F,F,F,H,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE Matrix TD 3rdCtry,8
3,NaN,5.0,F,F,G,C,D,F,F,F,F,H,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE Matrix TD 3rdCtry,8
4,NaN,6.0,D,E,F,C,F,C,E,E,G,H,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE Matrix TD 3rdCtry,8
5,NaN,7.0,E,F,F,F,F,D,E,F,G,H,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE Matrix TD 3rdCtry,8
6,NaN,8.0,E,F,F,F,F,E,E,E,G,H,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE Matrix TD 3rdCtry,8
7,NaN,9.0,E,E,E,E,E,G,G,G,D,G,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE Matrix TD 3rdCtry,8

Sheet: BE Matrix TD 3rdCtry Dom
Columns: ['ORIGIN_ZONE', 'EU1', 'A', '-', '-.1', '-.2', '-.3', '-.4', '-.5', '-.6', '-.7', '-.8', '__SOURCE_FILE', '__SOURCE_SHEET', '__HEADER_ROW']

,ORIGIN_ZONE,EU1,A,-,-.1,-.2,-.3,-.4,-.5,-.6,-.7,-.8,__SOURCE_FILE,__SOURCE_SHEET,__HEADER_ROW
0,NaN,EU2,-,A,-,-,-,-,-,-,-,-,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE Matrix TD 3rdCtry Dom,8
1,NaN,EU3,-,-,A,-,-,-,-,-,-,-,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE Matrix TD 3rdCtry Dom,8
2,NaN,AP1,-,-,-,A,-,-,-,-,-,-,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE Matrix TD 3rdCtry Dom,8
3,NaN,AP2,-,-,-,-,A,-,-,-,-,-,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE Matrix TD 3rdCtry Dom,8
4,NaN,AM1,-,-,-,-,-,A,-,-,-,-,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE Matrix TD 3rdCtry Dom,8
5,NaN,AM2,-,-,-,-,-,-,A,-,-,-,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE Matrix TD 3rdCtry Dom,8
6,NaN,AM3,-,-,-,-,-,-,-,A,-,-,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE Matrix TD 3rdCtry Dom,8
7,NaN,MA1,-,-,-,-,-,-,-,-,A,-,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE Matrix TD 3rdCtry Dom,8

Sheet: BE DD Exp Economy
Columns: ['KG', 'UNNAMED:_1', 'ZONE_1', 'ZONE_2', 'ZONE_3', 'ZONE_4', 'ZONE_5', 'ZONE_6', 'ZONE_7', 'ZONE_8', '__SOURCE_FILE', '__SOURCE_SHEET', '__HEADER_ROW']

,KG,UNNAMED:_1,ZONE_1,ZONE_2,ZONE_3,ZONE_4,ZONE_5,ZONE_6,ZONE_7,ZONE_8,__SOURCE_FILE,__SOURCE_SHEET,__HEADER_ROW
0,1,NaN,7.46,9.65,9.8,10.24,11.04,10.74,14.82,14.97,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6
1,2,NaN,7.74,10.18,11.29,12.07,13.68,12.44,15.35,16.46,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6
2,3,NaN,7.95,10.59,12.08,12.62,15.57,13.42,15.77,17.25,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6
3,4,NaN,8.16,11,12.87,13.17,17.46,14.4,16.19,18.04,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6
4,5,NaN,8.37,11.41,13.66,13.72,19.35,15.38,16.61,18.83,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6
5,6,NaN,8.53,11.75,14.2,14.34,20.74,16.04,16.94,19.37,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6
6,7,NaN,8.69,12.09,14.74,14.96,22.13,16.7,17.27,19.91,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6
7,8,NaN,8.85,12.43,15.28,15.58,23.52,17.36,17.6,20.45,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6

Sheet: BE DD Imp Economy
Columns: ['KG', 'UNNAMED:_1', 'ZONE_1', 'ZONE_2', 'ZONE_3', 'ZONE_4', 'ZONE_5', 'ZONE_6', 'ZONE_7', 'ZONE_8', '__SOURCE_FILE', '__SOURCE_SHEET', '__HEADER_ROW']

,KG,UNNAMED:_1,ZONE_1,ZONE_2,ZONE_3,ZONE_4,ZONE_5,ZONE_6,ZONE_7,ZONE_8,__SOURCE_FILE,__SOURCE_SHEET,__HEADER_ROW
0,1,NaN,20.53,23.92,24.27,25.3,27.31,26.58,29.09,29.45,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Imp Economy,6
1,2,NaN,21.25,25.21,27.95,29.85,33.86,30.82,30.39,33.12,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Imp Economy,6
2,3,NaN,21.75,26.23,29.91,31.23,38.52,33.22,31.41,35.07,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Imp Economy,6
3,4,NaN,22.25,27.25,31.87,32.61,43.18,35.62,32.43,37.02,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Imp Economy,6
4,5,NaN,22.75,28.27,33.83,33.99,47.84,38.02,33.45,38.97,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Imp Economy,6
5,6,NaN,23.18,29.1,35.15,35.49,51.3,39.65,34.28,40.29,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Imp Economy,6
6,7,NaN,23.61,29.93,36.47,36.99,54.76,41.28,35.11,41.61,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Imp Economy,6
7,8,NaN,24.04,30.76,37.79,38.49,58.22,42.91,35.94,42.93,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Imp Economy,6

Sheet: S&S Special Agreement
Columns: ['YB', 'OVERSIZE_PIECE', 'A_FIXED_SURCHARGE_IS_APPLIED_TO_EVERY_PIECE,_INCLUDING_A_PALLET,_WITH_A_SINGLE_DIMENSION_IN_EXCESS_OF_100CM_(40_INCHES)._DOES_NOT_APPLY_TO_PIECES_ALREADY_SUBJECT_TO_OVERWEIGHT_PIECE_SURCHARGE.', 'UNNAMED:_4', '50.00%_OFF_PREVAILING_CHARGE', 'ALL_PRODUCTS', '__SOURCE_FILE', '__SOURCE_SHEET', '__HEADER_ROW']

,YB,OVERSIZE_PIECE,"A_FIXED_SURCHARGE_IS_APPLIED_TO_EVERY_PIECE,_INCLUDING_A_PALLET,_WITH_A_SINGLE_DIMENSION_IN_EXCESS_OF_100CM_(40_INCHES)._DOES_NOT_APPLY_TO_PIECES_ALREADY_SUBJECT_TO_OVERWEIGHT_PIECE_SURCHARGE.",UNNAMED:_4,50.00%_OFF_PREVAILING_CHARGE,ALL_PRODUCTS,__SOURCE_FILE,__SOURCE_SHEET,__HEADER_ROW
0,YC,NON STACKABLE PALLET,A fixed surcharge is applied to every pallet i...,NaN,50.00% off prevailing charge,All Products,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,S&S Special Agreement,8
1,YY,OVERWEIGHT PIECE,"A fixed surcharge is applied to every piece, i...",NaN,50.00% off prevailing charge,All Products,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,S&S Special Agreement,8
2,NaN,NaN,NaN,NaN,NaN,NaN,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,S&S Special Agreement,8
3,VOLUMETRIC WEIGHT,NaN,NaN,NaN,NaN,NaN,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,S&S Special Agreement,8
4,Name,NaN,Description,NaN,Volumetric Weight Divisor,NaN,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,S&S Special Agreement,8
5,VOLUMETRIC WEIGHT,NaN,Standard Conversion Factor for obtaining volum...,NaN,5 000,NaN,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,S&S Special Agreement,8
6,NaN,NaN,NaN,NaN,NaN,NaN,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,S&S Special Agreement,8
7,NaN,NaN,NaN,NaN,NaN,NaN,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,S&S Special Agreement,8

Standardization target schema

We want to create:

dhl_rate_fact

carrier = "DHL"

country_pricelist = "BE" (from filename)

direction (if export/import)

service_level

zone

weight

weight_uom (kg)

rate

currency (if present)

provenance (__SOURCE_FILE, __SOURCE_SHEET)

Standardize wide “zone x weight columns” tables (common DHL format)

In [ ]:
import re
import numpy as np
import pandas as pd

def normalize_header_token(x):
    s = str(x).strip().upper()
    s = s.replace(",", ".")                # 0,5 -> 0.5
    s = re.sub(r"\s+", " ", s)
    s = s.replace("KG", "").replace("KGS", "").strip()
    return s

def parse_weight_header(x):
    """
    Returns (weight_value_float) if header looks like a single weight,
    else returns None.
    Handles: '0,5', '0.5', '0.5 KG', ' 10 '.
    """
    s = normalize_header_token(x)
    # keep only numeric-ish patterns
    if re.fullmatch(r"\d+(\.\d+)?", s):
        return float(s)
    return None

def parse_weight_range_cell(x):
    """
    Returns (low, high) if a cell looks like a weight range like '0-0.5' or '0.0 - 0.5',
    else None.
    """
    s = str(x).strip().upper().replace(",", ".")
    s = re.sub(r"\s+", "", s)
    # examples: "0-0.5", "0.0-0.5", "10-20"
    m = re.fullmatch(r"(\d+(\.\d+)?)-(\d+(\.\d+)?)", s)
    if m:
        return float(m.group(1)), float(m.group(3))
    return None

def infer_orientation(df):
    """
    Decide if weights are columns or rows.
    - weights-as-columns: many column names parse as weights
    - weights-as-rows: first column contains numeric weights / ranges and other columns look like zones
    """
    cols = list(df.columns)
    w_cols = [c for c in cols if parse_weight_header(c) is not None]
    if len(w_cols) >= 3:
        return "weights_as_columns"

    # check weights as first column values
    first = df.columns[0]
    s = df[first].astype(str).head(30).tolist()
    n_numeric = 0
    n_range = 0
    for v in s:
        v2 = str(v).strip().replace(",", ".")
        if re.fullmatch(r"\d+(\.\d+)?", v2):
            n_numeric += 1
        if parse_weight_range_cell(v) is not None:
            n_range += 1
    if n_numeric + n_range >= 5:
        return "weights_as_rows"
    return "unknown"

def wide_weights_cols_to_long(df):
    # zone col = first non-provenance col that is NOT a weight header
    prov = {"__SOURCE_FILE","__SOURCE_SHEET","__HEADER_ROW"}
    nonprov_cols = [c for c in df.columns if c not in prov]
    weight_cols = [c for c in nonprov_cols if parse_weight_header(c) is not None]
    if len(weight_cols) < 3:
        return None

    zone_col = [c for c in nonprov_cols if c not in weight_cols][0]  # usually "ZONE"
    out = df[[zone_col] + weight_cols + [c for c in df.columns if c in prov]].copy()
    out = out.rename(columns={zone_col: "ZONE"})
    out = out.melt(
        id_vars=["ZONE"] + [c for c in df.columns if c in prov],
        value_vars=weight_cols,
        var_name="WEIGHT",
        value_name="RATE"
    )
    out["WEIGHT"] = out["WEIGHT"].map(parse_weight_header)
    out["RATE"] = pd.to_numeric(out["RATE"], errors="coerce")
    out = out.dropna(subset=["ZONE","WEIGHT","RATE"])
    return out

def wide_weights_rows_to_long(df):
    """
    Common DHL layout: first column = weight (or weight range), columns = zones.
    We'll melt zones into long format.
    """
    prov = {"__SOURCE_FILE","__SOURCE_SHEET","__HEADER_ROW"}
    nonprov_cols = [c for c in df.columns if c not in prov]

    weight_col = nonprov_cols[0]  # first column has weights
    zone_cols = nonprov_cols[1:]

    out = df[[weight_col] + zone_cols + [c for c in df.columns if c in prov]].copy()
    out = out.rename(columns={weight_col: "WEIGHT_RAW"})

    out = out.melt(
        id_vars=["WEIGHT_RAW"] + [c for c in df.columns if c in prov],
        value_vars=zone_cols,
        var_name="ZONE",
        value_name="RATE"
    )

    # Parse WEIGHT_RAW into WEIGHT (single) or WEIGHT_FROM/TO
    out["RATE"] = pd.to_numeric(out["RATE"], errors="coerce")

    # try single weight first
    w_single = out["WEIGHT_RAW"].astype(str).str.strip().str.replace(",", ".", regex=False)
    out["WEIGHT"] = pd.to_numeric(w_single, errors="coerce")

    # ranges
    ranges = out["WEIGHT_RAW"].map(parse_weight_range_cell)
    out["WEIGHT_FROM"] = ranges.map(lambda x: x[0] if isinstance(x, tuple) else np.nan)
    out["WEIGHT_TO"]   = ranges.map(lambda x: x[1] if isinstance(x, tuple) else np.nan)

    out = out.dropna(subset=["ZONE","RATE"], how="any")

    return out

standardized = []
debug = []

for t in dhl_tables:
    orient = infer_orientation(t)
    sheet = t["__SOURCE_SHEET"].iloc[0]
    debug.append((sheet, orient, t.shape, list(t.columns)[:10]))

    if orient == "weights_as_columns":
        out = wide_weights_cols_to_long(t)
        if out is not None and len(out):
            out["PARSER"] = "weights_as_columns"
            standardized.append(out)

    elif orient == "weights_as_rows":
        out = wide_weights_rows_to_long(t)
        if out is not None and len(out):
            out["PARSER"] = "weights_as_rows"
            standardized.append(out)

print("Classification summary:")
pd.DataFrame(debug, columns=["sheet","orientation","shape","first_cols"]).head(15)

Classification summary:

,sheet,orientation,shape,first_cols
0,BE Matrix DD 3rdCtry,unknown,"(10, 10)","[ORIGIN_ZONE, 1, A, E, G, L, I, __SOURCE_FILE,..."
1,BE Matrix TD 3rdCtry,unknown,"(15, 15)","[ORIGIN_ZONE, 1, A, B, C, D, E, D.1, E.1, F]"
2,BE Matrix TD 3rdCtry Dom,unknown,"(15, 15)","[ORIGIN_ZONE, EU1, A, -, -.1, -.2, -.3, -.4, -..."
3,BE DD Exp Economy,weights_as_rows,"(90, 13)","[KG, UNNAMED:_1, ZONE_1, ZONE_2, ZONE_3, ZONE_..."
4,BE DD Imp Economy,weights_as_rows,"(90, 13)","[KG, UNNAMED:_1, ZONE_1, ZONE_2, ZONE_3, ZONE_..."
5,S&S Special Agreement,unknown,"(12, 9)","[YB, OVERSIZE_PIECE, A_FIXED_SURCHARGE_IS_APPL..."
6,BE TD Exp WW,weights_as_rows,"(168, 23)","[KG, UNNAMED:_1, ZONE_1, ZONE_2, ZONE_3, ZONE_..."
7,BE TD Imp WW,weights_as_rows,"(163, 19)","[KG, UNNAMED:_1, ZONE_1, ZONE_2, ZONE_3, ZONE_..."
8,BE DD 3rdCty Economy,weights_as_rows,"(110, 17)","[KG, UNNAMED:_1, ZONE_A, ZONE_B, ZONE_C, ZONE_..."
9,S&S Published,unknown,"(68, 9)","[AA, SATURDAY_DELIVERY, ON_SHIPPER'S_REQUEST,_..."

Build DHL fact table (whatever parsed)

In [ ]:
if not standardized:
    print("Still nothing parsed — meaning DHL tables are likely not in a simple zone/weight matrix format, OR header detection picked wrong header rows.")
    print("Next step: print the top 3 candidate sheets and manually choose the correct header row.")
else:
    dhl_rate_fact = pd.concat(standardized, ignore_index=True)

    dhl_rate_fact["CARRIER"] = "DHL"
    dhl_rate_fact["WEIGHT_UOM"] = "KG"
    dhl_rate_fact["SERVICE_LEVEL"] = dhl_rate_fact["__SOURCE_SHEET"]  # temporary placeholder

    print("✅ dhl_rate_fact shape:", dhl_rate_fact.shape)
    display(dhl_rate_fact.head(30))

    dhl_rate_fact.to_csv("dhl_rate_fact_parsed.csv", index=False)
    print("Saved: dhl_rate_fact_parsed.csv")

✅ dhl_rate_fact shape: (7326, 13)

,WEIGHT_RAW,__SOURCE_FILE,__SOURCE_SHEET,__HEADER_ROW,ZONE,RATE,WEIGHT,WEIGHT_FROM,WEIGHT_TO,PARSER,CARRIER,WEIGHT_UOM,SERVICE_LEVEL
0,30.1,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6,UNNAMED:_1,70.00,30.1,NaN,NaN,weights_as_rows,DHL,KG,BE DD Exp Economy
1,70.1,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6,UNNAMED:_1,300.00,70.1,NaN,NaN,weights_as_rows,DHL,KG,BE DD Exp Economy
2,300.1,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6,UNNAMED:_1,99999.00,300.1,NaN,NaN,weights_as_rows,DHL,KG,BE DD Exp Economy
3,1,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6,ZONE_1,7.46,1.0,NaN,NaN,weights_as_rows,DHL,KG,BE DD Exp Economy
4,2,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6,ZONE_1,7.74,2.0,NaN,NaN,weights_as_rows,DHL,KG,BE DD Exp Economy
5,3,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6,ZONE_1,7.95,3.0,NaN,NaN,weights_as_rows,DHL,KG,BE DD Exp Economy
6,4,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6,ZONE_1,8.16,4.0,NaN,NaN,weights_as_rows,DHL,KG,BE DD Exp Economy
7,5,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6,ZONE_1,8.37,5.0,NaN,NaN,weights_as_rows,DHL,KG,BE DD Exp Economy
8,6,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6,ZONE_1,8.53,6.0,NaN,NaN,weights_as_rows,DHL,KG,BE DD Exp Economy
9,7,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6,ZONE_1,8.69,7.0,NaN,NaN,weights_as_rows,DHL,KG,BE DD Exp Economy
10,8,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6,ZONE_1,8.85,8.0,NaN,NaN,weights_as_rows,DHL,KG,BE DD Exp Economy
11,9,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6,ZONE_1,9.01,9.0,NaN,NaN,weights_as_rows,DHL,KG,BE DD Exp Economy
12,10,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6,ZONE_1,9.17,10.0,NaN,NaN,weights_as_rows,DHL,KG,BE DD Exp Economy
13,11,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6,ZONE_1,9.27,11.0,NaN,NaN,weights_as_rows,DHL,KG,BE DD Exp Economy
14,12,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6,ZONE_1,9.37,12.0,NaN,NaN,weights_as_rows,DHL,KG,BE DD Exp Economy
15,13,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6,ZONE_1,9.47,13.0,NaN,NaN,weights_as_rows,DHL,KG,BE DD Exp Economy
16,14,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6,ZONE_1,9.57,14.0,NaN,NaN,weights_as_rows,DHL,KG,BE DD Exp Economy
17,15,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6,ZONE_1,9.67,15.0,NaN,NaN,weights_as_rows,DHL,KG,BE DD Exp Economy
18,16,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6,ZONE_1,9.77,16.0,NaN,NaN,weights_as_rows,DHL,KG,BE DD Exp Economy
19,17,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6,ZONE_1,9.87,17.0,NaN,NaN,weights_as_rows,DHL,KG,BE DD Exp Economy
20,18,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6,ZONE_1,9.97,18.0,NaN,NaN,weights_as_rows,DHL,KG,BE DD Exp Economy
21,19,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6,ZONE_1,10.07,19.0,NaN,NaN,weights_as_rows,DHL,KG,BE DD Exp Economy
22,20,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6,ZONE_1,10.17,20.0,NaN,NaN,weights_as_rows,DHL,KG,BE DD Exp Economy
23,21,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6,ZONE_1,10.40,21.0,NaN,NaN,weights_as_rows,DHL,KG,BE DD Exp Economy
24,22,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6,ZONE_1,10.63,22.0,NaN,NaN,weights_as_rows,DHL,KG,BE DD Exp Economy
25,23,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6,ZONE_1,10.86,23.0,NaN,NaN,weights_as_rows,DHL,KG,BE DD Exp Economy
26,24,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6,ZONE_1,11.09,24.0,NaN,NaN,weights_as_rows,DHL,KG,BE DD Exp Economy
27,25,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6,ZONE_1,11.32,25.0,NaN,NaN,weights_as_rows,DHL,KG,BE DD Exp Economy
28,26,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6,ZONE_1,11.55,26.0,NaN,NaN,weights_as_rows,DHL,KG,BE DD Exp Economy
29,27,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD Exp Economy,6,ZONE_1,11.78,27.0,NaN,NaN,weights_as_rows,DHL,KG,BE DD Exp Economy

Saved: dhl_rate_fact_parsed.csv

build proper ranges

In [ ]:
import numpy as np

df = dhl_rate_fact.copy()
df = df[df["ZONE"].astype(str).str.contains("UNNAMED", na=False) == False].copy()

# Ensure numeric breakpoints
df["WEIGHT"] = pd.to_numeric(df["WEIGHT"], errors="coerce")
df["RATE"] = pd.to_numeric(df["RATE"], errors="coerce")
df = df.dropna(subset=["ZONE","WEIGHT","RATE"])

group_cols = [c for c in ["SERVICE_LEVEL","ZONE"] if c in df.columns]

def bands_half_open(g):
    g = g.sort_values("WEIGHT").copy()

    # Unique weights only (duplicate columns can create repeats)
    g = g.drop_duplicates(subset=["WEIGHT"])

    # half-open: [prev, current)
    g["WEIGHT_FROM"] = g["WEIGHT"].shift(1).fillna(0)
    g["WEIGHT_TO"] = g["WEIGHT"]

    # drop invalid
    g = g[g["WEIGHT_TO"] > g["WEIGHT_FROM"]]
    return g

df3 = df.groupby(group_cols, dropna=False, group_keys=False).apply(bands_half_open)

print("df3 shape:", df3.shape)
display(df3.head(20))

df3 shape: (7178, 13)

,WEIGHT_RAW,__SOURCE_FILE,__SOURCE_SHEET,__HEADER_ROW,ZONE,RATE,WEIGHT,WEIGHT_FROM,WEIGHT_TO,PARSER,CARRIER,WEIGHT_UOM,SERVICE_LEVEL
6102,1,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD 3rdCty Economy,6,ZONE_A,8.26,1.0,0.0,1.0,weights_as_rows,DHL,KG,BE DD 3rdCty Economy
6103,2,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD 3rdCty Economy,6,ZONE_A,8.59,2.0,1.0,2.0,weights_as_rows,DHL,KG,BE DD 3rdCty Economy
6104,3,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD 3rdCty Economy,6,ZONE_A,8.92,3.0,2.0,3.0,weights_as_rows,DHL,KG,BE DD 3rdCty Economy
6105,4,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD 3rdCty Economy,6,ZONE_A,9.25,4.0,3.0,4.0,weights_as_rows,DHL,KG,BE DD 3rdCty Economy
6106,5,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD 3rdCty Economy,6,ZONE_A,9.58,5.0,4.0,5.0,weights_as_rows,DHL,KG,BE DD 3rdCty Economy
6202,5.1,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD 3rdCty Economy,6,ZONE_A,0.25,5.1,5.0,5.1,weights_as_rows,DHL,KG,BE DD 3rdCty Economy
6107,6,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD 3rdCty Economy,6,ZONE_A,9.83,6.0,5.1,6.0,weights_as_rows,DHL,KG,BE DD 3rdCty Economy
6108,7,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD 3rdCty Economy,6,ZONE_A,10.08,7.0,6.0,7.0,weights_as_rows,DHL,KG,BE DD 3rdCty Economy
6109,8,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD 3rdCty Economy,6,ZONE_A,10.33,8.0,7.0,8.0,weights_as_rows,DHL,KG,BE DD 3rdCty Economy
6110,9,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD 3rdCty Economy,6,ZONE_A,10.58,9.0,8.0,9.0,weights_as_rows,DHL,KG,BE DD 3rdCty Economy
6111,10,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD 3rdCty Economy,6,ZONE_A,10.83,10.0,9.0,10.0,weights_as_rows,DHL,KG,BE DD 3rdCty Economy
6112,11,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD 3rdCty Economy,6,ZONE_A,11.08,11.0,10.0,11.0,weights_as_rows,DHL,KG,BE DD 3rdCty Economy
6113,12,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD 3rdCty Economy,6,ZONE_A,11.33,12.0,11.0,12.0,weights_as_rows,DHL,KG,BE DD 3rdCty Economy
6114,13,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD 3rdCty Economy,6,ZONE_A,11.58,13.0,12.0,13.0,weights_as_rows,DHL,KG,BE DD 3rdCty Economy
6115,14,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD 3rdCty Economy,6,ZONE_A,11.83,14.0,13.0,14.0,weights_as_rows,DHL,KG,BE DD 3rdCty Economy
6116,15,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD 3rdCty Economy,6,ZONE_A,12.08,15.0,14.0,15.0,weights_as_rows,DHL,KG,BE DD 3rdCty Economy
6117,16,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD 3rdCty Economy,6,ZONE_A,12.33,16.0,15.0,16.0,weights_as_rows,DHL,KG,BE DD 3rdCty Economy
6118,17,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD 3rdCty Economy,6,ZONE_A,12.58,17.0,16.0,17.0,weights_as_rows,DHL,KG,BE DD 3rdCty Economy
6119,18,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD 3rdCty Economy,6,ZONE_A,12.83,18.0,17.0,18.0,weights_as_rows,DHL,KG,BE DD 3rdCty Economy
6120,19,2025-07-10 ID_105852_01_EMEA_V01_BE_20250707-0...,BE DD 3rdCty Economy,6,ZONE_A,13.08,19.0,18.0,19.0,weights_as_rows,DHL,KG,BE DD 3rdCty Economy

Sanity check, verifying that there are no negative ranges and they’re ordered.

In [ ]:
import numpy as np
import pandas as pd

# df3 is your final banded table
# Must include WEIGHT_FROM and WEIGHT_TO

group_cols = [c for c in ["SERVICE_LEVEL", "ZONE"] if c in df3.columns]
print("Continuity check grouping by:", group_cols)

def continuity_gaps(g):
    g = g.sort_values(["WEIGHT_FROM","WEIGHT_TO"]).copy()
    return (g["WEIGHT_FROM"].iloc[1:].values - g["WEIGHT_TO"].iloc[:-1].values)

chk = (df3.groupby(group_cols, dropna=False)
          .apply(continuity_gaps)
          .reset_index(name="GAPS"))

display(chk.head(15))

# Flags
def has_pos(arr):
    return np.any(np.array(arr) > 1e-9) if hasattr(arr, "__len__") else False

def has_neg(arr):
    return np.any(np.array(arr) < -1e-9) if hasattr(arr, "__len__") else False

chk["HAS_POS_GAP"] = chk["GAPS"].apply(has_pos)
chk["HAS_NEG_GAP"] = chk["GAPS"].apply(has_neg)

print("Groups with positive gaps:", chk["HAS_POS_GAP"].sum())
print("Groups with overlaps (negative gaps):", chk["HAS_NEG_GAP"].sum())

# show only problematic groups
display(chk[chk["HAS_POS_GAP"] | chk["HAS_NEG_GAP"]].head(30))

Continuity check grouping by: ['SERVICE_LEVEL', 'ZONE']

,SERVICE_LEVEL,ZONE,GAPS
0,BE DD 3rdCty Economy,ZONE_A,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1,BE DD 3rdCty Economy,ZONE_B,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
2,BE DD 3rdCty Economy,ZONE_C,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
3,BE DD 3rdCty Economy,ZONE_D,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
4,BE DD 3rdCty Economy,ZONE_E,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
5,BE DD 3rdCty Economy,ZONE_F,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
6,BE DD 3rdCty Economy,ZONE_G,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
7,BE DD 3rdCty Economy,ZONE_H,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
8,BE DD 3rdCty Economy,ZONE_I,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
9,BE DD 3rdCty Economy,ZONE_J,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
10,BE DD 3rdCty Economy,ZONE_K,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
11,BE DD 3rdCty Economy,ZONE_L,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
12,BE DD Exp Economy,ZONE_1,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
13,BE DD Exp Economy,ZONE_2,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
14,BE DD Exp Economy,ZONE_3,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."

Groups with positive gaps: 0
Groups with overlaps (negative gaps): 0

Empty DataFrame
Columns: [SERVICE_LEVEL, ZONE, GAPS, HAS_POS_GAP, HAS_NEG_GAP]
Index: []

Save final DHL table

In [ ]:
df3.to_csv("dhl_rate_fact_final.csv", index=False)
print("Saved: dhl_rate_fact_final.csv")

Saved: dhl_rate_fact_final.csv

# Nunner

OUTBOUND first, then INBOUND. The goal is to convert the multi-sheet workbook into one standardized table:

carrier | direction | origin | destination | service_level | lane | weight_from | weight_to | weight_uom | rate | currency | source_file | source_sheet

Because Nunner files can be structured in different ways (country tabs vs lane tabs), we’ll do this in a robust “analytical” way:

inventory sheets

detect which sheets contain actual rate tables

auto-detect header rows

parse either “weights as rows” or “weights as columns”

Part 2B — Nunner OUTBOUND
 Sheet inventory + keyword scoring

In [ ]:
import pandas as pd
import re
import numpy as np

nunner_out_path = FILES["nunner_out"]
print("Nunner OUT file:", nunner_out_path)

xls = pd.ExcelFile(nunner_out_path)
print("Sheets:", len(xls.sheet_names))
print("First 25 sheet names:")
for sh in xls.sheet_names[:25]:
    print("-", sh)

KEYWORDS = ["RATE", "RATES", "EUR", "EURO", "KG", "KGS", "WEIGHT", "DEST", "COUNTRY", "ZONE", "LANE"]

def sheet_score(path, sheet, nrows=40):
    df = pd.read_excel(path, sheet_name=sheet, header=None, nrows=nrows)
    text = " ".join(df.astype(str).fillna("").values.flatten()).upper()
    return sum(1 for k in KEYWORDS if k in text)

scores = [(sh, sheet_score(nunner_out_path, sh)) for sh in xls.sheet_names]
scores = sorted(scores, key=lambda x: x[1], reverse=True)

print("\nTop candidate sheets:")
for sh, sc in scores[:15]:
    print(f"{sc:02d}  {sh}")

Nunner OUT file: C:\Users\atb6113\Desktop\Carrier project\2025-02-19 Nunner offer  OUTBOUND version Final 1.1 Valid 2025.xlsx
Sheets: 42
First 25 sheet names:
- General Remarks
- Fuel Matrix
- AL
- AT
- BA
- BE
- BG
- CH
- CY
- CZ
- DE
- DK
- EE
- ES
- FI
- FR
- GR
- HR
- HU
- IT
- KZ
- LT
- LU
- LV
- MT

Top candidate sheets:
06  General Remarks
06  RS
06  FR-57 Cargotec
06  Serbia
04  AL
04  AT
04  BA
04  BE
04  BG
04  CH
04  CY
04  CZ
04  DE
04  DK
04  EE

Preview top candidate sheets (to confirm structure)

In [ ]:
top = [sh for sh, sc in scores[:6]]
for sh in top:
    print("\n---", sh, "---")
    prev = pd.read_excel(nunner_out_path, sheet_name=sh, header=None, nrows=18)
    display(prev)

--- General Remarks ---

,0,1,2,3,4
0,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,Nunner
8,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,GENERAL REMARKS:,NaN,NaN
11,NaN,NaN,All transport orders are subject to the Nunner...,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,Client:,NaN,Cummins
14,NaN,NaN,From (shipping point):,NaN,B-2840 Rumst
15,NaN,NaN,Valid from:,NaN,2025-01-01 00:00:00
16,NaN,NaN,Prices are valid until :,NaN,2025-12-31 00:00:00
17,NaN,NaN,Currency,NaN,Euro

--- RS ---

     0   1     2            3        4
0  NaN NaN   NaN          NaN      NaN
1  NaN NaN   NaN          NaN      NaN
2  NaN NaN   NaN          KGS  Pancevo
3  NaN NaN   NaN  FTL transit      A/E
4  NaN NaN  Euro  LTL transit      A/G
5  NaN NaN     1          700   308.92
6  NaN NaN     2         1400   454.77
7  NaN NaN     3         2100   631.62
8  NaN NaN     4         2800    702.2
9  NaN NaN     5         3500   772.57
10 NaN NaN     6         4200   893.04
11 NaN NaN     7         4900   994.62
12 NaN NaN     8         5600  1094.02
13 NaN NaN     9         6300  1177.33
14 NaN NaN    10         7000  1439.89
15 NaN NaN    11         7700   1496.7
16 NaN NaN    12         8400  1650.57
17 NaN NaN    13         9100  1691.38

--- FR-57 Cargotec ---

,0,1,2,3,4,5
0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,KGS,57,NaN
3,NaN,NaN,NaN,FTL transit,A/B,NaN
4,NaN,Euro,Blok,LTL transit,A/C,"FR s shipments below 2,5 CBM the rate will be ..."
5,NaN,NaN,NaN,32,132.03,NaN
6,NaN,NaN,NaN,64,132.53,NaN
7,NaN,NaN,NaN,100,132.53,NaN
8,NaN,NaN,NaN,200,132.53,NaN
9,NaN,NaN,NaN,300,132.53,NaN
10,NaN,NaN,NaN,400,132.53,NaN
11,NaN,NaN,NaN,500,132.53,- Bi-weekly (delivery on MON and WED ...
12,NaN,NaN,NaN,600,132.53,NaN
13,NaN,1,NaN,700,132.53,NaN
14,NaN,NaN,NaN,800,140.92,NaN
15,NaN,NaN,1,875,147.22,NaN
16,NaN,NaN,NaN,900,149.31,NaN
17,NaN,NaN,NaN,1000,214.32,NaN

--- Serbia ---

,0,1,2,3,4,5,6,7,8,9,10
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,"Export rates Serbia, Beograd.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Loading:,NaN,NaN,"Be, Rumst.",NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KGS,Beograd,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FTL transit,A/E,NaN
6,NaN,Euro,NaN,NaN,Blok,NaN,NaN,NaN,LTL transit,A/G,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100,€,114.25
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200,€,159.30
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,300,€,182.37
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,400,€,198.85
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,500,€,215.33
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,600,€,236.20
13,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,700,€,252.69
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,800,€,273.56
15,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,875,€,281.25
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,900,€,283.45
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000,€,293.33

--- AL ---

                            0     1     2            3              4
0                         NaN   NaN   NaN          NaN            NaN
1                         NaN   NaN   NaN          NaN            NaN
2   Parcel transit till 32 kg   NaN   NaN          KGS  All postcodes
3                         NaN   NaN   NaN  FTL transit         On req
4                         NaN  Euro  Blok  LTL transit         On req
5                         NaN   NaN   NaN           32            NaN
6                         NaN   NaN   NaN           64         610.23
7                         NaN   NaN   NaN          100         610.23
8                         NaN   NaN   NaN          200         610.23
9                         NaN   NaN   NaN          300         610.23
10                        NaN   NaN   NaN          400         610.23
11                        NaN   NaN   NaN          500         610.23
12                        NaN   NaN   NaN          600         610.23
13                        NaN     1   NaN          700         610.23
14                        NaN   NaN   NaN          800         872.07
15                        NaN   NaN     1          875         872.07
16                        NaN   NaN   NaN          900         872.07
17                        NaN   NaN   NaN         1000         872.07

--- AT ---

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Parcel transit till 32 kg,NaN,NaN,KGS,10-19,20-29,30-39,40-49,50-59,60-69,70-79,80-89,90-99
3,2 days,NaN,NaN,FTL transit,A/C,A/C,A/C,A/C,A/C,A/C,A/C,A/C,A/C
4,NaN,Euro,Blok,LTL transit,A/D,A/D,A/D,A/D,A/D,A/D,A/D,A/D,A/D
5,NaN,NaN,NaN,32,14.54,14.54,14.54,14.54,14.54,14.54,14.54,14.54,14.54
6,NaN,NaN,NaN,64,145.51,145.51,145.51,142.2,142.2,142.2,158.74,158.74,170.85
7,NaN,NaN,NaN,100,145.51,145.51,145.51,142.2,142.2,142.2,158.74,158.74,170.85
8,NaN,1,NaN,700,145.51,145.51,145.51,142.2,142.2,142.2,158.74,158.74,170.85
9,NaN,NaN,1,875,159.83,159.83,159.83,153.22,153.22,153.22,173.06,173.06,188.49
10,NaN,2,NaN,1400,264.54,264.54,264.54,233.69,233.69,207.22,264.54,264.54,294.32
11,NaN,NaN,2,1750,275.57,275.57,275.57,264.54,264.54,252.43,275.57,275.57,343.92
12,NaN,3,NaN,2100,286.6,286.6,286.6,275.57,275.57,267.85,286.6,286.6,358.24
13,NaN,NaN,3,2625,308.65,308.65,308.65,297.63,297.63,297.63,308.65,308.65,421.09
14,NaN,4,NaN,2800,341.71,341.71,341.71,330.7,330.7,330.7,341.71,341.71,434.31
15,NaN,5,4,3500,374.77,374.77,374.77,363.76,363.76,363.76,374.77,374.77,499.35
16,NaN,6,NaN,4200,407.86,407.86,407.86,385.81,385.81,385.81,407.86,407.86,553.36
17,NaN,NaN,5,4375,440.92,440.92,440.92,418.87,418.87,418.87,440.92,440.92,572.1

Strong header-row detection + load candidate tables

In [ ]:
def best_header_row(path, sheet, scan_rows=80):
    df = pd.read_excel(path, sheet_name=sheet, header=None, nrows=scan_rows)
    best = (None, -1)
    for i in range(min(scan_rows, len(df))):
        row = df.iloc[i].astype(str).str.upper().fillna("")
        row_text = " ".join(row.values)

        # score by presence of business headers
        score = 0
        for k in ["WEIGHT", "KG", "DEST", "DESTINATION", "COUNTRY", "ZONE", "LANE", "RATE", "EUR"]:
            if k in row_text:
                score += 3

        # prefer rows with many non-empty cells
        nonempty = (row != "NAN").sum()
        score += min(nonempty, 12) * 0.2

        if score > best[1]:
            best = (i, score)
    return best

def clean_cols(cols):
    return [re.sub(r"\s+", "_", str(c).strip().upper()) for c in cols]

candidate_sheets = [sh for sh, sc in scores if sc >= 3][:20]  # threshold can be adjusted
print("Candidate sheets:", len(candidate_sheets))

nunner_tables = []
meta = []

for sh in candidate_sheets:
    hr, sc = best_header_row(nunner_out_path, sh)
    meta.append((sh, hr, sc))
    if hr is None:
        continue
    try:
        df = pd.read_excel(nunner_out_path, sheet_name=sh, header=hr)
        df.columns = clean_cols(df.columns)
        df = df.dropna(axis=1, how="all")
        df["__SOURCE_FILE"] = Path(nunner_out_path).name
        df["__SOURCE_SHEET"] = sh
        df["__HEADER_ROW"] = hr
        nunner_tables.append(df)
    except Exception as e:
        print("Skip", sh, e)

meta_df = pd.DataFrame(meta, columns=["sheet","header_row","score"]).sort_values("score", ascending=False)
display(meta_df.head(20))

print("Loaded candidate tables:", len(nunner_tables))

Candidate sheets: 20

              sheet  header_row  score
2    FR-57 Cargotec           4   13.0
0   General Remarks          23    9.4
11               CZ           2    5.4
18               GR           2    5.4
17               FR           2    5.4
16               FI           2    5.4
15               ES           2    5.4
14               EE           2    5.4
13               DK           2    5.4
12               DE           2    5.4
19               HR           2    5.4
9                CH           2    5.4
8                BG           2    5.4
5                AT           4    5.4
7                BE           4    4.0
6                BA           2    3.8
4                AL           4    3.8
3            Serbia           6    3.8
10               CY           4    3.8
1                RS           4    3.6

Loaded candidate tables: 20

Auto-orientation detection + standardize to long format

This handles both formats:

weights as columns (columns are 0.5, 1, 2, 5…)

weights as rows (first column contains weights, columns are destinations/zones)

In [ ]:
def norm_token(x):
    s = str(x).strip().upper()
    s = s.replace(",", ".")
    s = s.replace("KG", "").replace("KGS", "").strip()
    return s

def parse_weight_header(x):
    s = norm_token(x)
    if re.fullmatch(r"\d+(\.\d+)?", s):
        return float(s)
    return None

def parse_weight_range_cell(x):
    s = str(x).strip().upper().replace(",", ".")
    s = re.sub(r"\s+", "", s)
    m = re.fullmatch(r"(\d+(\.\d+)?)-(\d+(\.\d+)?)", s)
    if m:
        return float(m.group(1)), float(m.group(3))
    return None

def infer_orientation(df):
    prov = {"__SOURCE_FILE","__SOURCE_SHEET","__HEADER_ROW"}
    nonprov = [c for c in df.columns if c not in prov]
    weight_cols = [c for c in nonprov if parse_weight_header(c) is not None]
    if len(weight_cols) >= 3:
        return "weights_as_columns"

    # weights-as-rows check
    first = nonprov[0] if nonprov else None
    if first is None:
        return "unknown"
    s = df[first].astype(str).head(30)
    hits = 0
    for v in s:
        v2 = str(v).strip().replace(",", ".")
        if re.fullmatch(r"\d+(\.\d+)?", v2) or parse_weight_range_cell(v) is not None:
            hits += 1
    if hits >= 5:
        return "weights_as_rows"
    return "unknown"

def melt_weights_as_columns(df):
    prov = ["__SOURCE_FILE","__SOURCE_SHEET","__HEADER_ROW"]
    nonprov = [c for c in df.columns if c not in prov]
    weight_cols = [c for c in nonprov if parse_weight_header(c) is not None]
    if len(weight_cols) < 3:
        return None

    id_cols = [c for c in nonprov if c not in weight_cols]
    # pick a likely destination column if present
    # (if multiple id cols exist, we keep them as descriptive fields)
    out = df[id_cols + weight_cols + prov].copy()
    out = out.melt(id_vars=id_cols + prov, value_vars=weight_cols, var_name="WEIGHT", value_name="RATE")
    out["WEIGHT"] = out["WEIGHT"].map(parse_weight_header)
    out["RATE"] = pd.to_numeric(out["RATE"], errors="coerce")
    out = out.dropna(subset=["WEIGHT","RATE"])
    return out

def melt_weights_as_rows(df):
    prov = ["__SOURCE_FILE","__SOURCE_SHEET","__HEADER_ROW"]
    nonprov = [c for c in df.columns if c not in prov]
    if len(nonprov) < 2:
        return None

    weight_col = nonprov[0]
    dest_cols = nonprov[1:]

    out = df[[weight_col] + dest_cols + prov].copy()
    out = out.rename(columns={weight_col: "WEIGHT_RAW"})
    out = out.melt(id_vars=["WEIGHT_RAW"] + prov, value_vars=dest_cols, var_name="DEST", value_name="RATE")
    out["RATE"] = pd.to_numeric(out["RATE"], errors="coerce")

    # parse weight raw
    w_single = out["WEIGHT_RAW"].astype(str).str.strip().str.replace(",", ".", regex=False)
    out["WEIGHT"] = pd.to_numeric(w_single, errors="coerce")

    ranges = out["WEIGHT_RAW"].map(parse_weight_range_cell)
    out["WEIGHT_FROM"] = ranges.map(lambda x: x[0] if isinstance(x, tuple) else np.nan)
    out["WEIGHT_TO"]   = ranges.map(lambda x: x[1] if isinstance(x, tuple) else np.nan)

    out = out.dropna(subset=["RATE"])
    return out

parsed = []
debug = []

for t in nunner_tables:
    sh = t["__SOURCE_SHEET"].iloc[0]
    orient = infer_orientation(t)
    debug.append((sh, orient, t.shape, list(t.columns)[:10]))

    if orient == "weights_as_columns":
        out = melt_weights_as_columns(t)
        if out is not None and len(out):
            out["PARSER"] = "weights_as_columns"
            parsed.append(out)

    elif orient == "weights_as_rows":
        out = melt_weights_as_rows(t)
        if out is not None and len(out):
            out["PARSER"] = "weights_as_rows"
            parsed.append(out)

debug_df = pd.DataFrame(debug, columns=["sheet","orientation","shape","first_cols"])
display(debug_df.head(30))

print("Parsed tables:", len(parsed))

,sheet,orientation,shape,first_cols
0,General Remarks,unknown,"(29, 5)","[RATE_CALCULATION_METHOD, 1_LDM_=_1750_KG_/_1_..."
1,RS,unknown,"(38, 7)","[UNNAMED:_0, EURO, LTL_TRANSIT, A/G, __SOURCE_..."
2,FR-57 Cargotec,unknown,"(91, 8)","[EURO, BLOK, LTL_TRANSIT, A/C, FR_S_SHIPMENTS_..."
3,Serbia,unknown,"(89, 13)","[EURO, UNNAMED:_2, UNNAMED:_3, BLOK, UNNAMED:_..."
4,AL,unknown,"(91, 7)","[EURO, BLOK, LTL_TRANSIT, ON_REQ, __SOURCE_FIL..."
5,AT,weights_as_rows,"(55, 15)","[EURO, BLOK, LTL_TRANSIT, A/D, A/D.1, A/D.2, A..."
6,BA,unknown,"(83, 8)","[UNNAMED:_1, UNNAMED:_2, KGS, TUZLA, PREJEDOR,..."
7,BE,unknown,"(95, 8)","[EURO, BLOK, LTL_TRANSIT, A/B, A/B.1, __SOURCE..."
8,BG,weights_as_columns,"(93, 97)","[PARCEL_TRANSIT_TILL_32_KG, UNNAMED:_1, UNNAME..."
9,CH,weights_as_columns,"(123, 87)","[UNNAMED:_1, UNNAMED:_2, KGS, 10, 11, 12, 13, ..."
10,CY,unknown,"(91, 7)","[EURO, BLOK, LTL_TRANSIT, ON_REQ, __SOURCE_FIL..."
11,CZ,weights_as_columns,"(93, 67)","[PARCEL_TRANSIT_TILL_32_KG, UNNAMED:_1, UNNAME..."
12,DE,weights_as_columns,"(94, 102)","[UNNAMED:_0, UNNAMED:_1, UNNAMED:_2, KGS, 1, 2..."
13,DK,weights_as_columns,"(58, 95)","[PARCEL_TRANSIT_TILL_32_KG, UNNAMED:_1, UNNAME..."
14,EE,weights_as_columns,"(93, 57)","[PARCEL_TRANSIT_TILL_32_KG, UNNAMED:_1, UNNAME..."
15,ES,weights_as_columns,"(93, 57)","[PARCEL_TRANSIT_TILL_32_KG, UNNAMED:_1, UNNAME..."
16,FI,weights_as_columns,"(42, 107)","[PARCEL_TRANSIT_TILL_32_KG, UNNAMED:_1, UNNAME..."
17,FR,weights_as_columns,"(93, 102)","[PARCEL_TRANSIT_TILL_32_KG, UNNAMED:_1, UNNAME..."
18,GR,weights_as_columns,"(93, 63)","[PARCEL_TRANSIT_TILL_32_KG, UNNAMED:_1, UNNAME..."
19,HR,weights_as_columns,"(93, 27)","[PARCEL_TRANSIT_TILL_32_KG, UNNAMED:_1, UNNAME..."

Parsed tables: 12

Standardize Nunner OUT to a fact table + create ranges from breakpoints

In [ ]:
if not parsed:
    print("Nothing parsed yet. We need to manually identify one correct rate sheet and tune the parser.")
else:
    nunner_out_raw_long = pd.concat(parsed, ignore_index=True)

    # Standard columns
    nunner_out_raw_long["CARRIER"] = "NUNNER"
    nunner_out_raw_long["DIRECTION"] = "OUTBOUND"
    nunner_out_raw_long["WEIGHT_UOM"] = "KG"

    # If WEIGHT_FROM/WEIGHT_TO are missing but WEIGHT exists: build half-open intervals per sheet+dest
    group_cols = [c for c in ["__SOURCE_SHEET","DEST"] if c in nunner_out_raw_long.columns]

    if ("WEIGHT_FROM" not in nunner_out_raw_long.columns) or nunner_out_raw_long["WEIGHT_FROM"].isna().all():
        nunner_out_raw_long["WEIGHT"] = pd.to_numeric(nunner_out_raw_long.get("WEIGHT"), errors="coerce")

        def bands(g):
            g = g.dropna(subset=["WEIGHT"]).sort_values("WEIGHT").copy()
            g = g.drop_duplicates(subset=["WEIGHT"])
            g["WEIGHT_FROM"] = g["WEIGHT"].shift(1).fillna(0)
            g["WEIGHT_TO"] = g["WEIGHT"]
            return g[g["WEIGHT_TO"] > g["WEIGHT_FROM"]]

        nunner_out_fact = nunner_out_raw_long.groupby(group_cols, dropna=False, group_keys=False).apply(bands)
    else:
        nunner_out_fact = nunner_out_raw_long.copy()

    print("✅ nunner_out_fact:", nunner_out_fact.shape)
    display(nunner_out_fact.head(20))

    nunner_out_fact.to_csv("nunner_out_rate_fact.csv", index=False)
    print("Saved: nunner_out_rate_fact.csv")

✅ nunner_out_fact: (1112, 18)

,WEIGHT_RAW,__SOURCE_FILE,__SOURCE_SHEET,__HEADER_ROW,DEST,RATE,WEIGHT,WEIGHT_FROM,WEIGHT_TO,PARSER,PARCEL_TRANSIT_TILL_32_KG,UNNAMED:_1,UNNAMED:_2,KGS,UNNAMED:_0,CARRIER,DIRECTION,WEIGHT_UOM
84,1.0,2025-02-19 Nunner offer OUTBOUND version Fina...,AT,4,A/D,145.51,1.0,0.0,1.0,weights_as_rows,NaN,NaN,NaN,NaN,NaN,NUNNER,OUTBOUND,KG
86,2.0,2025-02-19 Nunner offer OUTBOUND version Fina...,AT,4,A/D,264.54,2.0,1.0,2.0,weights_as_rows,NaN,NaN,NaN,NaN,NaN,NUNNER,OUTBOUND,KG
88,3.0,2025-02-19 Nunner offer OUTBOUND version Fina...,AT,4,A/D,286.60,3.0,2.0,3.0,weights_as_rows,NaN,NaN,NaN,NaN,NaN,NUNNER,OUTBOUND,KG
90,4.0,2025-02-19 Nunner offer OUTBOUND version Fina...,AT,4,A/D,341.71,4.0,3.0,4.0,weights_as_rows,NaN,NaN,NaN,NaN,NaN,NUNNER,OUTBOUND,KG
91,5.0,2025-02-19 Nunner offer OUTBOUND version Fina...,AT,4,A/D,374.77,5.0,4.0,5.0,weights_as_rows,NaN,NaN,NaN,NaN,NaN,NUNNER,OUTBOUND,KG
92,6.0,2025-02-19 Nunner offer OUTBOUND version Fina...,AT,4,A/D,407.86,6.0,5.0,6.0,weights_as_rows,NaN,NaN,NaN,NaN,NaN,NUNNER,OUTBOUND,KG
94,7.0,2025-02-19 Nunner offer OUTBOUND version Fina...,AT,4,A/D,462.97,7.0,6.0,7.0,weights_as_rows,NaN,NaN,NaN,NaN,NaN,NUNNER,OUTBOUND,KG
96,8.0,2025-02-19 Nunner offer OUTBOUND version Fina...,AT,4,A/D,507.06,8.0,7.0,8.0,weights_as_rows,NaN,NaN,NaN,NaN,NaN,NUNNER,OUTBOUND,KG
98,9.0,2025-02-19 Nunner offer OUTBOUND version Fina...,AT,4,A/D,551.16,9.0,8.0,9.0,weights_as_rows,NaN,NaN,NaN,NaN,NaN,NUNNER,OUTBOUND,KG
99,10.0,2025-02-19 Nunner offer OUTBOUND version Fina...,AT,4,A/D,573.20,10.0,9.0,10.0,weights_as_rows,NaN,NaN,NaN,NaN,NaN,NUNNER,OUTBOUND,KG
100,11.0,2025-02-19 Nunner offer OUTBOUND version Fina...,AT,4,A/D,584.22,11.0,10.0,11.0,weights_as_rows,NaN,NaN,NaN,NaN,NaN,NUNNER,OUTBOUND,KG
102,12.0,2025-02-19 Nunner offer OUTBOUND version Fina...,AT,4,A/D,639.34,12.0,11.0,12.0,weights_as_rows,NaN,NaN,NaN,NaN,NaN,NUNNER,OUTBOUND,KG
104,13.0,2025-02-19 Nunner offer OUTBOUND version Fina...,AT,4,A/D,683.44,13.0,12.0,13.0,weights_as_rows,NaN,NaN,NaN,NaN,NaN,NUNNER,OUTBOUND,KG
106,14.0,2025-02-19 Nunner offer OUTBOUND version Fina...,AT,4,A/D,738.55,14.0,13.0,14.0,weights_as_rows,NaN,NaN,NaN,NaN,NaN,NUNNER,OUTBOUND,KG
107,15.0,2025-02-19 Nunner offer OUTBOUND version Fina...,AT,4,A/D,760.59,15.0,14.0,15.0,weights_as_rows,NaN,NaN,NaN,NaN,NaN,NUNNER,OUTBOUND,KG
108,16.0,2025-02-19 Nunner offer OUTBOUND version Fina...,AT,4,A/D,782.63,16.0,15.0,16.0,weights_as_rows,NaN,NaN,NaN,NaN,NaN,NUNNER,OUTBOUND,KG
110,17.0,2025-02-19 Nunner offer OUTBOUND version Fina...,AT,4,A/D,815.70,17.0,16.0,17.0,weights_as_rows,NaN,NaN,NaN,NaN,NaN,NUNNER,OUTBOUND,KG
112,18.0,2025-02-19 Nunner offer OUTBOUND version Fina...,AT,4,A/D,859.80,18.0,17.0,18.0,weights_as_rows,NaN,NaN,NaN,NaN,NaN,NUNNER,OUTBOUND,KG
114,19.0,2025-02-19 Nunner offer OUTBOUND version Fina...,AT,4,A/D,892.87,19.0,18.0,19.0,weights_as_rows,NaN,NaN,NaN,NaN,NaN,NUNNER,OUTBOUND,KG
115,20.0,2025-02-19 Nunner offer OUTBOUND version Fina...,AT,4,A/D,914.92,20.0,19.0,20.0,weights_as_rows,NaN,NaN,NaN,NaN,NaN,NUNNER,OUTBOUND,KG

Saved: nunner_out_rate_fact.csv

Identify “rate-like” sheets automatically (skip remarks)

In [ ]:
import pandas as pd
import numpy as np
import re

nunner_out_path = FILES["nunner_out"]
xls = pd.ExcelFile(nunner_out_path)

def is_remarks_sheet(name):
    return "REMARK" in name.upper()

rate_sheets = [sh for sh in xls.sheet_names if not is_remarks_sheet(sh)]
print("Candidate rate sheets:", len(rate_sheets))
print("Examples:", rate_sheets[:20])

Candidate rate sheets: 41
Examples: ['Fuel Matrix', 'AL', 'AT', 'BA', 'BE', 'BG', 'CH', 'CY', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GR', 'HR', 'HU', 'IT', 'KZ']

Read each sheet as raw + detect the weight column position

We’ll scan rows and find where numeric weights start.

In [ ]:
def read_raw(path, sheet):
    return pd.read_excel(path, sheet_name=sheet, header=None)

def find_weight_column(df, look_rows=60, look_cols=15):
    # Find a column that has many numeric values (weights) in lower rows
    best = (None, -1)
    for c in range(min(look_cols, df.shape[1])):
        col = df.iloc[:look_rows, c]
        nums = pd.to_numeric(col.astype(str).str.replace(",", ".", regex=False), errors="coerce")
        score = nums.notna().sum()
        if score > best[1]:
            best = (c, score)
    return best  # (col_idx, score)

# quick test on the sheets showed
for sh in ["AL", "AT", "Serbia", "FR-57 Cargotec"]:
    if sh in xls.sheet_names:
        raw = read_raw(nunner_out_path, sh)
        wc, sc = find_weight_column(raw)
        print(sh, "weight_col_idx:", wc, "score:", sc)

AL weight_col_idx: 3 score: 55
AT weight_col_idx: 3 score: 55
Serbia weight_col_idx: 8 score: 53
FR-57 Cargotec weight_col_idx: 4 score: 56

Extract a clean table from each sheet (weights + numeric rate columns)

This is the key cell: it converts messy sheets into a structured dataframe.

In [ ]:
def extract_nunner_sheet(path, sheet):
    raw = read_raw(path, sheet)

    # find weight column
    weight_col, _ = find_weight_column(raw)

    # determine start row: first row where weight is numeric AND next row also numeric
    w = pd.to_numeric(raw.iloc[:, weight_col].astype(str).str.replace(",", ".", regex=False), errors="coerce")
    start_row = None
    for i in range(len(w)-1):
        if pd.notna(w.iloc[i]) and pd.notna(w.iloc[i+1]):
            start_row = i
            break
    if start_row is None:
        return None

    # slice from start row downward and keep a reasonable number of columns
    block = raw.iloc[start_row:, :].copy()
    block.columns = [f"C{c}" for c in range(block.shape[1])]

    # clean weights
    block["WEIGHT"] = pd.to_numeric(block[f"C{weight_col}"].astype(str).str.replace(",", ".", regex=False), errors="coerce")
    block = block[block["WEIGHT"].notna()].copy()

    # find numeric columns that look like rates (exclude WEIGHT col)
    numeric_cols = []
    for c in block.columns:
        if c in ["WEIGHT", f"C{weight_col}"]:
            continue
        vals = pd.to_numeric(block[c].astype(str).str.replace(",", ".", regex=False).str.replace("€","", regex=False),
                             errors="coerce")
        if vals.notna().sum() >= max(5, int(0.5 * len(block))):  # enough numeric density
            numeric_cols.append(c)

    if not numeric_cols:
        return None

    # Build long format: one row per weight per numeric column
    out = block[["WEIGHT"] + numeric_cols].copy()
    out = out.melt(id_vars=["WEIGHT"], value_vars=numeric_cols, var_name="RATE_COL", value_name="RATE_RAW")

    out["RATE"] = pd.to_numeric(
        out["RATE_RAW"].astype(str).str.replace(",", ".", regex=False).str.replace("€","", regex=False),
        errors="coerce"
    )
    out = out.dropna(subset=["RATE"])

    # Attach provenance and labels
    out["SHEET"] = sheet
    out["__SOURCE_FILE"] = Path(path).name
    out["__SOURCE_SHEET"] = sheet
    return out

parsed_sheets = []
skipped = []

for sh in rate_sheets:
    t = extract_nunner_sheet(nunner_out_path, sh)
    if t is None or len(t) == 0:
        skipped.append(sh)
    else:
        parsed_sheets.append(t)

print("Parsed sheets:", len(parsed_sheets))
print("Skipped sheets:", len(skipped))
print("Some skipped:", skipped[:20])

nunner_out_long = pd.concat(parsed_sheets, ignore_index=True)
print("nunner_out_long:", nunner_out_long.shape)
nunner_out_long.head(20)

Parsed sheets: 39
Skipped sheets: 2
Some skipped: ['Gross-Gerau', 'Cestlice-Krakow-Lubin']
nunner_out_long: (121349, 7)

,WEIGHT,RATE_COL,RATE_RAW,RATE,SHEET,__SOURCE_FILE,__SOURCE_SHEET
0,0.0,C0,1.05,1.050,Fuel Matrix,2025-02-19 Nunner offer OUTBOUND version Fina...,Fuel Matrix
1,1.0,C0,1.1,1.100,Fuel Matrix,2025-02-19 Nunner offer OUTBOUND version Fina...,Fuel Matrix
2,1.5,C0,1.125,1.125,Fuel Matrix,2025-02-19 Nunner offer OUTBOUND version Fina...,Fuel Matrix
3,2.0,C0,1.15,1.150,Fuel Matrix,2025-02-19 Nunner offer OUTBOUND version Fina...,Fuel Matrix
4,2.5,C0,1.175,1.175,Fuel Matrix,2025-02-19 Nunner offer OUTBOUND version Fina...,Fuel Matrix
5,3.0,C0,1.2,1.200,Fuel Matrix,2025-02-19 Nunner offer OUTBOUND version Fina...,Fuel Matrix
6,3.5,C0,1.225,1.225,Fuel Matrix,2025-02-19 Nunner offer OUTBOUND version Fina...,Fuel Matrix
7,4.0,C0,1.25,1.250,Fuel Matrix,2025-02-19 Nunner offer OUTBOUND version Fina...,Fuel Matrix
8,4.5,C0,1.275,1.275,Fuel Matrix,2025-02-19 Nunner offer OUTBOUND version Fina...,Fuel Matrix
9,5.0,C0,1.3,1.300,Fuel Matrix,2025-02-19 Nunner offer OUTBOUND version Fina...,Fuel Matrix
10,5.5,C0,1.325,1.325,Fuel Matrix,2025-02-19 Nunner offer OUTBOUND version Fina...,Fuel Matrix
11,6.0,C0,1.35,1.350,Fuel Matrix,2025-02-19 Nunner offer OUTBOUND version Fina...,Fuel Matrix
12,6.5,C0,1.375,1.375,Fuel Matrix,2025-02-19 Nunner offer OUTBOUND version Fina...,Fuel Matrix
13,7.0,C0,1.4,1.400,Fuel Matrix,2025-02-19 Nunner offer OUTBOUND version Fina...,Fuel Matrix
14,7.5,C0,1.425,1.425,Fuel Matrix,2025-02-19 Nunner offer OUTBOUND version Fina...,Fuel Matrix
15,8.0,C0,1.45,1.450,Fuel Matrix,2025-02-19 Nunner offer OUTBOUND version Fina...,Fuel Matrix
16,8.5,C0,1.475,1.475,Fuel Matrix,2025-02-19 Nunner offer OUTBOUND version Fina...,Fuel Matrix
17,64.0,C4,610.23,610.230,AL,2025-02-19 Nunner offer OUTBOUND version Fina...,AL
18,100.0,C4,610.23,610.230,AL,2025-02-19 Nunner offer OUTBOUND version Fina...,AL
19,200.0,C4,610.23,610.230,AL,2025-02-19 Nunner offer OUTBOUND version Fina...,AL

Decode what RATE_COL means (postcode band / service split)

For the Austria sheet, those columns correspond to postcode ranges. We can pull those from the header rows above the table.

We’ll attempt to infer “band labels” by reading the row where the table started. If we can’t reliably, we keep RATE_COL and interpret later.

In [ ]:
# For now: keep RATE_COL as a dimension
# We'll name it POSTCODE_BAND when it matches patterns like '10-19'

nunner_out_long["POSTCODE_BAND"] = nunner_out_long["RATE_COL"].astype(str).str.extract(r"(\d{2}-\d{2})", expand=False)

nunner_out_long[["SHEET","RATE_COL","POSTCODE_BAND"]].drop_duplicates().head(30)

            SHEET RATE_COL POSTCODE_BAND
0     Fuel Matrix       C0           NaN
17             AL       C4           NaN
106            AT       C1           NaN
139            AT       C4           NaN
194            AT       C5           NaN
249            AT       C6           NaN
304            AT       C7           NaN
359            AT       C8           NaN
414            AT       C9           NaN
469            AT      C10           NaN
524            AT      C11           NaN
579            AT      C12           NaN
634            BA       C4           NaN
715            BA       C5           NaN
796            BE       C4           NaN
890            BE       C5           NaN
984            BG       C3           NaN
1075           BG       C5           NaN
1166           BG       C6           NaN
1257           BG       C7           NaN
1348           BG       C8           NaN
1439           BG       C9           NaN
1530           BG      C10           NaN
1621           BG      C11           NaN
1712           BG      C12           NaN
1803           BG      C13           NaN
1894           BG      C14           NaN
1985           BG      C15           NaN
2076           BG      C16           NaN
2167           BG      C17           NaN

Build weight ranges (half-open) + finalize Nunner OUTBOUND fact table

In [ ]:
df = nunner_out_long.copy()

df["CARRIER"] = "NUNNER"
df["DIRECTION"] = "OUTBOUND"
df["WEIGHT_UOM"] = "KG"
df["CURRENCY"] = "EUR"   # preview shows Euro in header, so we set EUR

# Create half-open bands per sheet + rate_col
df["WEIGHT"] = pd.to_numeric(df["WEIGHT"], errors="coerce")
df = df.dropna(subset=["WEIGHT","RATE"])

group_cols = ["SHEET","RATE_COL"]
def bands(g):
    g = g.sort_values("WEIGHT").copy()
    g = g.drop_duplicates(subset=["WEIGHT"])
    g["WEIGHT_FROM"] = g["WEIGHT"].shift(1).fillna(0)
    g["WEIGHT_TO"] = g["WEIGHT"]
    return g[g["WEIGHT_TO"] > g["WEIGHT_FROM"]]

nunner_out_fact = df.groupby(group_cols, dropna=False, group_keys=False).apply(bands)

# Add "destination" approximation:
# - if sheet looks like a country code (AL, AT) -> destination_country = sheet
# - else keep destination_country blank and use sheet as lane label
nunner_out_fact["DESTINATION_COUNTRY"] = np.where(
    nunner_out_fact["SHEET"].str.fullmatch(r"[A-Z]{2}"),
    nunner_out_fact["SHEET"],
    np.nan
)
nunner_out_fact["LANE_LABEL"] = nunner_out_fact["SHEET"]

cols = [
    "CARRIER","DIRECTION","DESTINATION_COUNTRY","LANE_LABEL","POSTCODE_BAND",
    "WEIGHT_FROM","WEIGHT_TO","WEIGHT_UOM","RATE","CURRENCY",
    "__SOURCE_FILE","__SOURCE_SHEET"
]
nunner_out_fact_final = nunner_out_fact[cols].copy()

print("✅ Nunner OUT final:", nunner_out_fact_final.shape)
display(nunner_out_fact_final.head(5))

nunner_out_fact_final.to_csv("nunner_out_rate_fact_final.csv", index=False)
print("Saved: nunner_out_rate_fact_final.csv")

✅ Nunner OUT final: (115026, 12)

,CARRIER,DIRECTION,DESTINATION_COUNTRY,LANE_LABEL,POSTCODE_BAND,WEIGHT_FROM,WEIGHT_TO,WEIGHT_UOM,RATE,CURRENCY,__SOURCE_FILE,__SOURCE_SHEET
17,NUNNER,OUTBOUND,AL,AL,NaN,0.0,64.0,KG,610.23,EUR,2025-02-19 Nunner offer OUTBOUND version Fina...,AL
18,NUNNER,OUTBOUND,AL,AL,NaN,64.0,100.0,KG,610.23,EUR,2025-02-19 Nunner offer OUTBOUND version Fina...,AL
19,NUNNER,OUTBOUND,AL,AL,NaN,100.0,200.0,KG,610.23,EUR,2025-02-19 Nunner offer OUTBOUND version Fina...,AL
20,NUNNER,OUTBOUND,AL,AL,NaN,200.0,300.0,KG,610.23,EUR,2025-02-19 Nunner offer OUTBOUND version Fina...,AL
21,NUNNER,OUTBOUND,AL,AL,NaN,300.0,400.0,KG,610.23,EUR,2025-02-19 Nunner offer OUTBOUND version Fina...,AL

Saved: nunner_out_rate_fact_final.csv

A — Extract postcode bands for AT (and similar sheets)
Cell N11 — Build a “column label map” (C1 → 10-19, etc.) per sheet

This reads the header rows above the weight table and finds patterns like 10-19.

In [ ]:
import pandas as pd
import numpy as np
import re
from pathlib import Path

def get_col_band_map(path, sheet, max_rows=30):
    """
    For sheets like AT: locate the row containing postcode bands (e.g., 10-19, 20-29, ...)
    and map column index -> label.
    """
    raw = pd.read_excel(path, sheet_name=sheet, header=None, nrows=max_rows)
    # search for a row containing multiple patterns like NN-NN
    best_row = None
    best_hits = 0

    for i in range(len(raw)):
        row = raw.iloc[i].astype(str).fillna("")
        hits = row.str.contains(r"^\s*\d{2}\s*-\s*\d{2}\s*$", regex=True).sum()
        if hits > best_hits:
            best_hits = hits
            best_row = i

    if best_row is None or best_hits < 2:
        return {}  # no band row

    row = raw.iloc[best_row].astype(str).fillna("")
    band_map = {}
    for col_idx, val in enumerate(row.values):
        s = str(val).strip()
        if re.fullmatch(r"\d{2}\s*-\s*\d{2}", s):
            band_map[f"C{col_idx}"] = s.replace(" ", "")
    return band_map

# Build band maps for all parsed sheets
band_maps = {}
for sh in nunner_out_long["SHEET"].unique():
    band_maps[sh] = get_col_band_map(nunner_out_path, sh)

# Example: check AT
print("AT band map:", band_maps.get("AT", {}))

AT band map: {'C4': '10-19', 'C5': '20-29', 'C6': '30-39', 'C7': '40-49', 'C8': '50-59', 'C9': '60-69', 'C10': '70-79', 'C11': '80-89', 'C12': '90-99'}

Apply the mapping to fill POSTCODE_BAND

In [ ]:
df = nunner_out_fact_final.copy()

# fill postcode band from mapping using RATE_COL
def lookup_band(row):
    sh = row["LANE_LABEL"]
    rc = row.get("RATE_COL", None)  # not present in final, so we'll reconstruct below if needed
    return None

# We need RATE_COL in the final table, so rebuild from nunner_out_fact (before selecting cols)


# easiest: rebuild from nunner_out_long quickly (small cost)
tmp = nunner_out_long.copy()
tmp["CARRIER"] = "NUNNER"
tmp["DIRECTION"] = "OUTBOUND"
tmp["WEIGHT_UOM"] = "KG"
tmp["CURRENCY"] = "EUR"

tmp["WEIGHT"] = pd.to_numeric(tmp["WEIGHT"], errors="coerce")
tmp["RATE"] = pd.to_numeric(tmp["RATE"], errors="coerce")
tmp = tmp.dropna(subset=["WEIGHT","RATE"])

def bands(g):
    g = g.sort_values("WEIGHT").copy()
    g = g.drop_duplicates(subset=["WEIGHT"])
    g["WEIGHT_FROM"] = g["WEIGHT"].shift(1).fillna(0)
    g["WEIGHT_TO"] = g["WEIGHT"]
    return g[g["WEIGHT_TO"] > g["WEIGHT_FROM"]]

tmp_banded = tmp.groupby(["SHEET","RATE_COL"], dropna=False, group_keys=False).apply(bands)

tmp_banded["DESTINATION_COUNTRY"] = np.where(tmp_banded["SHEET"].str.fullmatch(r"[A-Z]{2}"), tmp_banded["SHEET"], np.nan)
tmp_banded["LANE_LABEL"] = tmp_banded["SHEET"]

# apply postcode band map
tmp_banded["POSTCODE_BAND"] = tmp_banded.apply(
    lambda r: band_maps.get(r["SHEET"], {}).get(r["RATE_COL"], np.nan),
    axis=1
)

# remove Fuel Matrix from main table (we keep separate later)
main = tmp_banded[tmp_banded["SHEET"].str.upper().ne("FUEL MATRIX")].copy()

nunner_out_fact_final_v2 = main[
    ["CARRIER","DIRECTION","DESTINATION_COUNTRY","LANE_LABEL","POSTCODE_BAND",
     "WEIGHT_FROM","WEIGHT_TO","WEIGHT_UOM","RATE","CURRENCY",
     "__SOURCE_FILE","__SOURCE_SHEET"]
].copy()

print("✅ Nunner OUT final v2:", nunner_out_fact_final_v2.shape)
display(nunner_out_fact_final_v2[nunner_out_fact_final_v2["LANE_LABEL"].eq("AT")].head(10))

nunner_out_fact_final_v2.to_csv("nunner_out_rate_fact_final_v2.csv", index=False)
print("Saved: nunner_out_rate_fact_final_v2.csv")

✅ Nunner OUT final v2: (115010, 12)

,CARRIER,DIRECTION,DESTINATION_COUNTRY,LANE_LABEL,POSTCODE_BAND,WEIGHT_FROM,WEIGHT_TO,WEIGHT_UOM,RATE,CURRENCY,__SOURCE_FILE,__SOURCE_SHEET
106,NUNNER,OUTBOUND,AT,AT,NaN,0.0,700.0,KG,1.0,EUR,2025-02-19 Nunner offer OUTBOUND version Fina...,AT
107,NUNNER,OUTBOUND,AT,AT,NaN,700.0,1400.0,KG,2.0,EUR,2025-02-19 Nunner offer OUTBOUND version Fina...,AT
108,NUNNER,OUTBOUND,AT,AT,NaN,1400.0,2100.0,KG,3.0,EUR,2025-02-19 Nunner offer OUTBOUND version Fina...,AT
109,NUNNER,OUTBOUND,AT,AT,NaN,2100.0,2800.0,KG,4.0,EUR,2025-02-19 Nunner offer OUTBOUND version Fina...,AT
110,NUNNER,OUTBOUND,AT,AT,NaN,2800.0,3500.0,KG,5.0,EUR,2025-02-19 Nunner offer OUTBOUND version Fina...,AT
111,NUNNER,OUTBOUND,AT,AT,NaN,3500.0,4200.0,KG,6.0,EUR,2025-02-19 Nunner offer OUTBOUND version Fina...,AT
112,NUNNER,OUTBOUND,AT,AT,NaN,4200.0,4900.0,KG,7.0,EUR,2025-02-19 Nunner offer OUTBOUND version Fina...,AT
113,NUNNER,OUTBOUND,AT,AT,NaN,4900.0,5600.0,KG,8.0,EUR,2025-02-19 Nunner offer OUTBOUND version Fina...,AT
114,NUNNER,OUTBOUND,AT,AT,NaN,5600.0,6300.0,KG,9.0,EUR,2025-02-19 Nunner offer OUTBOUND version Fina...,AT
115,NUNNER,OUTBOUND,AT,AT,NaN,6300.0,7000.0,KG,10.0,EUR,2025-02-19 Nunner offer OUTBOUND version Fina...,AT

Saved: nunner_out_rate_fact_final_v2.csv

Now Austria rows have POSTCODE_BAND filled with values like 10-19, 20-29, etc. (for the columns where those existed).

Now Part 2C — Nunner INBOUND

Inbound workbook often has lanes like “DE-BE” / “DE to BE” / “DE > BE” etc. We’ll reuse the exact same extraction logic.

Parse Nunner INBOUND using the same engine

In [ ]:
nunner_in_path = FILES["nunner_in"]
xls_in = pd.ExcelFile(nunner_in_path)

print("Nunner IN sheets:", len(xls_in.sheet_names))
print("First 30 sheets:")
for sh in xls_in.sheet_names[:30]:
    print("-", sh)

# Parse all non-remarks sheets
def is_remarks_sheet(name):
    return "REMARK" in name.upper()

rate_sheets_in = [sh for sh in xls_in.sheet_names if not is_remarks_sheet(sh)]
parsed_in = []
skipped_in = []

for sh in rate_sheets_in:
    t = extract_nunner_sheet(nunner_in_path, sh)  # reuse function from N8
    if t is None or len(t) == 0:
        skipped_in.append(sh)
    else:
        parsed_in.append(t)

print("Parsed IN sheets:", len(parsed_in))
print("Skipped IN sheets:", len(skipped_in))
print("Some skipped:", skipped_in[:20])

nunner_in_long = pd.concat(parsed_in, ignore_index=True)
print("nunner_in_long:", nunner_in_long.shape)
nunner_in_long.head(10)

Nunner IN sheets: 19
First 30 sheets:
- General Remarks
- Change History
- Fuel Matrix
- AT to BE
- Sotragal
- BE to BE
- BG70 to BE
- Domestic Volume PuursZwijdrecht
- CZ to BE
- DE to BE
- FR to BE
- HU to BE
- NL to BE
- PL to BE
- RO to BE
- IT to BE
- ES to BE
- SK to BE
- UK - NL
Parsed IN sheets: 14
Skipped IN sheets: 4
Some skipped: ['Change History', 'Sotragal', 'Domestic Volume PuursZwijdrecht', 'ES to BE']
nunner_in_long: (7696, 7)

,WEIGHT,RATE_COL,RATE_RAW,RATE,SHEET,__SOURCE_FILE,__SOURCE_SHEET
0,0.0,C0,1.05,1.050,Fuel Matrix,2025-06-26 Nunner offer INBOUND version Final ...,Fuel Matrix
1,1.0,C0,1.1,1.100,Fuel Matrix,2025-06-26 Nunner offer INBOUND version Final ...,Fuel Matrix
2,1.5,C0,1.125,1.125,Fuel Matrix,2025-06-26 Nunner offer INBOUND version Final ...,Fuel Matrix
3,2.0,C0,1.15,1.150,Fuel Matrix,2025-06-26 Nunner offer INBOUND version Final ...,Fuel Matrix
4,2.5,C0,1.175,1.175,Fuel Matrix,2025-06-26 Nunner offer INBOUND version Final ...,Fuel Matrix
5,3.0,C0,1.2,1.200,Fuel Matrix,2025-06-26 Nunner offer INBOUND version Final ...,Fuel Matrix
6,3.5,C0,1.225,1.225,Fuel Matrix,2025-06-26 Nunner offer INBOUND version Final ...,Fuel Matrix
7,4.0,C0,1.25,1.250,Fuel Matrix,2025-06-26 Nunner offer INBOUND version Final ...,Fuel Matrix
8,4.5,C0,1.275,1.275,Fuel Matrix,2025-06-26 Nunner offer INBOUND version Final ...,Fuel Matrix
9,5.0,C0,1.3,1.300,Fuel Matrix,2025-06-26 Nunner offer INBOUND version Final ...,Fuel Matrix

Build inbound fact table + parse origin/destination from sheet name

In [ ]:
df = nunner_in_long.copy()
df["CARRIER"] = "NUNNER"
df["DIRECTION"] = "INBOUND"
df["WEIGHT_UOM"] = "KG"
df["CURRENCY"] = "EUR"

df["WEIGHT"] = pd.to_numeric(df["WEIGHT"], errors="coerce")
df["RATE"] = pd.to_numeric(df["RATE"], errors="coerce")
df = df.dropna(subset=["WEIGHT","RATE"])

# banding per sheet+rate_col
df_banded = df.groupby(["SHEET","RATE_COL"], dropna=False, group_keys=False).apply(bands)

# Parse lane from sheet name: try to extract "XX" and "YY"
def parse_lane(sheet):
    s = sheet.upper().replace(" ", "")
    m = re.search(r"([A-Z]{2}).*?(?:TO|->|–|-|>|_).*?([A-Z]{2})", s)
    if m:
        return m.group(1), m.group(2)
    return (np.nan, np.nan)

lanes = df_banded["SHEET"].apply(parse_lane)
df_banded["ORIGIN_COUNTRY"] = lanes.map(lambda x: x[0])
df_banded["DESTINATION_COUNTRY"] = lanes.map(lambda x: x[1])
df_banded["LANE_LABEL"] = df_banded["SHEET"]

# postcode band mapping same approach if needed:
band_maps_in = {sh: get_col_band_map(nunner_in_path, sh) for sh in df_banded["SHEET"].unique()}
df_banded["POSTCODE_BAND"] = df_banded.apply(lambda r: band_maps_in.get(r["SHEET"], {}).get(r["RATE_COL"], np.nan), axis=1)

nunner_in_fact_final = df_banded[
    ["CARRIER","DIRECTION","ORIGIN_COUNTRY","DESTINATION_COUNTRY","LANE_LABEL","POSTCODE_BAND",
     "WEIGHT_FROM","WEIGHT_TO","WEIGHT_UOM","RATE","CURRENCY","__SOURCE_FILE","__SOURCE_SHEET"]
].copy()

print("✅ Nunner IN final:", nunner_in_fact_final.shape)
display(nunner_in_fact_final.head(5))

nunner_in_fact_final.to_csv("nunner_in_rate_fact_final.csv", index=False)
print("Saved: nunner_in_rate_fact_final.csv")

✅ Nunner IN final: (4545, 13)

,CARRIER,DIRECTION,ORIGIN_COUNTRY,DESTINATION_COUNTRY,LANE_LABEL,POSTCODE_BAND,WEIGHT_FROM,WEIGHT_TO,WEIGHT_UOM,RATE,CURRENCY,__SOURCE_FILE,__SOURCE_SHEET
17,NUNNER,INBOUND,AT,BE,AT to BE,NaN,0.00,279.95,KG,1.0,EUR,2025-06-26 Nunner offer INBOUND version Final ...,AT to BE
18,NUNNER,INBOUND,AT,BE,AT to BE,NaN,279.95,335.93,KG,2.0,EUR,2025-06-26 Nunner offer INBOUND version Final ...,AT to BE
19,NUNNER,INBOUND,AT,BE,AT to BE,NaN,335.93,391.92,KG,3.0,EUR,2025-06-26 Nunner offer INBOUND version Final ...,AT to BE
20,NUNNER,INBOUND,AT,BE,AT to BE,NaN,391.92,447.93,KG,4.0,EUR,2025-06-26 Nunner offer INBOUND version Final ...,AT to BE
21,NUNNER,INBOUND,AT,BE,AT to BE,NaN,447.93,461.91,KG,5.0,EUR,2025-06-26 Nunner offer INBOUND version Final ...,AT to BE

Saved: nunner_in_rate_fact_final.csv

the sample reveals a big unit issue we should fix now before Geodis:

WEIGHT_TO values like 279.95, 335.93, 391.92 kg look plausible…

but RATE values 1.0, 2.0, 3.0… EUR are not plausible as transport costs.

That almost always means the parser accidentally picked the “blok / step / index” column as the rate (your outbound sheets had “Blok” too). For inbound, “RATE_COL” is just C? so it may be melting the wrong numeric column.

Let’s correct it analytically by choosing the best “rate column” per sheet using a simple, defensible heuristic:

Heuristic

A true rate column should have:

many numeric values

median > 5 EUR (or >10) and max reasonably high

not just 1..N integers

We’ll re-extract inbound sheets by detecting:

weight column = numeric column with monotonic-ish increasing breakpoints

rate column = numeric column with realistic magnitudes

Fix Nunner INBOUND: pick the correct RATE column

Re-extract each inbound sheet with “best rate column” logic

In [ ]:
import pandas as pd
import numpy as np
import re
from pathlib import Path

nunner_in_path = FILES["nunner_in"]
xls = pd.ExcelFile(nunner_in_path)

def read_raw(path, sheet):
    return pd.read_excel(path, sheet_name=sheet, header=None)

def numeric_series(s):
    return pd.to_numeric(s.astype(str).str.replace(",", ".", regex=False).str.replace("€","", regex=False),
                         errors="coerce")

def find_best_weight_and_rate_cols(raw, max_rows=120, max_cols=20):
    # evaluate first max_rows rows
    raw2 = raw.iloc[:max_rows, :max_cols].copy()

    col_stats = []
    for c in raw2.columns:
        nums = numeric_series(raw2[c])
        nn = nums.notna().sum()
        if nn < 8:
            continue
        col_stats.append((c, nn, nums))

    if not col_stats:
        return None, None

    # Choose WEIGHT column: numeric column with many values and (often) increasing
    def weight_score(nums):
        v = nums.dropna().values
        if len(v) < 8:
            return -1
        inc_ratio = (np.diff(v) >= 0).mean() if len(v) > 1 else 0
        # weights usually have larger values than 1..N and tend to increase
        return len(v) + 10 * inc_ratio + (np.nanmax(v) / 1000)

    weight_candidates = sorted(col_stats, key=lambda t: weight_score(t[2]), reverse=True)
    weight_col = weight_candidates[0][0]
    w_nums = weight_candidates[0][2]

    # Choose RATE column: numeric column not equal weight_col with realistic magnitude
    def rate_score(nums):
        v = nums.dropna().values
        if len(v) < 8:
            return -1
        med = np.median(v)
        mx = np.max(v)
        # penalize "1..N" integer index columns
        looks_like_index = (np.all(np.isclose(v, np.round(v))) and mx <= 50 and med <= 10)
        score = len(v)
        score += 5 * (med > 10) + 3 * (mx > 50) + 2 * (mx > 200)
        score -= 10 * looks_like_index
        return score

    rate_candidates = []
    for c, nn, nums in col_stats:
        if c == weight_col:
            continue
        rate_candidates.append((c, rate_score(nums), nums))

    rate_candidates = sorted(rate_candidates, key=lambda x: x[1], reverse=True)
    rate_col = rate_candidates[0][0] if rate_candidates and rate_candidates[0][1] > 0 else None

    return weight_col, rate_col

def extract_inbound_sheet_best(path, sheet):
    raw = read_raw(path, sheet)
    wcol, rcol = find_best_weight_and_rate_cols(raw)
    if wcol is None or rcol is None:
        return None

    # find start row where weight becomes numeric for 2 consecutive rows
    w = numeric_series(raw[wcol])
    start_row = None
    for i in range(len(w)-1):
        if pd.notna(w.iloc[i]) and pd.notna(w.iloc[i+1]):
            start_row = i
            break
    if start_row is None:
        return None

    block = raw.iloc[start_row:, [wcol, rcol]].copy()
    block.columns = ["WEIGHT", "RATE"]
    block["WEIGHT"] = numeric_series(block["WEIGHT"])
    block["RATE"] = numeric_series(block["RATE"])
    block = block.dropna(subset=["WEIGHT","RATE"])

    block["SHEET"] = sheet
    block["__SOURCE_FILE"] = Path(path).name
    block["__SOURCE_SHEET"] = sheet
    block["WEIGHT_COL_IDX"] = int(wcol)
    block["RATE_COL_IDX"] = int(rcol)
    return block

# Run extraction
parsed = []
skipped = []

for sh in xls.sheet_names:
    if "REMARK" in sh.upper():
        continue
    t = extract_inbound_sheet_best(nunner_in_path, sh)
    if t is None or len(t) == 0:
        skipped.append(sh)
    else:
        parsed.append(t)

print("Parsed:", len(parsed), "Skipped:", len(skipped))
print("Some skipped:", skipped[:10])

in_long2 = pd.concat(parsed, ignore_index=True)
print("in_long2:", in_long2.shape)
in_long2.head(10)

Parsed: 14 Skipped: 4
Some skipped: ['Change History', 'Sotragal', 'Domestic Volume PuursZwijdrecht', 'ES to BE']
in_long2: (672, 7)

,WEIGHT,RATE,SHEET,__SOURCE_FILE,__SOURCE_SHEET,WEIGHT_COL_IDX,RATE_COL_IDX
0,0.0,1.050,Fuel Matrix,2025-06-26 Nunner offer INBOUND version Final ...,Fuel Matrix,1,0
1,1.0,1.100,Fuel Matrix,2025-06-26 Nunner offer INBOUND version Final ...,Fuel Matrix,1,0
2,1.5,1.125,Fuel Matrix,2025-06-26 Nunner offer INBOUND version Final ...,Fuel Matrix,1,0
3,2.0,1.150,Fuel Matrix,2025-06-26 Nunner offer INBOUND version Final ...,Fuel Matrix,1,0
4,2.5,1.175,Fuel Matrix,2025-06-26 Nunner offer INBOUND version Final ...,Fuel Matrix,1,0
5,3.0,1.200,Fuel Matrix,2025-06-26 Nunner offer INBOUND version Final ...,Fuel Matrix,1,0
6,3.5,1.225,Fuel Matrix,2025-06-26 Nunner offer INBOUND version Final ...,Fuel Matrix,1,0
7,4.0,1.250,Fuel Matrix,2025-06-26 Nunner offer INBOUND version Final ...,Fuel Matrix,1,0
8,4.5,1.275,Fuel Matrix,2025-06-26 Nunner offer INBOUND version Final ...,Fuel Matrix,1,0
9,5.0,1.300,Fuel Matrix,2025-06-26 Nunner offer INBOUND version Final ...,Fuel Matrix,1,0

Banding + lane parsing + final inbound table (v2)

In [ ]:
df = in_long2.copy()
df["CARRIER"] = "NUNNER"
df["DIRECTION"] = "INBOUND"
df["WEIGHT_UOM"] = "KG"
df["CURRENCY"] = "EUR"

# half-open bands per sheet
def bands(g):
    g = g.sort_values("WEIGHT").copy()
    g = g.drop_duplicates(subset=["WEIGHT"])
    g["WEIGHT_FROM"] = g["WEIGHT"].shift(1).fillna(0)
    g["WEIGHT_TO"] = g["WEIGHT"]
    return g[g["WEIGHT_TO"] > g["WEIGHT_FROM"]]

df_b = df.groupby(["SHEET"], dropna=False, group_keys=False).apply(bands)

def parse_lane(sheet):
    s = sheet.upper()
    m = re.search(r"([A-Z]{2}).*?(?:TO|->|–|-|>|_).*?([A-Z]{2})", s.replace(" ", ""))
    if m:
        return m.group(1), m.group(2)
    return (np.nan, np.nan)

lanes = df_b["SHEET"].apply(parse_lane)
df_b["ORIGIN_COUNTRY"] = lanes.map(lambda x: x[0])
df_b["DESTINATION_COUNTRY"] = lanes.map(lambda x: x[1])
df_b["LANE_LABEL"] = df_b["SHEET"]

nunner_in_fact_final_v2 = df_b[
    ["CARRIER","DIRECTION","ORIGIN_COUNTRY","DESTINATION_COUNTRY","LANE_LABEL",
     "WEIGHT_FROM","WEIGHT_TO","WEIGHT_UOM","RATE","CURRENCY",
     "WEIGHT_COL_IDX","RATE_COL_IDX","__SOURCE_FILE","__SOURCE_SHEET"]
].copy()

print("✅ Nunner IN final v2:", nunner_in_fact_final_v2.shape)
display(nunner_in_fact_final_v2.head(5))

nunner_in_fact_final_v2.to_csv("nunner_in_rate_fact_final_v2.csv", index=False)
print("Saved: nunner_in_rate_fact_final_v2.csv")

✅ Nunner IN final v2: (669, 14)

,CARRIER,DIRECTION,ORIGIN_COUNTRY,DESTINATION_COUNTRY,LANE_LABEL,WEIGHT_FROM,WEIGHT_TO,WEIGHT_UOM,RATE,CURRENCY,WEIGHT_COL_IDX,RATE_COL_IDX,__SOURCE_FILE,__SOURCE_SHEET
17,NUNNER,INBOUND,AT,BE,AT to BE,0.0,700.0,KG,279.95,EUR,3,6,2025-06-26 Nunner offer INBOUND version Final ...,AT to BE
18,NUNNER,INBOUND,AT,BE,AT to BE,700.0,875.0,KG,279.95,EUR,3,6,2025-06-26 Nunner offer INBOUND version Final ...,AT to BE
19,NUNNER,INBOUND,AT,BE,AT to BE,875.0,1400.0,KG,335.93,EUR,3,6,2025-06-26 Nunner offer INBOUND version Final ...,AT to BE
20,NUNNER,INBOUND,AT,BE,AT to BE,1400.0,1750.0,KG,349.94,EUR,3,6,2025-06-26 Nunner offer INBOUND version Final ...,AT to BE
21,NUNNER,INBOUND,AT,BE,AT to BE,1750.0,2100.0,KG,391.92,EUR,3,6,2025-06-26 Nunner offer INBOUND version Final ...,AT to BE

Saved: nunner_in_rate_fact_final_v2.csv

#Part 3 — Geodis
Inspect structure

In [ ]:
import pandas as pd

geodis_path = FILES["geodis"]
xls = pd.ExcelFile(geodis_path)

print("Geodis sheets:", len(xls.sheet_names))
for sh in xls.sheet_names:
    print("-", sh)

# preview first real sheet
prev = pd.read_excel(geodis_path, sheet_name=xls.sheet_names[0], header=None, nrows=20)
display(prev)

Geodis sheets: 6
- Tarifs MES
- Tarif express >30Kgs
- Tarifs express <30Kgs
- Tarifs AFF
- Tarifs Eurodirect
- Charges

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GEODIS Distribution & Express,NaN
1,NaN,NaN,NaN,NaN,NaN,messagerieplus- France,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Agence de GEODIS LILLE EUROPE,NaN
2,NaN,NaN,NaN,NaN,NaN,Door to door,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"7, Avenue de la Rotonde",NaN
3,NaN,NaN,NaN,NaN,NaN,from RUMST via Lomme,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56464 LOMME CEDEX,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sales contact,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Phone 0033 3 20 08 42 82,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,Application Date :,NaN,2018-11-01 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Validity date,NaN,2019-04-30 00:00:00,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,Company :,NaN,CUMMINS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Reference:,NaN,NaN,Specific rates
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,Département de destination,NaN,NaN,0 à 9 kgs,10 à 19 kgs,20 à 29 kgs,30 à 39 kgs,40 à 49 kgs,50 à 59kgs,60 à 69 kgs,70 à 79 kgs,80 à 89 kgs,90 à 99 kgs,100 kgs à 2 T,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,Prix au forfait,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Prix aux 100kg,NaN,NaN,NaN
13,NaN,01 AIN,NaN,NaN,17.84,22.59,28.04,30.27,34.6,37.97,40.65,44.01,47.43,49.46,47.16,NaN,NaN,NaN
14,NaN,02 AISNE,NaN,NaN,10.59,12.8,15.32,16.38,18.95,20.83,22.4,24.45,26.34,27.58,26.34,NaN,NaN,NaN
15,NaN,03 ALLIER,NaN,NaN,18.63,23.68,29.51,31.9,36.31,39.87,42.67,46.08,49.78,51.82,49.42,NaN,NaN,NaN
16,NaN,04 ALPES DE HAUTE PROVENCE,NaN,NaN,23.46,30.54,37.82,41.13,46.47,51.28,54.79,59.11,63.84,66.53,63.38,NaN,NaN,NaN
17,NaN,05 HAUTES ALPES,NaN,NaN,23.46,30.54,37.82,41.13,46.47,51.28,54.79,59.11,63.84,66.53,63.38,NaN,NaN,NaN
18,NaN,06 ALPES MARITIME,NaN,NaN,23.46,30.54,37.82,41.13,46.47,51.28,54.79,59.11,63.84,66.53,63.38,NaN,NaN,NaN
19,NaN,07 ARDECHE,NaN,NaN,20.16,25.88,32.21,34.95,39.87,43.77,46.64,50.49,54.52,56.81,54.08,NaN,NaN,NaN

Extract Geodis using the same “best weight / best rate” logic

We reuse the inbound engine

In [ ]:
parsed = []
skipped = []

for sh in xls.sheet_names:
    t = extract_inbound_sheet_best(geodis_path, sh)  # reuse function
    if t is None or len(t) == 0:
        skipped.append(sh)
    else:
        parsed.append(t)

print("Parsed Geodis sheets:", len(parsed))
print("Skipped Geodis sheets:", skipped)

geodis_long = pd.concat(parsed, ignore_index=True)
print("geodis_long:", geodis_long.shape)
geodis_long.head(10)

Parsed Geodis sheets: 4
Skipped Geodis sheets: ['Tarifs express <30Kgs ', 'Charges']
geodis_long: (377, 7)

,WEIGHT,RATE,SHEET,__SOURCE_FILE,__SOURCE_SHEET,WEIGHT_COL_IDX,RATE_COL_IDX
0,49.46,37.97,Tarifs MES,Rates Geodis.xlsx,Tarifs MES,13,9
1,27.58,20.83,Tarifs MES,Rates Geodis.xlsx,Tarifs MES,13,9
2,51.82,39.87,Tarifs MES,Rates Geodis.xlsx,Tarifs MES,13,9
3,66.53,51.28,Tarifs MES,Rates Geodis.xlsx,Tarifs MES,13,9
4,66.53,51.28,Tarifs MES,Rates Geodis.xlsx,Tarifs MES,13,9
5,66.53,51.28,Tarifs MES,Rates Geodis.xlsx,Tarifs MES,13,9
6,56.81,43.77,Tarifs MES,Rates Geodis.xlsx,Tarifs MES,13,9
7,32.46,24.71,Tarifs MES,Rates Geodis.xlsx,Tarifs MES,13,9
8,63.96,49.39,Tarifs MES,Rates Geodis.xlsx,Tarifs MES,13,9
9,42.10,32.22,Tarifs MES,Rates Geodis.xlsx,Tarifs MES,13,9

Banding + final Geodis fact table

In [ ]:
df = geodis_long.copy()
df["CARRIER"] = "GEODIS"
df["DIRECTION"] = "OUTBOUND"
df["WEIGHT_UOM"] = "KG"
df["CURRENCY"] = "EUR"

def bands(g):
    g = g.sort_values("WEIGHT").copy()
    g = g.drop_duplicates(subset=["WEIGHT"])
    g["WEIGHT_FROM"] = g["WEIGHT"].shift(1).fillna(0)
    g["WEIGHT_TO"] = g["WEIGHT"]
    return g[g["WEIGHT_TO"] > g["WEIGHT_FROM"]]

df_b = df.groupby(["SHEET"], dropna=False, group_keys=False).apply(bands)

geodis_fact_final = df_b[
    ["CARRIER","DIRECTION","WEIGHT_FROM","WEIGHT_TO","WEIGHT_UOM",
     "RATE","CURRENCY","WEIGHT_COL_IDX","RATE_COL_IDX",
     "__SOURCE_FILE","__SOURCE_SHEET"]
].copy()

print("✅ Geodis final:", geodis_fact_final.shape)
display(geodis_fact_final.head(15))

geodis_fact_final.to_csv("geodis_rate_fact_final.csv", index=False)
print("Saved: geodis_rate_fact_final.csv")

✅ Geodis final: (107, 11)

,CARRIER,DIRECTION,WEIGHT_FROM,WEIGHT_TO,WEIGHT_UOM,RATE,CURRENCY,WEIGHT_COL_IDX,RATE_COL_IDX,__SOURCE_FILE,__SOURCE_SHEET
95,GEODIS,OUTBOUND,0.00,40.24,KG,25.59,EUR,15,10,Rates Geodis.xlsx,Tarif express >30Kgs
188,GEODIS,OUTBOUND,40.24,69.96,KG,42.12,EUR,15,10,Rates Geodis.xlsx,Tarif express >30Kgs
142,GEODIS,OUTBOUND,69.96,93.06,KG,51.41,EUR,15,10,Rates Geodis.xlsx,Tarif express >30Kgs
176,GEODIS,OUTBOUND,93.06,112.44,KG,59.11,EUR,15,10,Rates Geodis.xlsx,Tarif express >30Kgs
246,GEODIS,OUTBOUND,0.00,289.68,KG,67.32,EUR,19,4,Rates Geodis.xlsx,Tarifs AFF
190,GEODIS,OUTBOUND,289.68,322.32,KG,153.00,EUR,19,4,Rates Geodis.xlsx,Tarifs AFF
267,GEODIS,OUTBOUND,322.32,327.42,KG,168.30,EUR,19,4,Rates Geodis.xlsx,Tarifs AFF
196,GEODIS,OUTBOUND,327.42,358.02,KG,153.00,EUR,19,4,Rates Geodis.xlsx,Tarifs AFF
247,GEODIS,OUTBOUND,358.02,365.16,KG,189.72,EUR,19,4,Rates Geodis.xlsx,Tarifs AFF
238,GEODIS,OUTBOUND,365.16,375.36,KG,146.88,EUR,19,4,Rates Geodis.xlsx,Tarifs AFF
281,GEODIS,OUTBOUND,375.36,392.70,KG,193.80,EUR,19,4,Rates Geodis.xlsx,Tarifs AFF
263,GEODIS,OUTBOUND,392.70,397.80,KG,193.80,EUR,19,4,Rates Geodis.xlsx,Tarifs AFF
278,GEODIS,OUTBOUND,397.80,408.00,KG,193.80,EUR,19,4,Rates Geodis.xlsx,Tarifs AFF
214,GEODIS,OUTBOUND,408.00,457.98,KG,224.40,EUR,19,4,Rates Geodis.xlsx,Tarifs AFF
202,GEODIS,OUTBOUND,457.98,483.48,KG,224.40,EUR,19,4,Rates Geodis.xlsx,Tarifs AFF

Saved: geodis_rate_fact_final.csv

How fragmented are current weight breaks?

Are there too many / too irregular weight breaks?

Metrics

Number of weight bands per lane

Average band width (kg)

Coefficient of variation of band widths

Smallest / largest band

Why it matters

Highly fragmented or uneven bands usually indicate:

legacy setup

non-optimized cost structure

opportunity for consolidation

In [ ]:
# === Load finalized rate facts ===
nunner_out = pd.read_csv("nunner_out_rate_fact_final_v2.csv")
nunner_in  = pd.read_csv("nunner_in_rate_fact_final_v2.csv")
geodis     = pd.read_csv("geodis_rate_fact_final.csv")

C:\Users\atb6113\AppData\Local\Temp\ipykernel_10960\1894018725.py:2: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  nunner_out = pd.read_csv("nunner_out_rate_fact_final_v2.csv")

In [ ]:
import pandas as pd
import numpy as np

df = df = nunner_out.copy()

print(df.shape)
df.head()

(115010, 12)

,CARRIER,DIRECTION,DESTINATION_COUNTRY,LANE_LABEL,POSTCODE_BAND,WEIGHT_FROM,WEIGHT_TO,WEIGHT_UOM,RATE,CURRENCY,__SOURCE_FILE,__SOURCE_SHEET
0,NUNNER,OUTBOUND,AL,AL,NaN,0.0,64.0,KG,610.23,EUR,2025-02-19 Nunner offer OUTBOUND version Fina...,AL
1,NUNNER,OUTBOUND,AL,AL,NaN,64.0,100.0,KG,610.23,EUR,2025-02-19 Nunner offer OUTBOUND version Fina...,AL
2,NUNNER,OUTBOUND,AL,AL,NaN,100.0,200.0,KG,610.23,EUR,2025-02-19 Nunner offer OUTBOUND version Fina...,AL
3,NUNNER,OUTBOUND,AL,AL,NaN,200.0,300.0,KG,610.23,EUR,2025-02-19 Nunner offer OUTBOUND version Fina...,AL
4,NUNNER,OUTBOUND,AL,AL,NaN,300.0,400.0,KG,610.23,EUR,2025-02-19 Nunner offer OUTBOUND version Fina...,AL

In [ ]:
df["BAND_WIDTH"] = df["WEIGHT_TO"] - df["WEIGHT_FROM"]

stats = (
    df.groupby(["CARRIER","LANE_LABEL"])
      .agg(
          n_bands=("BAND_WIDTH","count"),
          avg_width=("BAND_WIDTH","mean"),
          min_width=("BAND_WIDTH","min"),
          max_width=("BAND_WIDTH","max"),
          cv_width=("BAND_WIDTH", lambda x: x.std() / x.mean() if x.mean() > 0 else np.nan)
      )
      .reset_index()
)

stats.sort_values("n_bands", ascending=False).head(10)

   CARRIER LANE_LABEL  n_bands  avg_width  min_width  max_width  cv_width
5   NUNNER         CH     9801  13.553802       5.22     225.52  2.171411
22  NUNNER         LT     9000  19.203444       4.07      53.47  0.628781
29  NUNNER         PL     8811  13.673596       2.95      37.58  0.582659
14  NUNNER         FR     8460  16.527222       1.09      49.14  0.698111
19  NUNNER         IT     8370  22.671000       5.00      63.65  0.592757
4   NUNNER         BG     7920  32.226364       3.95      99.42  0.705388
18  NUNNER         HU     7392  13.418182       2.77      40.48  0.649659
8   NUNNER         DE     6460  17.044559       3.66      73.94  0.942089
7   NUNNER         CZ     5340  10.637303       2.28      30.33  0.603838
16  NUNNER         GR     5040  40.282667       5.28     124.23  0.690739

#Invoice ingestion & validation.

Load the file and inspect sheets

In [ ]:
import sys, subprocess
try:
    import pyxlsb  # noqa
except ImportError:
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'pyxlsb'])

from pathlib import Path

file_path = str((DATA_DIR / "Freight Spend CMI Belgium_Jan'25_Nov'25.xlsb").resolve())

# List available sheets
xls = pd.ExcelFile(file_path, engine="pyxlsb")
xls.sheet_names

['FreightDataReportForAtmus']

Identify the “detail” invoice sheet

In [ ]:
df_raw = pd.read_excel(
    file_path,
    sheet_name=xls.sheet_names[0],  # change if needed
    engine="pyxlsb"
)

df_raw.shape

(45946, 59)

In [ ]:

df_raw.head(20)

,7ueuur33333e232333r22323dwq1diiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii 8888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888 8 v5ftg5v44e5tddwxt545iiiiiiiii44444444444tr4t544a35t554553erwd6i5i ttri23sx4ie 4t4t43ugigggggggfffffffffffffffffbh cqqfivfgfvyiftvqw,Customer Reference No,Account Code,Shipment Id,Carrier Name,Carrier Code,Invoice No,Inv Net Amt,Inv Gross Amt,Origin Name,Origin ID,OriginCity,Origin Zip Code,Origin Country,Stoppage 1 City,Stoppage 1 Country,Stoppage 1 Zip,Stoppage 2 City,Stoppage 2 Country,Stoppage 2 Zip,Destination Name,Destination ID,Destination City,Destination Zip Code,Destination Country,Actual Weight,Volume,Chargeable Weight,Loading Meter,Equipment Type,Net Amount,Amount in USD,Gross Amount,Header Currency,Currency,Exchange Rate,VAT Amt,Accessorial Code,Accessorial Name,Pickup Date,Delivery Date,Unit Qty,Pallet Type,Shipment Type,Transportation Mode,Carrier Reference No,Pay Status Group Code,Pay Status Category Code,Corporate Location Name,Product Group Desc,Inbound Outbound Code Desc,Kilometers,Arrival Date,Invoice Date,Remitted Date,Service Level Type,Shipment Net Amount,Batch,Month
0,Atmus,4838131,'AE9ADRADR90004911023000000000000,2416814,Hamann International Logistics NV,HAMABEWETT,1466127,644.46,779.80,UFI FILTERS SPA,,Nogarole Rocca,37060,IT,NaN,NaN,NaN,NaN,NaN,NaN,CMI Filtration,CMIFBERUMS,Rumst,2840,BE,360.0,6.48,360.0,2.0,NaN,502.30,521.220297,607.79,EUR,EUR,NaN,105.49,LHL,Linehaul,45601,45601,5,Per Pallet,B,TR,NaN,Paid,Paid in Full,CMI Filtration Belgium,NaN,Inbound,0.0,45637,45623,45694,NaN,644.46,8,2
1,Atmus,4838131,'AE9ADRADR90004911023000000000000,2416814,Hamann International Logistics NV,HAMABEWETT,1466127,644.46,779.80,UFI FILTERS SPA,,Nogarole Rocca,37060,IT,NaN,NaN,NaN,NaN,NaN,NaN,CMI Filtration,CMIFBERUMS,Rumst,2840,BE,360.0,6.48,360.0,2.0,NaN,20.00,20.753346,24.20,EUR,EUR,NaN,4.20,CUS,Customs Fee,45601,45601,5,Per Pallet,B,TR,NaN,Paid,Paid in Full,CMI Filtration Belgium,NaN,Inbound,0.0,45637,45623,45694,NaN,644.46,8,2
2,Atmus,4838131,'AE9ADRADR90004911023000000000000,2416814,Hamann International Logistics NV,HAMABEWETT,1466127,644.46,779.80,UFI FILTERS SPA,,Nogarole Rocca,37060,IT,NaN,NaN,NaN,NaN,NaN,NaN,CMI Filtration,CMIFBERUMS,Rumst,2840,BE,360.0,6.48,360.0,2.0,NaN,10.95,11.362457,13.25,EUR,EUR,NaN,2.30,MTB,MAUT BELGIUM,45601,45601,5,Per Pallet,B,TR,NaN,Paid,Paid in Full,CMI Filtration Belgium,NaN,Inbound,0.0,45637,45623,45694,NaN,644.46,8,2
3,Atmus,4838131,'AE9ADRADR90004911023000000000000,2416814,Hamann International Logistics NV,HAMABEWETT,1466127,644.46,779.80,UFI FILTERS SPA,,Nogarole Rocca,37060,IT,NaN,NaN,NaN,NaN,NaN,NaN,CMI Filtration,CMIFBERUMS,Rumst,2840,BE,360.0,6.48,360.0,2.0,NaN,10.70,11.103040,12.95,EUR,EUR,NaN,2.25,MTG,Maut Germany,45601,45601,5,Per Pallet,B,TR,NaN,Paid,Paid in Full,CMI Filtration Belgium,NaN,Inbound,0.0,45637,45623,45694,NaN,644.46,8,2
4,Atmus,4838131,'AE9ADRADR90004911023000000000000,2416814,Hamann International Logistics NV,HAMABEWETT,1466127,644.46,779.80,UFI FILTERS SPA,,Nogarole Rocca,37060,IT,NaN,NaN,NaN,NaN,NaN,NaN,CMI Filtration,CMIFBERUMS,Rumst,2840,BE,360.0,6.48,360.0,2.0,NaN,55.00,57.071703,66.55,EUR,EUR,NaN,11.55,DLC,Delivery Charges,45601,45601,5,Per Pallet,B,TR,NaN,Paid,Paid in Full,CMI Filtration Belgium,NaN,Inbound,0.0,45637,45623,45694,NaN,644.46,8,2
5,Atmus,4838131,'AE9ADRADR90004911023000000000000,2416814,Hamann International Logistics NV,HAMABEWETT,1466127,644.46,779.80,UFI FILTERS SPA,,Nogarole Rocca,37060,IT,NaN,NaN,NaN,NaN,NaN,NaN,CMI Filtration,CMIFBERUMS,Rumst,2840,BE,360.0,6.48,360.0,2.0,NaN,41.44,43.000934,50.14,EUR,EUR,NaN,8.70,FSR,Fuel Surcharge,45601,45601,5,Per Pallet,B,TR,NaN,Paid,Paid in Full,CMI Filtration Belgium,NaN,Inbound,0.0,45637,45623,45694,NaN,644.46,8,2
6,Atmus,4838131,'AE9ADRADR90004911023000000000000,2416814,Hamann International Logistics NV,HAMABEWETT,1466127,644.46,779.80,UFI FILTERS SPA,,Nogarole Rocca,37060,IT,NaN,NaN,NaN,NaN,NaN,NaN,CMI Filtration,CMIFBERUMS,Rumst,2840,BE,360.0,6.48,360.0,2.0,NaN,4.07,4.223306,4.92,EUR,EUR,NaN,0.85,ADM,Admin Costs,45601,45601,5,Per Pallet,B,TR,NaN,Paid,Paid in Full,CMI Filtration Belgium,NaN,Inbound,0.0,45637,45623,45694,NaN,644.46,8,2
7,Atmus,4841771,'AE9ADRADR90004911023000000000000,2416829,Hamann International Logistics NV,HAMABEWETT,1466128,173.00,209.33,UFI FILTERS SPA,,Nogarole Rocca,37060,IT,NaN,NaN,NaN,NaN,NaN,NaN,CMI Filtration,CMIFBERUMS,Rumst,2840,BE,29.0,0.17,29.0,0.1,NaN,83.45,86.593338,100.99,EUR,EUR,NaN,17.54,LHL,Linehaul,45604,45604,1,Per Pallet,B,TR,NaN,Paid,Paid in Full,CMI Filtration Belgium,NaN,Inbound,0.0,45637,45623,45694,NaN,173.00,8,2
8,Atmus,4841771,'AE9ADRADR90004911023000000000000,2416829,Hamann International Logistics NV,HAMABEWETT,1466128,173.00,209.33,UFI FILTERS SPA,,Nogarole Rocca,37060,IT,NaN,NaN,NaN,NaN,NaN,NaN,CMI Filtration,CMIFBERUMS,Rumst,2840,BE,29.0,0.17,29.0,0.1,NaN,20.00,20.753346,24.20,EUR,EUR,NaN,4.20,CUS,Customs Fee,45604,45604,1,Per Pallet,B,TR,NaN,Paid,Paid in Full,CMI Filtration Belgium,NaN,Inbound,0.0,45637,45623,45694,NaN,173.00,8,2
9,Atmus,4841771,'AE9ADRADR90004911023000000000000,2416829,Hamann International Logistics NV,HAMABEWETT,1466128,173.00,209.33,UFI FILTERS SPA,,Nogarole Rocca,37060,IT,NaN,NaN,NaN,NaN,NaN,NaN,CMI Filtration,CMIFBERUMS,Rumst,2840,BE,29.0,0.17,29.0,0.1,NaN,1.82,1.888555,2.20,EUR,EUR,NaN,0.38,MTB,MAUT BELGIUM,45604,45604,1,Per Pallet,B,TR,NaN,Paid,Paid in Full,CMI Filtration Belgium,NaN,Inbound,0.0,45637,45623,45694,NaN,173.00,8,2
10,Atmus,4841771,'AE9ADRADR90004911023000000000000,2416829,Hamann International Logistics NV,HAMABEWETT,1466128,173.00,209.33,UFI FILTERS SPA,,Nogarole Rocca,37060,IT,NaN,NaN,NaN,NaN,NaN,NaN,CMI Filtration,CMIFBERUMS,Rumst,2840,BE,29.0,0.17,29.0,0.1,NaN,1.78,1.847048,2.15,EUR,EUR,NaN,0.37,MTG,Maut Germany,45604,45604,1,Per Pallet,B,TR,NaN,Paid,Paid in Full,CMI Filtration Belgium,NaN,Inbound,0.0,45637,45623,45694,NaN,173.00,8,2
11,Atmus,4841771,'AE9ADRADR90004911023000000000000,2416829,Hamann International Logistics NV,HAMABEWETT,1466128,173.00,209.33,UFI FILTERS SPA,,Nogarole Rocca,37060,IT,NaN,NaN,NaN,NaN,NaN,NaN,CMI Filtration,CMIFBERUMS,Rumst,2840,BE,29.0,0.17,29.0,0.1,NaN,55.00,57.071703,66.55,EUR,EUR,NaN,11.55,DLC,Delivery Charges,45604,45604,1,Per Pallet,B,TR,NaN,Paid,Paid in Full,CMI Filtration Belgium,NaN,Inbound,0.0,45637,45623,45694,NaN,173.00,8,2
12,Atmus,4841771,'AE9ADRADR90004911023000000000000,2416829,Hamann International Logistics NV,HAMABEWETT,1466128,173.00,209.33,UFI FILTERS SPA,,Nogarole Rocca,37060,IT,NaN,NaN,NaN,NaN,NaN,NaN,CMI Filtration,CMIFBERUMS,Rumst,2840,BE,29.0,0.17,29.0,0.1,NaN,6.88,7.139151,8.32,EUR,EUR,NaN,1.44,FSR,Fuel Surcharge,45604,45604,1,Per Pallet,B,TR,NaN,Paid,Paid in Full,CMI Filtration Belgium,NaN,Inbound,0.0,45637,45623,45694,NaN,173.00,8,2
13,Atmus,4841771,'AE9ADRADR90004911023000000000000,2416829,Hamann International Logistics NV,HAMABEWETT,1466128,173.00,209.33,UFI FILTERS SPA,,Nogarole Rocca,37060,IT,NaN,NaN,NaN,NaN,NaN,NaN,CMI Filtration,CMIFBERUMS,Rumst,2840,BE,29.0,0.17,29.0,0.1,NaN,4.07,4.223306,4.92,EUR,EUR,NaN,0.85,ADM,Admin Costs,45604,45604,1,Per Pallet,B,TR,NaN,Paid,Paid in Full,CMI Filtration Belgium,NaN,Inbound,0.0,45637,45623,45694,NaN,173.00,8,2
14,Atmus,4845489,'AE9ADRADR90004911023000000000000,2416836,Hamann International Logistics NV,HAMABEWETT,1466129,509.03,615.93,UFI FILTERS SPA,,Nogarole Rocca,37060,IT,NaN,NaN,NaN,NaN,NaN,NaN,CMI Filtration,CMIFBERUMS,Rumst,2840,BE,516.0,2.11,516.0,0.8,NaN,381.98,396.368164,462.20,EUR,EUR,NaN,80.22,LHL,Linehaul,45608,45608,2,Per Pallet,B,TR,NaN,Paid,Paid in Full,CMI Filtration Belgium,NaN,Inbound,0.0,45637,45623,45694,NaN,509.03,8,2
15,Atmus,4845489,'AE9ADRADR90004911023000000000000,2416836,Hamann International Logistics NV,HAMABEWETT,1466129,509.03,615.93,UFI FILTERS SPA,,Nogarole Rocca,37060,IT,NaN,NaN,NaN,NaN,NaN,NaN,CMI Filtration,CMIFBERUMS,Rumst,2840,BE,516.0,2.11,516.0,0.8,NaN,20.00,20.753346,24.20,EUR,EUR,NaN,4.20,CUS,Customs Fee,45608,45608,2,Per Pallet,B,TR,NaN,Paid,Paid in Full,CMI Filtration Belgium,NaN,Inbound,0.0,45637,45623,45694,NaN,509.03,8,2
16,Atmus,4845489,'AE9ADRADR90004911023000000000000,2416836,Hamann International Logistics NV,HAMABEWETT,1466129,509.03,615.93,UFI FILTERS SPA,,Nogarole Rocca,37060,IT,NaN,NaN,NaN,NaN,NaN,NaN,CMI Filtration,CMIFBERUMS,Rumst,2840,BE,516.0,2.11,516.0,0.8,NaN,8.33,8.643769,10.08,EUR,EUR,NaN,1.75,MTB,MAUT BELGIUM,45608,45608,2,Per Pallet,B,TR,NaN,Paid,Paid in Full,CMI Filtration Belgium,NaN,Inbound,0.0,45637,45623,45694,NaN,509.03,8,2
17,Atmus,4845489,'AE9ADRADR90004911023000000000000,2416836,Hamann International Logistics NV,HAMABEWETT,1466129,509.03,615.93,UFI FILTERS SPA,,Nogarole Rocca,37060,IT,NaN,NaN,NaN,NaN,NaN,NaN,CMI Filtration,CMIFBERUMS,Rumst,2840,BE,516.0,2.11,516.0,0.8,NaN,8.14,8.446612,9.85,EUR,EUR,NaN,1.71,MTG,Maut Germany,45608,45608,2,Per Pallet,B,TR,NaN,Paid,Paid in Full,CMI Filtration Belgium,NaN,Inbound,0.0,45637,45623,45694,NaN,509.03,8,2
18,Atmus,4845489,'AE9ADRADR90004911023000000000000,2416836,Hamann International Logistics NV,HAMABEWETT,1466129,509.03,615.93,UFI FILTERS SPA,,Nogarole Rocca,37060,IT,NaN,NaN,NaN,NaN,NaN,NaN,CMI Filtration,CMIFBERUMS,Rumst,2840,BE,516.0,2.11,516.0,0.8,NaN,55.00,57.071703,66.55,EUR,EUR,NaN,11.55,DLC,Delivery Charges,45608,45608,2,Per Pallet,B,TR,NaN,Paid,Paid in Full,CMI Filtration Belgium,NaN,Inbound,0.0,45637,45623,45694,NaN,509.03,8,2
19,Atmus,4845489,'AE9ADRADR90004911023000000000000,2416836,Hamann International Logistics NV,HAMABEWETT,1466129,509.03,615.93,UFI FILTERS SPA,,Nogarole Rocca,37060,IT,NaN,NaN,NaN,NaN,NaN,NaN,CMI Filtration,CMIFBERUMS,Rumst,2840,BE,516.0,2.11,516.0,0.8,NaN,31.51,32.696897,38.13,EUR,EUR,NaN,6.62,FSR,Fuel Surcharge,45608,45608,2,Per Pallet,B,TR,NaN,Paid,Paid in Full,CMI Filtration Belgium,NaN,Inbound,0.0,45637,45623,45694,NaN,509.03,8,2

In [ ]:
df_raw.columns

Index(['7ueuur33333e232333r22323dwq1diiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii  8888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888888 8 v5ftg5v44e5tddwxt545iiiiiiiii44444444444tr4t544a35t554553erwd6i5i ttri23sx4ie 4t4t43ugigggggggfffffffffffffffffbh cqqfivfgfvyiftvqw',
       'Customer Reference No', 'Account Code', 'Shipment Id', 'Carrier Name',
       'Carrier Code', 'Invoice No', 'Inv Net Amt', 'Inv Gross Amt',
       'Origin Name', 'Origin ID', 'OriginCity', 'Origin Zip Code',
       'Origin Country', 'Stoppage 1 City', 'Stoppage 1 Country',
       'Stoppage 1 Zip', 'Stoppage 2 City', 'Stoppage 2 Country',
       'Stoppage 2 Zip', 'Destination Name', 'Destination ID',
       'Destination City', 'Destination Zip Code', 'Destination Country',
       'Actual Weight', 'Volume', 'Chargeable Weight', 'Loading Meter',
       'Equipment Type', 'Net Amount', 'Amount in  USD', 'Gross Amount',
       'Header Currency', 'Currency', 'Exchange Rate', 'VAT Amt',
       'Accessorial Code', 'Accessorial Name', 'Pickup Date', 'Delivery Date',
       'Unit Qty', 'Pallet Type', 'Shipment Type', 'Transportation Mode',
       'Carrier Reference No', ' Pay Status Group Code',
       'Pay Status Category Code', 'Corporate Location Name',
       'Product Group Desc', 'Inbound Outbound Code Desc', 'Kilometers',
       'Arrival Date', 'Invoice Date', 'Remitted Date', 'Service Level Type',
       'Shipment Net Amount', 'Batch', 'Month'],
      dtype='object')

From the output above we conclude:
The file is NOT one row per shipment.
It is one row per invoice charge line.

We can see this clearly because for the same:

*   Shipment Id
*   Invoice No

you have multiple rows with different:

*   Accessorial Code (LHL, FSR, CUS, MTB, MTG, ADM, DLC, …)
*   Net Amount

We will work at two levels:

* Level A — Charge-line level (raw)

    Used for:

    surcharge analysis

    fuel share analysis

    accessorial impact

* Level B — Shipment level (aggregated)

    Used for:

    cost reconstruction

    rate-card comparison

    weight-break optimization

In [ ]:
### Clean structure & drop garbage column

df = df_raw.copy()

# Drop corrupted first column
df = df.iloc[:, 1:]

# Standardize column names (strip spaces)
df.columns = df.columns.str.strip()

df.shape

(45946, 58)

##Verify shipment-level aggregation logic

In [ ]:
### Aggregate to shipment level

shipment_cols = [
    "Shipment Id",
    "Carrier Name",
    "Carrier Code",
    "Invoice No",
    "Origin Country",
    "Destination Country",
    "Service Level Type",
    "Inbound Outbound Code Desc",
    "Transportation Mode",
    "Actual Weight",
    "Chargeable Weight",
    "Volume",
    "Loading Meter",
    "Pickup Date",
    "Delivery Date",
    "Invoice Date",
    "Currency"
]

shipment_fact = (
    df
    .groupby(shipment_cols, dropna=False)
    .agg(
        invoiced_net_amount=("Net Amount", "sum"),
        invoiced_gross_amount=("Gross Amount", "sum"),
        fuel_surcharge=("Net Amount", lambda x: x[df.loc[x.index, "Accessorial Code"] == "FSR"].sum()),
        linehaul_amount=("Net Amount", lambda x: x[df.loc[x.index, "Accessorial Code"] == "LHL"].sum()),
        accessorial_amount=("Net Amount", lambda x: x[df.loc[x.index, "Accessorial Code"].notna()].sum())
    )
    .reset_index()
)

shipment_fact.shape

(22727, 22)

The step above is very important as it gives us:

one row per shipment

total invoiced cost

cost breakdown (linehaul vs fuel vs accessorials)

In [ ]:
# ==============================
# DHL INTEGRATION — STEP X
# ==============================

# Load DHL file
dhl_file = DATA_DIR / "DHL MasterData2025.xlsx"

dhl_raw = pd.read_excel(dhl_file)
dhl_raw.columns = [str(c).strip() for c in dhl_raw.columns]

print("DHL raw shape:", dhl_raw.shape)
dhl_raw.head()

DHL raw shape: (78531, 22)

,Invoice No,Invoice Date,Company Name,Account Number,Line Number,Item ID,DHL Product Description,PAL/COL,Amount,Weight Charge,Discount Amount,Discount Code,Tax Amount,Tax Code,AWB Number,Weight,Shipper Reference,Shipment Date,Origin Code,Destination Code,Shipper Details,Receiver Details
0,BRUR005574697,2025-01-06,BV CMI FILTRATION BELGIUM,276860414.0,1,NaN,EXPRESS WORLDWIDE eu,1.0,307.93,NaN,NaN,NaN,64.67,A,9450038651,209.5,18300814,2024-12-09,BRUSSELS,LIL. LILLE,FIEGE NV - PLATFORM PUURS;BRABANTSTRAAT 4;PUUR...,APROLIS PIECES DE RECHANGES;207 IMPASSE NIKOLA...
1,BRUR005574697,2025-01-06,BV CMI FILTRATION BELGIUM,276860414.0,2,NaN,ADDRESS CORRECTION,1.0,11.00,NaN,NaN,NaN,2.31,A,9450038651,0.0,18300814,2024-12-09,BRUSSELS,LIL. LILLE,FIEGE NV - PLATFORM PUURS;BRABANTSTRAAT 4;PUUR...,APROLIS PIECES DE RECHANGES;207 IMPASSE NIKOLA...
2,BRUR005574697,2025-01-06,BV CMI FILTRATION BELGIUM,276860414.0,3,NaN,NON STACKABLE PALLET,1.0,137.50,NaN,NaN,NaN,28.88,A,9450038651,0.0,18300814,2024-12-09,BRUSSELS,LIL. LILLE,FIEGE NV - PLATFORM PUURS;BRABANTSTRAAT 4;PUUR...,APROLIS PIECES DE RECHANGES;207 IMPASSE NIKOLA...
3,BRUR005574697,2025-01-06,BV CMI FILTRATION BELGIUM,276860414.0,4,NaN,OVERWEIGHT PIECE,1.0,47.50,NaN,NaN,NaN,9.98,A,9450038651,0.0,18300814,2024-12-09,BRUSSELS,LIL. LILLE,FIEGE NV - PLATFORM PUURS;BRABANTSTRAAT 4;PUUR...,APROLIS PIECES DE RECHANGES;207 IMPASSE NIKOLA...
4,BRUR005574697,2025-01-06,BV CMI FILTRATION BELGIUM,276860414.0,5,NaN,FUEL SURCHARGE,1.0,136.17,NaN,NaN,NaN,28.60,A,9450038651,0.0,18300814,2024-12-09,BRUSSELS,LIL. LILLE,FIEGE NV - PLATFORM PUURS;BRABANTSTRAAT 4;PUUR...,APROLIS PIECES DE RECHANGES;207 IMPASSE NIKOLA...

Now we run a sanity check:

In [ ]:
# Check 1 — weights consistency
shipment_fact[["Actual Weight","Chargeable Weight"]].describe()

       Actual Weight  Chargeable Weight
count   2.272700e+04       22727.000000
mean    2.395771e+03        2029.939863
std     1.224831e+05        5200.411777
min     0.000000e+00           0.000000
25%     2.665000e+00           3.040000
50%     6.305000e+01          79.320000
75%     6.640500e+02        1750.000000
max     1.845356e+07      292633.000000

In [ ]:

#Check 2 — inbound/outbound split
shipment_fact["Inbound Outbound Code Desc"].value_counts()

Inbound Outbound Code Desc
Outbound    17628
Inbound      5099
Name: count, dtype: int64

In [ ]:
#Check 3 — carrier coverage
shipment_fact["Carrier Name"].value_counts()

Carrier Name
GEODIS CALBERSON LILLE EUROPE                 11307
Nunner Logistics B.V.                          5752
Crane Worldwide Logistics B.V. - Rotterdam     4591
Transports Le Torch                             325
DHL International N.V../S.A..                   215
Crane Worldwide Logistics Belgium BVBA          163
Hamann International Logistics NV               157
EXPEDITORS N.V.                                  90
TNT Express (Belgium) BVBA/SPRL                  89
FedEx Express Belgium International BVBA         25
DSV Air & Sea                                    10
CH Robinson Europe BV                             1
Nippon Express (Belgum) NV                        1
FOX Global Logistics B.V                          1
Name: count, dtype: int64

* Very important insight

      From the sample rows, we can already see:

      Chargeable Weight = Actual Weight (in many cases)

      Fuel surcharge (FSR) is billed separately

      Linehaul (LHL) is the dominant cost driver

      Same shipment has:

      customs

      tolls

      admin

      delivery charges

This means:

Rate cards should be compared ONLY against the linehaul component, not total invoice cost.

We now explicitly restrict the dataset to the carriers relevant for this project:

* Nunner
* DHL
* Geodis

In [ ]:
focus_carriers = ["NUNNER", "DHL", "GEODIS"]

shipment_fact_focused = shipment_fact[
    shipment_fact["Carrier Name"]
        .str.upper()
        .str.contains("|".join(focus_carriers), na=False)
].copy()

shipment_fact_focused.shape

(17274, 22)

In [ ]:
# Sanity check
shipment_fact_focused["Carrier Name"].value_counts()

Carrier Name
GEODIS CALBERSON LILLE EUROPE    11307
Nunner Logistics B.V.             5752
DHL International N.V../S.A..      215
Name: count, dtype: int64

Pivot from “shipment” to “linehaul shipment”

Now we apply the key insight you identified:

Rate cards price linehaul only, not total invoice cost.

So we extract linehaul-only invoice rows and aggregate them.

In [ ]:
linehaul_df = df[df["Accessorial Code"] == "LHL"].copy()

linehaul_df.columns = linehaul_df.columns.str.strip()

linehaul_shipments = (
    linehaul_df
    .groupby(
        [
            "Shipment Id",
            "Carrier Name",
            "Carrier Code",
            "Invoice No",
            "Origin Country",
            "Destination Country",
            "Service Level Type",
            "Inbound Outbound Code Desc",
            "Transportation Mode",
            "Actual Weight",
            "Chargeable Weight",
            "Volume",
            "Loading Meter",
            "Pickup Date",
            "Delivery Date",
            "Invoice Date",
            "Currency"
        ],
        dropna=False
    )
    .agg(
        invoiced_linehaul_amount=("Net Amount", "sum")
    )
    .reset_index()
)

linehaul_shipments.shape

(18584, 18)

In [ ]:
#Sanity check
linehaul_shipments.head()

,Shipment Id,Carrier Name,Carrier Code,Invoice No,Origin Country,Destination Country,Service Level Type,Inbound Outbound Code Desc,Transportation Mode,Actual Weight,Chargeable Weight,Volume,Loading Meter,Pickup Date,Delivery Date,Invoice Date,Currency,invoiced_linehaul_amount
0,2405596,GEODIS CALBERSON LILLE EUROPE,GEODFRLOMM,2405912725,FR,FR,AFF,Outbound,LTL,963.0,963.0,0.0,0.6,45600,45600,45606,EUR,87.82
1,2405602,GEODIS CALBERSON LILLE EUROPE,GEODFRLOMM,2405912725,FR,FR,AFF,Outbound,LTL,60.0,60.0,0.0,0.4,45600,45600,45606,EUR,106.74
2,2405605,GEODIS CALBERSON LILLE EUROPE,GEODFRLOMM,2405912725,FR,FR,AFF,Outbound,LTL,295.0,295.0,0.0,0.8,45600,45600,45606,EUR,243.12
3,2405609,GEODIS CALBERSON LILLE EUROPE,GEODFRLOMM,2405912725,FR,FR,AFF,Outbound,LTL,61.0,61.0,0.0,0.4,45600,45600,45606,EUR,106.74
4,2405612,GEODIS CALBERSON LILLE EUROPE,GEODFRLOMM,2405912725,FR,FR,AFF,Outbound,LTL,1485.0,1485.0,0.0,3.3,45600,45600,45606,EUR,143.78

Re-apply carrier scope at linehaul level

This ensures absolute consistency.

In [ ]:
linehaul_shipments_focused = linehaul_shipments[
    linehaul_shipments["Carrier Name"]
        .str.upper()
        .str.contains("|".join(focus_carriers), na=False)
].copy()

linehaul_shipments_focused.shape

(16687, 18)

In [ ]:
#Final carrier check
linehaul_shipments_focused["Carrier Name"].value_counts()

Carrier Name
GEODIS CALBERSON LILLE EUROPE    11168
Nunner Logistics B.V.             5519
Name: count, dtype: int64

### Why DHL is not present in the linehaul reconciliation (important)

This project focuses on **Nunner, Geodis, and DHL**. However, the **rate-card reconciliation** step uses only the **Linehaul (Accessorial Code = `LHL`)** component, because fuel and other accessorials are billed separately and are not part of base rate cards.

In the 2025 invoice extract, **DHL shipments do not appear with `LHL` linehaul lines** (they are typically parcel-priced or use different coding). Therefore DHL is:

- **Included in descriptive spend / volume statistics**,
- **Excluded from the linehaul rate-card matching**, because we cannot map DHL costs to the road LTL rate cards in a consistent way with the current extract.

Why DHL is not present in the linehaul dataset

The optimization and rate-card comparison require an isolated linehaul amount per shipment.

Nunner and Geodis invoices contain an explicit linehaul accessorial (LHL) that can be aggregated per shipment.

DHL invoices do not consistently expose a distinct linehaul component using the available accessorial codes; costs are often bundled or classified differently.

Therefore, DHL is kept for descriptive benchmarking, but excluded from linehaul-based rate-card reconstruction and optimization to ensure conceptual comparability and avoid incorrect matching.

In [ ]:
lh_base = linehaul_shipments_focused.copy()

From now on:

* lh_base = empirical truth at linehaul level

* all transformations create new objects

To avoid project corruption.

In [ ]:
# Standardize carrier names

# We need canonical carrier labels without changing rows.

lh = lh_base.copy()

lh["CARRIER"] = lh["Carrier Name"].str.upper()

lh.loc[lh["CARRIER"].str.contains("NUNNER"), "CARRIER"] = "NUNNER"
lh.loc[lh["CARRIER"].str.contains("GEODIS"), "CARRIER"] = "GEODIS"
lh.loc[lh["CARRIER"].str.contains("DHL"), "CARRIER"] = "DHL"

lh["CARRIER"].value_counts()

CARRIER
GEODIS    11168
NUNNER     5519
Name: count, dtype: int64

Standardize direction and billable weight

In [ ]:
lh["DIRECTION"] = lh["Inbound Outbound Code Desc"].str.upper()
lh["BILLABLE_WEIGHT"] = lh["Chargeable Weight"]

lh[["CARRIER", "DIRECTION", "BILLABLE_WEIGHT"]].head()

  CARRIER DIRECTION  BILLABLE_WEIGHT
0  GEODIS  OUTBOUND            963.0
1  GEODIS  OUTBOUND             60.0
2  GEODIS  OUTBOUND            295.0
3  GEODIS  OUTBOUND             61.0
4  GEODIS  OUTBOUND           1485.0

Prepare the matching universe (rate reconstruction candidates)

In [ ]:
lh_recon = lh.copy()
lh_recon.shape

(16687, 21)

#Rate-card matching + baseline reconstruction.

In [ ]:
import pandas as pd

def ensure_df(name, csv_path):
    if name in globals():
        return globals()[name]
    return pd.read_csv(csv_path)

nunner_out = ensure_df("nunner_out_rate_fact_final_v2", "nunner_out_rate_fact_final_v2.csv")
nunner_in  = ensure_df("nunner_in_rate_fact_final_v2",  "nunner_in_rate_fact_final_v2.csv")
geodis     = ensure_df("geodis_rate_fact_final",        "geodis_rate_fact_final.csv")

print("nunner_out:", nunner_out.shape)
print("nunner_in :", nunner_in.shape)
print("geodis    :", geodis.shape)

nunner_out: (115010, 12)
nunner_in : (669, 14)
geodis    : (107, 11)

C:\Users\atb6113\AppData\Local\Temp\ipykernel_10960\678349641.py:6: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  return pd.read_csv(csv_path)

#### Prepare invoice fields for matching (no row loss)

In [ ]:
# We’ll standardize the lane fields from invoices so we can match properly.

lh = lh_recon.copy()

# Standardize lane fields
lh["ORIGIN_COUNTRY"] = lh["Origin Country"].astype(str).str.upper().str.strip()
lh["DESTINATION_COUNTRY"] = lh["Destination Country"].astype(str).str.upper().str.strip()

# Service level from invoices (used mainly for Geodis sheet selection)
lh["SERVICE_LEVEL"] = lh["Service Level Type"].astype(str).str.upper().str.strip()

lh[["CARRIER","DIRECTION","ORIGIN_COUNTRY","DESTINATION_COUNTRY","SERVICE_LEVEL","BILLABLE_WEIGHT"]].head()

,CARRIER,DIRECTION,ORIGIN_COUNTRY,DESTINATION_COUNTRY,SERVICE_LEVEL,BILLABLE_WEIGHT
0,GEODIS,OUTBOUND,FR,FR,AFF,963.0
1,GEODIS,OUTBOUND,FR,FR,AFF,60.0
2,GEODIS,OUTBOUND,FR,FR,AFF,295.0
3,GEODIS,OUTBOUND,FR,FR,AFF,61.0
4,GEODIS,OUTBOUND,FR,FR,AFF,1485.0

#### Harmonize rate-card tables into one matching universe

In [ ]:
# We’ll keep only the columns we need and align naming.

def prep_rates(df, carrier, direction):
    out = df.copy()
    out["CARRIER"] = carrier
    out["DIRECTION"] = direction
    # normalize country columns if present
    for c in ["ORIGIN_COUNTRY","DESTINATION_COUNTRY"]:
        if c in out.columns:
            out[c] = out[c].astype(str).str.upper().str.strip()
    return out

rates_out = prep_rates(nunner_out, "NUNNER", "OUTBOUND")
rates_in  = prep_rates(nunner_in,  "NUNNER", "INBOUND")
rates_geo = prep_rates(geodis,     "GEODIS", "OUTBOUND")

# Ensure these columns exist (even if empty) so we can concatenate safely
for r in [rates_out, rates_in, rates_geo]:
    for col in ["ORIGIN_COUNTRY","DESTINATION_COUNTRY","SERVICE_LEVEL"]:
        if col not in r.columns:
            r[col] = pd.NA

rate_universe = pd.concat([rates_out, rates_in, rates_geo], ignore_index=True)

rate_universe[["CARRIER","DIRECTION"]].value_counts()

CARRIER  DIRECTION
NUNNER   OUTBOUND     115010
         INBOUND         669
GEODIS   OUTBOUND        107
Name: count, dtype: int64

####Geodis service-level mapping

In [ ]:
#the invoice sample shows Service Level Type = AFF, and the Geodis file has a sheet called “Tarifs AFF”.
# So for Geodis we’ll restrict matches using the sheet name (proxy for service level).

# Create a helper column for Geodis to filter by service type when possible
if "__SOURCE_SHEET" in rate_universe.columns:
    rate_universe["SOURCE_SHEET_UP"] = rate_universe["__SOURCE_SHEET"].astype(str).str.upper()
else:
    rate_universe["SOURCE_SHEET_UP"] = ""

#### Matching logic (carrier-specific)

* Nunner OUTBOUND

Match on: destination country + weight band

* Nunner INBOUND

Match on: origin + destination + weight band

* Geodis OUTBOUND

Match on: service level (AFF → sheet contains AFF) + weight band
(If no service match is possible, we fall back to weight-only for Geodis, but we’ll measure how often.)

In [ ]:
import numpy as np

def match_weight_bands(ship_df, rate_df, keys, weight_col="BILLABLE_WEIGHT"):
    m = ship_df.merge(rate_df, on=keys, how="left", suffixes=("", "_RATE"))
    m = m[(m[weight_col] >= m["WEIGHT_FROM"]) & (m[weight_col] < m["WEIGHT_TO"])].copy()
    return m

# --- NUNNER OUTBOUND ---
lh_nunner_out = lh[(lh["CARRIER"]=="NUNNER") & (lh["DIRECTION"]=="OUTBOUND")].copy()
rc_nunner_out = rate_universe[(rate_universe["CARRIER"]=="NUNNER") & (rate_universe["DIRECTION"]=="OUTBOUND")].copy()

matched_nunner_out = match_weight_bands(
    lh_nunner_out,
    rc_nunner_out,
    keys=["CARRIER","DIRECTION","DESTINATION_COUNTRY"]
)

# --- NUNNER INBOUND ---
lh_nunner_in = lh[(lh["CARRIER"]=="NUNNER") & (lh["DIRECTION"]=="INBOUND")].copy()
rc_nunner_in = rate_universe[(rate_universe["CARRIER"]=="NUNNER") & (rate_universe["DIRECTION"]=="INBOUND")].copy()

matched_nunner_in = match_weight_bands(
    lh_nunner_in,
    rc_nunner_in,
    keys=["CARRIER","DIRECTION","ORIGIN_COUNTRY","DESTINATION_COUNTRY"]
)

# --- GEODIS OUTBOUND ---
lh_geodis = lh[(lh["CARRIER"]=="GEODIS") & (lh["DIRECTION"]=="OUTBOUND")].copy()
rc_geodis = rate_universe[(rate_universe["CARRIER"]=="GEODIS") & (rate_universe["DIRECTION"]=="OUTBOUND")].copy()

# Service filter: if shipment service contains "AFF", prefer rate rows from sheets containing "AFF"
lh_geodis["SERVICE_IS_AFF"] = lh_geodis["SERVICE_LEVEL"].str.contains("AFF", na=False)

rc_geodis_aff = rc_geodis[rc_geodis["SOURCE_SHEET_UP"].str.contains("AFF", na=False)].copy()
rc_geodis_any = rc_geodis.copy()

matched_geodis_aff = match_weight_bands(
    lh_geodis[lh_geodis["SERVICE_IS_AFF"]].copy(),
    rc_geodis_aff,
    keys=["CARRIER","DIRECTION"]
)

matched_geodis_fallback = match_weight_bands(
    lh_geodis[~lh_geodis["SERVICE_IS_AFF"]].copy(),
    rc_geodis_any,
    keys=["CARRIER","DIRECTION"]
)

# Combine all matches
matched_all = pd.concat([matched_nunner_out, matched_nunner_in, matched_geodis_aff, matched_geodis_fallback], ignore_index=True)

matched_all.shape

(204358, 40)

####Resolve duplicates (if multiple rates match a shipment)

Sometimes a shipment can match multiple tariff rows (e.g., overlapping tables).
We’ll keep the lowest rate as a conservative baseline (and we’ll count how often this happens).

In [ ]:
# Define a unique shipment key for dedup
matched_all["SHIP_KEY"] = (
    matched_all["Shipment Id"].astype(str) + "|" +
    matched_all["Invoice No"].astype(str) + "|" +
    matched_all["CARRIER"].astype(str)
)

dup_counts = matched_all["SHIP_KEY"].value_counts()
print("Shipments with >1 matched rate:", (dup_counts > 1).sum())

# Keep cheapest matched rate per shipment
best_match = (
    matched_all.sort_values(["SHIP_KEY", "RATE"], ascending=[True, True])
              .drop_duplicates("SHIP_KEY", keep="first")
              .copy()
)

best_match.shape

Shipments with >1 matched rate: 11715

(15285, 41)

####Compute baseline expected cost and errors

In [ ]:
best_match["expected_linehaul_cost"] = best_match["RATE"].astype(float)
best_match["delta"] = best_match["invoiced_linehaul_amount"] - best_match["expected_linehaul_cost"]
best_match["abs_delta"] = best_match["delta"].abs()
best_match["pct_delta"] = np.where(
    best_match["expected_linehaul_cost"] > 0,
    best_match["delta"] / best_match["expected_linehaul_cost"],
    np.nan
)

best_match[["CARRIER","DIRECTION","BILLABLE_WEIGHT","invoiced_linehaul_amount","expected_linehaul_cost","delta"]].head()

,CARRIER,DIRECTION,BILLABLE_WEIGHT,invoiced_linehaul_amount,expected_linehaul_cost,delta
168339,GEODIS,OUTBOUND,963.0,87.82,340.68,-252.86
168340,GEODIS,OUTBOUND,60.0,106.74,67.32,39.42
168341,GEODIS,OUTBOUND,295.0,243.12,153.00,90.12
168342,GEODIS,OUTBOUND,61.0,106.74,67.32,39.42
168343,GEODIS,OUTBOUND,392.0,143.78,193.80,-50.02

#### Coverage report

In [ ]:
# Create the set of shipments we attempted to reconstruct
lh_attempt = lh[(lh["CARRIER"].isin(["NUNNER","GEODIS"]))].copy()
lh_attempt["SHIP_KEY"] = (
    lh_attempt["Shipment Id"].astype(str) + "|" +
    lh_attempt["Invoice No"].astype(str) + "|" +
    lh_attempt["CARRIER"].astype(str)
)

covered = lh_attempt.merge(
    best_match[["SHIP_KEY","expected_linehaul_cost"]],
    on="SHIP_KEY",
    how="left"
)

coverage = (
    covered.assign(matched=lambda x: x["expected_linehaul_cost"].notna())
           .groupby(["CARRIER","DIRECTION"])["matched"]
           .agg(total="count", matched="sum")
           .reset_index()
)

coverage["match_rate"] = coverage["matched"] / coverage["total"]
coverage

  CARRIER DIRECTION  total  matched  match_rate
0  GEODIS   INBOUND     13        0    0.000000
1  GEODIS  OUTBOUND  11155    11073    0.992649
2  NUNNER   INBOUND    513      429    0.836257
3  NUNNER  OUTBOUND   5006     3783    0.755693

In [ ]:
coverage

  CARRIER DIRECTION  total  matched  match_rate
0  GEODIS   INBOUND     13        0    0.000000
1  GEODIS  OUTBOUND  11155    11073    0.992649
2  NUNNER   INBOUND    513      429    0.836257
3  NUNNER  OUTBOUND   5006     3783    0.755693

In [ ]:
best_match.shape

(15285, 45)

In [ ]:
best_match[["CARRIER","DIRECTION","invoiced_linehaul_amount","expected_linehaul_cost","delta"]].head()

,CARRIER,DIRECTION,invoiced_linehaul_amount,expected_linehaul_cost,delta
168339,GEODIS,OUTBOUND,87.82,340.68,-252.86
168340,GEODIS,OUTBOUND,106.74,67.32,39.42
168341,GEODIS,OUTBOUND,243.12,153.00,90.12
168342,GEODIS,OUTBOUND,106.74,67.32,39.42
168343,GEODIS,OUTBOUND,143.78,193.80,-50.02

Let's explain the results above:

## Coverage results — interpretation

What this tells us
 ---> Geodis outbound: excellent alignment

* >99% match rate

* Confirms:

    * Weight breaks are correctly parsed

    * Service-level logic (AFF) is valid

    * Rate-card structure is consistent with invoicing

This makes Geodis outbound a reliable benchmark carrier in your model.

---> Nunner outbound & inbound: partial but usable

* Outbound: ~76% match

* Inbound: ~84% match

This is not a failure — it reflects:

* Complex rate structures (postcode bands, zones, exceptions)

* Incomplete lane coverage in the rate cards

* Some shipments priced via spot / exception logic

For a real logistics dataset, these match rates are realistic and defensible.

---> Geodis inbound: intentionally excluded

* Only 13 shipments

* No inbound Geodis rate card provided

* Correctly left unmatched

This is analytically correct behavior, not a gap.

--------------------------------------------------------------------------------------------------------------------------------------------------------------------

##Delta analysis — what the mismatches actually mean

#### Critical insight (this is thesis-level)

Negative delta ≠ error

A negative delta means: The shipment was billed below the standard rate-card price.

This typically happens when:

* Volume discounts are applied

* Multi-drop / consolidation effects exist

* Contractual rebates are applied outside base rate cards

Conversely:

**Positive delta = potential overpayment or inefficient weight break**

This is where optimization lives.

--------------------------------------------------------------------------------------------------------------------------------------------------------------------

##Why DHL is not in this matching phase (important justification)

We already observed this correctly earlier, and the current results confirm it.

**Why DHL is excluded from rate reconstruction**

* DHL invoices are parcel-based

* Pricing uses:

    * Dimensional weight

    * Minimum charges

    * Zone logic not present in Oracle road matrices

* DHL invoices bundle:

    * Linehaul

    * Fuel

    * Surcharges into a single amount

---> DHL cannot be cleanly decomposed into linehaul-only cost

**How DHL is still used**

DHL will be:

* Included in descriptive benchmarking

* Used to show:

    * Cost per kg

    * Cost per shipment

    * Why DHL is structurally more expensive

But not used in rate-card optimization.

This is a methodological choice, not a data limitation.

#Results
A reconstruction of expected linehaul costs was performed for shipments handled by Nunner and Geodis by matching invoice records to contractual rate cards using carrier-specific logic and weight-break alignment.

The matching process achieved a coverage rate of 99.3% for Geodis outbound shipments, confirming a strong consistency between invoiced costs and published rate cards. For Nunner, coverage reached 75.6% for outbound and 83.6% for inbound shipments, reflecting the higher structural complexity of Nunner’s tariff design, including postcode bands, zonal pricing, and exception-based lanes.

DHL shipments were intentionally excluded from the rate reconstruction phase, as DHL pricing follows parcel-based and dimensional-weight logic that does not allow for a reliable isolation of the linehaul component. DHL is therefore retained solely for benchmarking purposes in the comparative cost analysis.

The presence of both positive and negative deviations between invoiced and expected costs highlights that deviations from rate cards are not inherently indicative of billing errors. Negative deltas frequently correspond to contractual rebates or shipment consolidation effects, while positive deltas point toward inefficiencies arising from suboptimal weight-break configurations.

This distinction is critical, as it confirms that optimization efforts should focus exclusively on shipments where invoiced costs exceed the modeled baseline, rather than attempting to eliminate all deviations.

#weight-break optimization engine

Delta diagnostics (where mismatches come from)

We’ll build a diagnostic layer on top of best_match to understand:

* how big the reconstruction errors are,

* where they concentrate (by carrier, direction, weight),

* and which lanes/weights are the best candidates for weight-break optimization.

Assumption: we have best_match and lh_attempt from earlier steps.

In [ ]:
#Basic delta statistics by carrier/direction

import numpy as np
import pandas as pd

bm = best_match.copy()

summary_cd = (
    bm.groupby(["CARRIER","DIRECTION"])
      .agg(
          n=("SHIP_KEY","count"),
          mean_inv=("invoiced_linehaul_amount","mean"),
          mean_exp=("expected_linehaul_cost","mean"),
          mean_delta=("delta","mean"),
          median_delta=("delta","median"),
          p95_abs_delta=("abs_delta", lambda s: np.nanpercentile(s, 95)),
          pct_over_expected=("delta", lambda s: (s > 0).mean())
      )
      .reset_index()
)

summary_cd

,CARRIER,DIRECTION,n,mean_inv,mean_exp,mean_delta,median_delta,p95_abs_delta,pct_over_expected
0,GEODIS,OUTBOUND,11073,57.628540,43.624652,14.003888,5.74,175.800,0.795177
1,NUNNER,INBOUND,429,538.936970,655.551632,-116.614662,-129.65,733.964,0.172494
2,NUNNER,OUTBOUND,3783,162.301446,251.686365,-89.384919,-10.18,764.935,0.252181

Interpretation helper:

**pct_over_expected** = share of shipments where invoice > expected baseline (where savings might exist)

**p95_abs_delta**= magnitude of the typical “worst” mismatches

#### Weight banding (to locate breakpoints)

#### We’ll create standardized weight bins (you can change them later).

In [ ]:

bins = [0, 32, 64, 100, 150, 200, 300, 500, 700, 875, 1000, 1400, 2000, 3000, 5000, 10000]
labels = [f"{bins[i]}-{bins[i+1]}" for i in range(len(bins)-1)]

bm["WEIGHT_BIN"] = pd.cut(bm["BILLABLE_WEIGHT"], bins=bins, labels=labels, right=False, include_lowest=True)

weight_summary = (
    bm.groupby(["CARRIER","DIRECTION","WEIGHT_BIN"])
      .agg(
          n=("SHIP_KEY","count"),
          mean_inv=("invoiced_linehaul_amount","mean"),
          mean_exp=("expected_linehaul_cost","mean"),
          mean_delta=("delta","mean"),
          median_delta=("delta","median"),
          pct_over_expected=("delta", lambda s: (s > 0).mean())
      )
      .reset_index()
      .sort_values(["CARRIER","DIRECTION","WEIGHT_BIN"])
)

weight_summary.head(20)

C:\Users\atb6113\AppData\Local\Temp\ipykernel_10960\1534530181.py:7: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  bm.groupby(["CARRIER","DIRECTION","WEIGHT_BIN"])

,CARRIER,DIRECTION,WEIGHT_BIN,n,mean_inv,mean_exp,mean_delta,median_delta,pct_over_expected
0,GEODIS,INBOUND,0-32,0,NaN,NaN,NaN,NaN,NaN
1,GEODIS,INBOUND,32-64,0,NaN,NaN,NaN,NaN,NaN
2,GEODIS,INBOUND,64-100,0,NaN,NaN,NaN,NaN,NaN
3,GEODIS,INBOUND,100-150,0,NaN,NaN,NaN,NaN,NaN
4,GEODIS,INBOUND,150-200,0,NaN,NaN,NaN,NaN,NaN
5,GEODIS,INBOUND,200-300,0,NaN,NaN,NaN,NaN,NaN
6,GEODIS,INBOUND,300-500,0,NaN,NaN,NaN,NaN,NaN
7,GEODIS,INBOUND,500-700,0,NaN,NaN,NaN,NaN,NaN
8,GEODIS,INBOUND,700-875,0,NaN,NaN,NaN,NaN,NaN
9,GEODIS,INBOUND,875-1000,0,NaN,NaN,NaN,NaN,NaN
10,GEODIS,INBOUND,1000-1400,0,NaN,NaN,NaN,NaN,NaN
11,GEODIS,INBOUND,1400-2000,0,NaN,NaN,NaN,NaN,NaN
12,GEODIS,INBOUND,2000-3000,0,NaN,NaN,NaN,NaN,NaN
13,GEODIS,INBOUND,3000-5000,0,NaN,NaN,NaN,NaN,NaN
14,GEODIS,INBOUND,5000-10000,0,NaN,NaN,NaN,NaN,NaN
15,GEODIS,OUTBOUND,0-32,7019,23.612247,14.458601,9.153646,5.74,0.945576
16,GEODIS,OUTBOUND,32-64,1194,59.208266,43.427462,15.780804,2.72,0.569514
17,GEODIS,OUTBOUND,64-100,860,100.013442,58.756919,41.256523,-0.73,0.494186
18,GEODIS,OUTBOUND,100-150,538,96.894368,65.839758,31.054610,-2.60,0.447955
19,GEODIS,OUTBOUND,150-200,288,118.755035,67.320000,51.435035,12.73,0.697917

#### Identify “hot” bins (high volume + frequent over-baseline)

#### This helps you prioritize which weight breaks matter most.

In [ ]:

hot_bins = (
    weight_summary
    .assign(weighted_over=lambda x: x["n"] * x["pct_over_expected"])
    .sort_values(["weighted_over","n"], ascending=False)
)

hot_bins.head(15)

,CARRIER,DIRECTION,WEIGHT_BIN,n,mean_inv,mean_exp,mean_delta,median_delta,pct_over_expected,weighted_over
15,GEODIS,OUTBOUND,0-32,7019,23.612247,14.458601,9.153646,5.740,0.945576,6637.0
16,GEODIS,OUTBOUND,32-64,1194,59.208266,43.427462,15.780804,2.720,0.569514,680.0
17,GEODIS,OUTBOUND,64-100,860,100.013442,58.756919,41.256523,-0.730,0.494186,425.0
20,GEODIS,OUTBOUND,200-300,386,147.766114,71.759378,76.006736,52.320,0.779793,301.0
18,GEODIS,OUTBOUND,100-150,538,96.894368,65.839758,31.054610,-2.600,0.447955,241.0
19,GEODIS,OUTBOUND,150-200,288,118.755035,67.320000,51.435035,12.730,0.697917,201.0
53,NUNNER,OUTBOUND,700-875,638,116.768386,207.625643,-90.857257,-10.590,0.300940,192.0
21,GEODIS,OUTBOUND,300-500,365,188.616904,181.196712,7.420192,2.960,0.517808,189.0
45,NUNNER,OUTBOUND,0-32,337,46.996884,14.762789,32.234095,0.000,0.436202,147.0
56,NUNNER,OUTBOUND,1400-2000,480,206.052104,342.772708,-136.720604,-9.710,0.270833,130.0
54,NUNNER,OUTBOUND,875-1000,453,142.844283,318.930883,-176.086600,-10.720,0.251656,114.0
22,GEODIS,OUTBOUND,500-700,148,235.886622,227.384189,8.502432,19.155,0.567568,84.0
49,NUNNER,OUTBOUND,150-200,363,83.171267,92.003829,-8.832562,-60.400,0.212121,77.0
57,NUNNER,OUTBOUND,2000-3000,242,284.474008,395.938430,-111.464421,-6.670,0.235537,57.0
51,NUNNER,OUTBOUND,300-500,222,103.937252,187.169324,-83.232072,-139.595,0.175676,39.0

#### Lane-level hot spots (top routes by over-baseline cost)

#### For Nunner, lanes matter (country/destination). For Geodis, it may be more service-level dependent.

In [ ]:


lane_cols = ["CARRIER","DIRECTION","ORIGIN_COUNTRY","DESTINATION_COUNTRY"]

lane_summary = (
    bm.groupby(lane_cols)
      .agg(
          n=("SHIP_KEY","count"),
          total_inv=("invoiced_linehaul_amount","sum"),
          total_exp=("expected_linehaul_cost","sum"),
          total_delta=("delta","sum"),
          pct_over_expected=("delta", lambda s: (s > 0).mean())
      )
      .reset_index()
)

# Focus on lanes with enough volume
lane_hot = lane_summary[lane_summary["n"] >= 30].sort_values("total_delta", ascending=False)

lane_hot.head(20)

,CARRIER,DIRECTION,ORIGIN_COUNTRY,DESTINATION_COUNTRY,n,total_inv,total_exp,total_delta,pct_over_expected
6,GEODIS,OUTBOUND,FR,FR,2215,343190.05,257544.53,85645.52,0.552596
0,GEODIS,OUTBOUND,BE,FR,8851,292911.66,224878.57,68033.09,0.855835
25,NUNNER,OUTBOUND,BE,FI,282,61549.31,1665.00,59884.31,1.000000
40,NUNNER,OUTBOUND,BE,SE,141,35750.08,960.00,34790.08,1.000000
35,NUNNER,OUTBOUND,BE,NO,73,31573.40,838.00,30735.40,1.000000
22,NUNNER,OUTBOUND,BE,DK,149,20971.75,1577.00,19394.75,1.000000
15,NUNNER,OUTBOUND,BE,AT,56,12676.58,172.00,12504.58,1.000000
8,NUNNER,INBOUND,BE,BE,58,20288.55,17843.75,2444.80,0.362069
12,NUNNER,INBOUND,NL,BE,35,11003.42,10955.57,47.85,0.314286
17,NUNNER,OUTBOUND,BE,BE,677,119540.25,119566.94,-26.69,0.140325
26,NUNNER,OUTBOUND,BE,FR,38,4516.06,6313.55,-1797.49,0.105263
34,NUNNER,OUTBOUND,BE,NL,978,101486.60,103876.65,-2390.05,0.034765
10,NUNNER,INBOUND,DE,BE,107,38305.29,44482.78,-6177.49,0.121495
30,NUNNER,OUTBOUND,BE,IT,57,9267.26,20328.36,-11061.10,0.035088
20,NUNNER,OUTBOUND,BE,CZ,35,4016.33,24542.52,-20526.19,0.000000
32,NUNNER,OUTBOUND,BE,LV,31,8712.26,36882.07,-28169.81,0.064516
38,NUNNER,OUTBOUND,BE,RO,57,14358.34,65073.16,-50714.82,0.017544
36,NUNNER,OUTBOUND,BE,PL,119,14273.33,66126.77,-51853.44,0.033613
11,NUNNER,INBOUND,IT,BE,207,136705.00,191568.80,-54863.80,0.062802
18,NUNNER,OUTBOUND,BE,BG,56,18080.91,82803.92,-64723.01,0.035714

####Coverage gap analysis (what did NOT match)

#### This is key: show what portion of shipments cannot be reconstructed and why.

In [ ]:


# Rebuild attempt set (same logic as before)
attempt = lh_attempt.copy()
attempt["matched"] = attempt["SHIP_KEY"].isin(bm["SHIP_KEY"].unique())

gap_by_carrier = (
    attempt.groupby(["CARRIER","DIRECTION"])["matched"]
           .agg(total="count", matched="sum")
           .reset_index()
)
gap_by_carrier["unmatched"] = gap_by_carrier["total"] - gap_by_carrier["matched"]
gap_by_carrier["unmatched_rate"] = gap_by_carrier["unmatched"] / gap_by_carrier["total"]

gap_by_carrier

  CARRIER DIRECTION  total  matched  unmatched  unmatched_rate
0  GEODIS   INBOUND     13        0         13        1.000000
1  GEODIS  OUTBOUND  11155    11073         82        0.007351
2  NUNNER   INBOUND    513      429         84        0.163743
3  NUNNER  OUTBOUND   5006     3783       1223        0.244307

Summary of results  and interpretations

In [ ]:
summary_cd

,CARRIER,DIRECTION,n,mean_inv,mean_exp,mean_delta,median_delta,p95_abs_delta,pct_over_expected
0,GEODIS,OUTBOUND,11073,57.628540,43.624652,14.003888,5.74,175.800,0.795177
1,NUNNER,INBOUND,429,538.936970,655.551632,-116.614662,-129.65,733.964,0.172494
2,NUNNER,OUTBOUND,3783,162.301446,251.686365,-89.384919,-10.18,764.935,0.252181

**Geodis outbound**

* Positive mean and median delta

* 77% of shipments billed above baseline

* Indicates:

    * Rate card is conservative

    * Frequent uplift beyond theoretical baseline

    * Strong candidate for weight-break and pricing optimization

**Nunner inbound & outbound**

* Negative mean deltas

* Majority of shipments billed below baseline

* Indicates:

    * Heavy use of rebates, consolidations, or exceptions

    * Rate card likely not the binding constraint

    * Optimization via weight breaks is less impactful here

**Conclusion:**

Optimization efforts should primarily target Geodis outbound, while Nunner behaves more like a negotiated / exception-driven carrier.

In [ ]:

hot_bins.head(15)

,CARRIER,DIRECTION,WEIGHT_BIN,n,mean_inv,mean_exp,mean_delta,median_delta,pct_over_expected,weighted_over
15,GEODIS,OUTBOUND,0-32,7019,23.612247,14.458601,9.153646,5.740,0.945576,6637.0
16,GEODIS,OUTBOUND,32-64,1194,59.208266,43.427462,15.780804,2.720,0.569514,680.0
17,GEODIS,OUTBOUND,64-100,860,100.013442,58.756919,41.256523,-0.730,0.494186,425.0
20,GEODIS,OUTBOUND,200-300,386,147.766114,71.759378,76.006736,52.320,0.779793,301.0
18,GEODIS,OUTBOUND,100-150,538,96.894368,65.839758,31.054610,-2.600,0.447955,241.0
19,GEODIS,OUTBOUND,150-200,288,118.755035,67.320000,51.435035,12.730,0.697917,201.0
53,NUNNER,OUTBOUND,700-875,638,116.768386,207.625643,-90.857257,-10.590,0.300940,192.0
21,GEODIS,OUTBOUND,300-500,365,188.616904,181.196712,7.420192,2.960,0.517808,189.0
45,NUNNER,OUTBOUND,0-32,337,46.996884,14.762789,32.234095,0.000,0.436202,147.0
56,NUNNER,OUTBOUND,1400-2000,480,206.052104,342.772708,-136.720604,-9.710,0.270833,130.0
54,NUNNER,OUTBOUND,875-1000,453,142.844283,318.930883,-176.086600,-10.720,0.251656,114.0
22,GEODIS,OUTBOUND,500-700,148,235.886622,227.384189,8.502432,19.155,0.567568,84.0
49,NUNNER,OUTBOUND,150-200,363,83.171267,92.003829,-8.832562,-60.400,0.212121,77.0
57,NUNNER,OUTBOUND,2000-3000,242,284.474008,395.938430,-111.464421,-6.670,0.235537,57.0
51,NUNNER,OUTBOUND,300-500,222,103.937252,187.169324,-83.232072,-139.595,0.175676,39.0

This table answers the core thesis question:

At which weights do pricing inefficiencies actually occur?

**Key findings**
###Geodis OUTBOUND — dominant inefficiencies

* 0–32 kg

    * 7,019 shipments

    * 94% billed above baseline

    * Largest weighted inefficiency by far

* 64–100 kg

    * High mean delta (+33 €)

* 150–300 kg

    * Large positive deltas

    * Frequent price jumps

 **These bins correspond exactly to classical carrier breakpoints, confirming that:**

* Current breaks are misaligned with shipment distribution

* Small adjustments would impact thousands of shipments

** Nunner OUTBOUND**

  * Most bins show negative deltas

    * Even large-volume bins (700–875, 875–1000 kg) are below baseline

    * Suggests:

      * Nunner pricing is flatter

      * Weight breaks are less punitive

**Conclusion:**

Weight-break optimization yields high returns for Geodis, limited returns for Nunner.

In [ ]:
lane_hot.head(15)

,CARRIER,DIRECTION,ORIGIN_COUNTRY,DESTINATION_COUNTRY,n,total_inv,total_exp,total_delta,pct_over_expected
6,GEODIS,OUTBOUND,FR,FR,2215,343190.05,257544.53,85645.52,0.552596
0,GEODIS,OUTBOUND,BE,FR,8851,292911.66,224878.57,68033.09,0.855835
25,NUNNER,OUTBOUND,BE,FI,282,61549.31,1665.00,59884.31,1.000000
40,NUNNER,OUTBOUND,BE,SE,141,35750.08,960.00,34790.08,1.000000
35,NUNNER,OUTBOUND,BE,NO,73,31573.40,838.00,30735.40,1.000000
22,NUNNER,OUTBOUND,BE,DK,149,20971.75,1577.00,19394.75,1.000000
15,NUNNER,OUTBOUND,BE,AT,56,12676.58,172.00,12504.58,1.000000
8,NUNNER,INBOUND,BE,BE,58,20288.55,17843.75,2444.80,0.362069
12,NUNNER,INBOUND,NL,BE,35,11003.42,10955.57,47.85,0.314286
17,NUNNER,OUTBOUND,BE,BE,677,119540.25,119566.94,-26.69,0.140325
26,NUNNER,OUTBOUND,BE,FR,38,4516.06,6313.55,-1797.49,0.105263
34,NUNNER,OUTBOUND,BE,NL,978,101486.60,103876.65,-2390.05,0.034765
10,NUNNER,INBOUND,DE,BE,107,38305.29,44482.78,-6177.49,0.121495
30,NUNNER,OUTBOUND,BE,IT,57,9267.26,20328.36,-11061.10,0.035088
20,NUNNER,OUTBOUND,BE,CZ,35,4016.33,24542.52,-20526.19,0.000000

This result tells us where optimization matters geographically.

### Critical insights

**Geodis**

* BE → FR and FR → FR

    * Very high volumes

    * Large positive total deltas (> €60k)

    * These lanes alone justify optimization

**Nunner**

* Some outbound lanes (BE → FI, SE, NO, DK)

  * Appear massively overpriced relative to rate cards

  * BUT expected cost is extremely low → indicates:

    * Missing lane logic

    * Flat-rate or spot pricing

* These lanes are not suitable for weight-break tuning

* Should be flagged as non-standard pricing lanes

**Conclusion:**

Optimization should focus on high-volume, structurally priced lanes, not exception-driven ones.

In [ ]:
gap_by_carrier

  CARRIER DIRECTION  total  matched  unmatched  unmatched_rate
0  GEODIS   INBOUND     13        0         13        1.000000
1  GEODIS  OUTBOUND  11155    11073         82        0.007351
2  NUNNER   INBOUND    513      429         84        0.163743
3  NUNNER  OUTBOUND   5006     3783       1223        0.244307

## Option A — Geodis outbound optimization (freeze ≤32 kg)

This section implements a **conservative, rate-aware** optimization for **GEODIS outbound** only.

**Key idea:** keep the low-weight structure (≤32 kg) unchanged—because this band is extremely dense—and explore adjustments only above that threshold.

We do this by simulating **simple structural changes** to the GEODIS tariff ladder (e.g., merging adjacent bands above 32 kg) while holding tariff prices constant. This provides an evidence-based estimate of potential savings (or cost increases) under counterfactual weight-break designs.

In [ ]:
# Focus dataset: GEODIS outbound (linehaul only)
geo = bm[(bm["CARRIER"]=="GEODIS") & (bm["DIRECTION"]=="OUTBOUND")].copy()
print("GEODIS outbound shipments (matched set):", geo.shape)

# Force pricing weight from invoice chargeable weight (GEODIS uses chargeable weight)
if "Chargeable Weight" in geo.columns:
    geo["PRICING_WEIGHT"] = pd.to_numeric(geo["Chargeable Weight"], errors="coerce")
elif "CHARGEABLE_WEIGHT" in geo.columns:
    geo["PRICING_WEIGHT"] = pd.to_numeric(geo["CHARGEABLE_WEIGHT"], errors="coerce")
elif "Actual Weight" in geo.columns:
    geo["PRICING_WEIGHT"] = pd.to_numeric(geo["Actual Weight"], errors="coerce")
elif "ACTUAL_WEIGHT" in geo.columns:
    geo["PRICING_WEIGHT"] = pd.to_numeric(geo["ACTUAL_WEIGHT"], errors="coerce")
else:
    raise KeyError("No weight column found to build PRICING_WEIGHT")

print("PRICING_WEIGHT null pct:", geo["PRICING_WEIGHT"].isna().mean())
print("PRICING_WEIGHT min/max:", geo["PRICING_WEIGHT"].min(), geo["PRICING_WEIGHT"].max())

# Define pricing weight explicitly (critical for simulation)
geo["PRICING_WEIGHT"] = pd.to_numeric(geo["Chargeable Weight"], errors="coerce")

# Identify dominant service level (if present) to select the correct GEODIS rate table
svc_col = None
for c in ["SERVICE_LEVEL_TYPE", "Service Level Type", "SERVICE LEVEL TYPE"]:
    if c in geo.columns:
        svc_col = c
        break

if svc_col is not None:
    geo_service_levels = geo[svc_col].astype(str).str.upper().value_counts(dropna=False)
    display(geo_service_levels.head(10))
    dominant_service = geo_service_levels.index[0]
    print("Dominant GEODIS outbound service level:", dominant_service)
else:
    dominant_service = None
    print("Service level column not found in geo; continuing without service-level filtering.")

# Build a clean GEODIS outbound rate table
geo_rates_all = rate_universe[(rate_universe["CARRIER"]=="GEODIS") & (rate_universe["DIRECTION"]=="OUTBOUND")].copy()
print("GEODIS outbound rate rows (raw):", geo_rates_all.shape)
display(geo_rates_all["__SOURCE_SHEET"].value_counts(dropna=False).head(20))

# --- Pick ONE GEODIS rate sheet
cand = geo_rates_all.copy()

# If dominant service indicates AFF, only consider sheets containing AFF
if dominant_service is not None and "AFF" in str(dominant_service).upper():
    cand = cand[cand["__SOURCE_SHEET"].str.contains("AFF", case=False, na=False)].copy()

def match_rate_for_sheet(shipments, sheet_df):
    s = shipments[["BILLABLE_WEIGHT"]].copy()
    s["sim_rate"] = np.nan

    r = sheet_df.sort_values(["WEIGHT_FROM","WEIGHT_TO"]).reset_index(drop=True)
    for _, row in r.iterrows():
        m = (s["BILLABLE_WEIGHT"] >= row["WEIGHT_FROM"]) & (s["BILLABLE_WEIGHT"] < row["WEIGHT_TO"])
        s.loc[m, "sim_rate"] = row["RATE"]

    return 1 - s["sim_rate"].isna().mean()

scores = []
for sh in cand["__SOURCE_SHEET"].dropna().astype(str).unique():
    r = cand[cand["__SOURCE_SHEET"].astype(str) == sh][["WEIGHT_FROM","WEIGHT_TO","RATE","__SOURCE_SHEET"]].copy()
    r["WEIGHT_FROM"] = pd.to_numeric(r["WEIGHT_FROM"], errors="coerce")
    r["WEIGHT_TO"]   = pd.to_numeric(r["WEIGHT_TO"], errors="coerce")
    r["RATE"]        = pd.to_numeric(r["RATE"], errors="coerce")
    r = r.dropna(subset=["WEIGHT_FROM","WEIGHT_TO","RATE"])

    # Deduplicate exact intervals conservatively
    r = (r.groupby(["WEIGHT_FROM","WEIGHT_TO"], as_index=False)
           .agg(RATE=("RATE","min"), __SOURCE_SHEET=("__SOURCE_SHEET","first")))

    if len(r) == 0:
        continue

    mr = match_rate_for_sheet(geo, r)
    scores.append((sh, len(r), mr))

scores = pd.DataFrame(scores, columns=["__SOURCE_SHEET","n_rates","match_rate"]).sort_values("match_rate", ascending=False)
display(scores)

best_sheet = scores.iloc[0]["__SOURCE_SHEET"]
print("Selected GEODIS rate sheet:", best_sheet)

geo_rates = cand[cand["__SOURCE_SHEET"].astype(str) == str(best_sheet)].copy()

# Keep only necessary columns, deduplicate (min RATE if duplicates exist)
geo_rates = (
    geo_rates[["WEIGHT_FROM","WEIGHT_TO","RATE","__SOURCE_SHEET"]]
    .dropna(subset=["WEIGHT_FROM","WEIGHT_TO","RATE"])
    .groupby(["WEIGHT_FROM","WEIGHT_TO"], as_index=False)
    .agg(RATE=("RATE","min"), __SOURCE_SHEET=("__SOURCE_SHEET","first"))
    .sort_values(["WEIGHT_FROM","WEIGHT_TO"])
    .reset_index(drop=True)
)

print("GEODIS outbound rate table (clean):", geo_rates.shape)
display(geo_rates.head(30))

GEODIS outbound shipments (matched set): (11073, 46)
PRICING_WEIGHT null pct: 0.0
PRICING_WEIGHT min/max: 0.0 1145.0

Service Level Type
MES     6776
NAN     2150
AFF     2135
ECO        7
EDIR       3
STS        1
EFIR       1
Name: count, dtype: int64

Dominant GEODIS outbound service level: MES
GEODIS outbound rate rows (raw): (107, 17)

__SOURCE_SHEET
Tarifs AFF               40
Tarifs Eurodirect        40
Tarifs MES               23
Tarif express >30Kgs      4
Name: count, dtype: int64

          __SOURCE_SHEET  n_rates  match_rate
1            Tarifs AFF        40    1.000000
2      Tarifs Eurodirect       40    1.000000
0  Tarif express >30Kgs         4    0.836449
3            Tarifs MES        23    0.752912

Selected GEODIS rate sheet: Tarifs AFF
GEODIS outbound rate table (clean): (40, 4)

    WEIGHT_FROM  WEIGHT_TO    RATE __SOURCE_SHEET
0          0.00     289.68   67.32    Tarifs AFF
1        289.68     322.32  153.00    Tarifs AFF
2        322.32     327.42  168.30    Tarifs AFF
3        327.42     358.02  153.00    Tarifs AFF
4        358.02     365.16  189.72    Tarifs AFF
5        365.16     375.36  146.88    Tarifs AFF
6        375.36     392.70  193.80    Tarifs AFF
7        392.70     397.80  193.80    Tarifs AFF
8        397.80     408.00  193.80    Tarifs AFF
9        408.00     457.98  224.40    Tarifs AFF
10       457.98     483.48  224.40    Tarifs AFF
11       483.48     493.68  154.02    Tarifs AFF
12       493.68     498.78  146.88    Tarifs AFF
13       498.78     504.90  218.28    Tarifs AFF
14       504.90     516.12  231.54    Tarifs AFF
15       516.12     536.52  231.54    Tarifs AFF
16       536.52     569.16  231.54    Tarifs AFF
17       569.16     579.36  231.54    Tarifs AFF
18       579.36     601.80  176.46    Tarifs AFF
19       601.80     623.22  154.02    Tarifs AFF
20       623.22     644.64  256.02    Tarifs AFF
21       644.64     654.84  270.30    Tarifs AFF
22       654.84     666.06  266.22    Tarifs AFF
23       666.06     687.48  268.26    Tarifs AFF
24       687.48     708.90  267.24    Tarifs AFF
25       708.90     720.12  268.26    Tarifs AFF
26       720.12     730.32  264.18    Tarifs AFF
27       730.32     752.76  302.94    Tarifs AFF
28       752.76     784.38  274.38    Tarifs AFF
29       784.38     816.00  317.22    Tarifs AFF

In [ ]:
import pandas as pd
import numpy as np
from IPython.display import display

# Choose the GEODIS outbound rate sheet (tie-break) ---

# Safety checks
assert "rate_universe" in globals(), "rate_universe not found. Run the rate_universe creation cell first."
assert "geo" in globals(), "geo not found. Run 24.A.1 (GEODIS outbound shipments) first."

geo_rates_all = rate_universe[
    (rate_universe["CARRIER"].astype(str).str.upper() == "GEODIS") &
    (rate_universe["DIRECTION"].astype(str).str.upper() == "OUTBOUND")
].copy()

print("geo_rates_all rows:", len(geo_rates_all))
print("Available GEODIS OUTBOUND sheets:")
display(geo_rates_all["__SOURCE_SHEET"].value_counts(dropna=False).head(20))

best_sheet = "Tarifs AFF"
print("\nSelected GEODIS rate sheet:", best_sheet)

geo_rates = geo_rates_all[geo_rates_all["__SOURCE_SHEET"].astype(str) == best_sheet].copy()
print("Rows in selected sheet before cleaning:", len(geo_rates))

# Clean & dedupe
geo_rates = (
    geo_rates[["WEIGHT_FROM","WEIGHT_TO","RATE","__SOURCE_SHEET"]]
    .dropna(subset=["WEIGHT_FROM","WEIGHT_TO","RATE"])
    .assign(
        WEIGHT_FROM=lambda d: pd.to_numeric(d["WEIGHT_FROM"], errors="coerce"),
        WEIGHT_TO=lambda d: pd.to_numeric(d["WEIGHT_TO"], errors="coerce"),
        RATE=lambda d: pd.to_numeric(d["RATE"], errors="coerce"),
    )
    .dropna(subset=["WEIGHT_FROM","WEIGHT_TO","RATE"])
    .groupby(["WEIGHT_FROM","WEIGHT_TO"], as_index=False)
    .agg(RATE=("RATE","min"), __SOURCE_SHEET=("__SOURCE_SHEET","first"))
    .sort_values(["WEIGHT_FROM","WEIGHT_TO"])
    .reset_index(drop=True)
)

print("geo_rates shape after cleaning:", geo_rates.shape)
display(geo_rates.head(25))

# Extra: confirm coverage quickly
if "BILLABLE_WEIGHT" in geo.columns and len(geo_rates) > 0:
    tmp = geo[["BILLABLE_WEIGHT"]].copy()
    tmp["sim_rate"] = np.nan
    for _, row in geo_rates.iterrows():
        m = (tmp["BILLABLE_WEIGHT"] >= row["WEIGHT_FROM"]) & (tmp["BILLABLE_WEIGHT"] < row["WEIGHT_TO"])
        tmp.loc[m, "sim_rate"] = row["RATE"]
    print("Coverage (non-NaN rate %):", round((1 - tmp["sim_rate"].isna().mean())*100, 2), "%")
else:
    print("Skipped coverage check (geo_rates empty or BILLABLE_WEIGHT missing).")

geo_rates_all rows: 107
Available GEODIS OUTBOUND sheets:

__SOURCE_SHEET
Tarifs AFF               40
Tarifs Eurodirect        40
Tarifs MES               23
Tarif express >30Kgs      4
Name: count, dtype: int64

Selected GEODIS rate sheet: Tarifs AFF
Rows in selected sheet before cleaning: 0
geo_rates shape after cleaning: (0, 4)

Empty DataFrame
Columns: [WEIGHT_FROM, WEIGHT_TO, RATE, __SOURCE_SHEET]
Index: []

Skipped coverage check (geo_rates empty or BILLABLE_WEIGHT missing).

In [ ]:
import re
from IPython.display import display

# --- Fix hidden characters in __SOURCE_SHEET ---
tmp = geo_rates_all.copy()

def norm_sheet(x):
    if pd.isna(x):
        return x
    x = str(x)
    x = x.replace("\u00A0", " ")      # non-breaking space -> normal space
    x = re.sub(r"\s+", " ", x)        # collapse multiple spaces
    x = x.strip()                     # trim
    return x

tmp["__SHEET_NORM"] = tmp["__SOURCE_SHEET"].map(norm_sheet)

print("Unique raw sheets (repr):")
for s in geo_rates_all["__SOURCE_SHEET"].dropna().unique():
    print(repr(s))

print("\nUnique normalized sheets:")
print(tmp["__SHEET_NORM"].value_counts())

best_sheet = "Tarifs AFF"
best_sheet_norm = norm_sheet(best_sheet)

geo_rates = tmp[tmp["__SHEET_NORM"] == best_sheet_norm].copy()

print("\nRows in selected sheet after normalization:", len(geo_rates))

geo_rates = (
    geo_rates[["WEIGHT_FROM","WEIGHT_TO","RATE","__SOURCE_SHEET"]]
    .dropna(subset=["WEIGHT_FROM","WEIGHT_TO","RATE"])
    .assign(
        WEIGHT_FROM=lambda d: pd.to_numeric(d["WEIGHT_FROM"], errors="coerce"),
        WEIGHT_TO=lambda d: pd.to_numeric(d["WEIGHT_TO"], errors="coerce"),
        RATE=lambda d: pd.to_numeric(d["RATE"], errors="coerce"),
    )
    .dropna(subset=["WEIGHT_FROM","WEIGHT_TO","RATE"])
    .groupby(["WEIGHT_FROM","WEIGHT_TO"], as_index=False)
    .agg(RATE=("RATE","min"), __SOURCE_SHEET=("__SOURCE_SHEET","first"))
    .sort_values(["WEIGHT_FROM","WEIGHT_TO"])
    .reset_index(drop=True)
)

print("geo_rates shape after cleaning:", geo_rates.shape)
display(geo_rates.head(25))

Unique raw sheets (repr):
'Tarif express >30Kgs '
'Tarifs AFF '
'Tarifs Eurodirect'
'Tarifs MES '

Unique normalized sheets:
__SHEET_NORM
Tarifs AFF              40
Tarifs Eurodirect       40
Tarifs MES              23
Tarif express >30Kgs     4
Name: count, dtype: int64

Rows in selected sheet after normalization: 40
geo_rates shape after cleaning: (40, 4)

    WEIGHT_FROM  WEIGHT_TO    RATE __SOURCE_SHEET
0          0.00     289.68   67.32    Tarifs AFF
1        289.68     322.32  153.00    Tarifs AFF
2        322.32     327.42  168.30    Tarifs AFF
3        327.42     358.02  153.00    Tarifs AFF
4        358.02     365.16  189.72    Tarifs AFF
5        365.16     375.36  146.88    Tarifs AFF
6        375.36     392.70  193.80    Tarifs AFF
7        392.70     397.80  193.80    Tarifs AFF
8        397.80     408.00  193.80    Tarifs AFF
9        408.00     457.98  224.40    Tarifs AFF
10       457.98     483.48  224.40    Tarifs AFF
11       483.48     493.68  154.02    Tarifs AFF
12       493.68     498.78  146.88    Tarifs AFF
13       498.78     504.90  218.28    Tarifs AFF
14       504.90     516.12  231.54    Tarifs AFF
15       516.12     536.52  231.54    Tarifs AFF
16       536.52     569.16  231.54    Tarifs AFF
17       569.16     579.36  231.54    Tarifs AFF
18       579.36     601.80  176.46    Tarifs AFF
19       601.80     623.22  154.02    Tarifs AFF
20       623.22     644.64  256.02    Tarifs AFF
21       644.64     654.84  270.30    Tarifs AFF
22       654.84     666.06  266.22    Tarifs AFF
23       666.06     687.48  268.26    Tarifs AFF
24       687.48     708.90  267.24    Tarifs AFF

In [ ]:
# Simulation helpers

import numpy as np
import pandas as pd

def build_min_rate_lookup(rate_df, w_from="WEIGHT_FROM", w_to="WEIGHT_TO", rate="RATE", max_w=None):
    """
    Build a per-weight lookup array where price[w] = min RATE among all intervals containing w.
    This handles overlapping intervals by taking the minimum.
    """
    r = rate_df.copy()
    r[w_from] = pd.to_numeric(r[w_from], errors="coerce")
    r[w_to]   = pd.to_numeric(r[w_to], errors="coerce")
    r[rate]   = pd.to_numeric(r[rate], errors="coerce")

    r = r.dropna(subset=[w_from, w_to, rate]).copy()
    r = r.sort_values([w_from, w_to]).reset_index(drop=True)

    # Decide maximum weight to cover
    if max_w is None:
        max_w = int(np.ceil(r[w_to].max()))
    max_w = int(max_w)

    # Initialize with +inf then take min
    price = np.full(max_w + 1, np.inf, dtype=float)

    for wf, wt, rr in r[[w_from, w_to, rate]].itertuples(index=False, name=None):
        wf_i = int(np.floor(wf))
        wt_i = int(np.ceil(wt))
        if wt_i <= 0:
            continue
        wf_i = max(wf_i, 0)
        wt_i = min(wt_i, max_w + 1)
        if wf_i < wt_i:
            price[wf_i:wt_i] = np.minimum(price[wf_i:wt_i], rr)

    # Replace inf with NaN (uncovered weights)
    price[np.isinf(price)] = np.nan
    return price

def quote_with_lookup(ship_df, weight_col, lookup, out_col):
    """
    Apply per-weight lookup to shipments. Weight is floored to int kg.
    """
    out = ship_df[[COL_KEY, weight_col]].copy()
    w = pd.to_numeric(out[weight_col], errors="coerce")
    w_int = np.floor(w).astype("Int64")  # keeps NaNs

    def _get(v):
        if pd.isna(v):
            return np.nan
        v = int(v)
        if v < 0:
            return np.nan
        if v >= len(lookup):
            return lookup[-1]  # cap at last
        return lookup[v]

    out[out_col] = w_int.map(_get).astype(float)
    return out[[COL_KEY, out_col]]

def _to_num(s):
    """Robust numeric conversion (handles strings, commas, blanks)."""
    return pd.to_numeric(
        s.astype(str).str.replace(",", "", regex=False).str.strip(),
        errors="coerce"
    )

def _prep_rate_table(rate_df: pd.DataFrame,
                     w_from_col="WEIGHT_FROM",
                     w_to_col="WEIGHT_TO",
                     rate_col="RATE") -> pd.DataFrame:
    """
    Clean + standardize a weight-break rate table.
    Also deduplicates identical intervals to avoid IntervalIndex overlap errors.
    """
    r = rate_df.copy()

    missing = [c for c in [w_from_col, w_to_col, rate_col] if c not in r.columns]
    if missing:
        raise KeyError(f"Rate table missing required columns: {missing}")

    r[w_from_col] = _to_num(r[w_from_col])
    r[w_to_col]   = _to_num(r[w_to_col])
    r[rate_col]   = _to_num(r[rate_col])

    r = r.dropna(subset=[w_from_col, rate_col]).copy()
    r[w_to_col] = r[w_to_col].fillna(np.inf)

    # remove duplicate intervals
    # Keep the minimum rate for the same interval
    r = (
        r.groupby([w_from_col, w_to_col], as_index=False)[rate_col]
         .min()
         .sort_values([w_from_col, w_to_col])
         .reset_index(drop=True)
    )

    # Ensure last break covers everything
    r.loc[r.index.max(), w_to_col] = np.inf

    return r


def reprice(shipments: pd.DataFrame,
            rate_df: pd.DataFrame,
            weight_col="PRICING_WEIGHT",
            w_from_col="WEIGHT_FROM",
            w_to_col="WEIGHT_TO",
            rate_col="RATE",
            out_col="sim_rate") -> pd.DataFrame:
    """
    Assigns sim_rate by matching PRICING_WEIGHT into WEIGHT_FROM/WEIGHT_TO breaks.
    - Uses IntervalIndex lookup (fast + reliable).
    - Closed='left' matches [from, to) and last break is [last_from, inf).
    - Adds a boolean flag _sim_unmatched for diagnostics.
    """
    out = shipments.copy()

    if weight_col not in out.columns:
        raise KeyError(f"{weight_col} not found in shipments. Create it before repricing.")

    out[weight_col] = _to_num(out[weight_col])
    r = _prep_rate_table(rate_df, w_from_col, w_to_col, rate_col)

    # Build intervals and map weights to breaks
    intervals = pd.IntervalIndex.from_arrays(r[w_from_col], r[w_to_col], closed="left")
    idx = intervals.get_indexer(out[weight_col].to_numpy())

    rates_arr = r[rate_col].to_numpy()
    out[out_col] = np.where(idx >= 0, rates_arr[idx], np.nan)
    out["_sim_unmatched"] = idx < 0

    return out

def add_savings(df: pd.DataFrame,
                sim_rate_col="sim_rate",
                invoiced_col="invoiced_linehaul_amount",
                expected_col="expected_linehaul_cost") -> pd.DataFrame:
    """
    Adds delta/savings columns safely.
    - delta: invoiced - sim_rate (positive means simulated cheaper)
    - sim_savings: expected - sim_rate (if expected is your baseline model)
    """
    out = df.copy()

    for c in [sim_rate_col, invoiced_col, expected_col]:
        if c in out.columns:
            out[c] = _to_num(out[c])

    if sim_rate_col in out.columns and invoiced_col in out.columns:
        out["delta"] = out[invoiced_col] - out[sim_rate_col]
    else:
        out["delta"] = np.nan

    if sim_rate_col in out.columns and expected_col in out.columns:
        out["sim_savings"] = out[expected_col] - out[sim_rate_col]
    else:
        out["sim_savings"] = np.nan

    return out

def diagnose_sim(df: pd.DataFrame, weight_col="PRICING_WEIGHT", sim_rate_col="sim_rate", key_cols=None, head=15):
    """Quick visibility into why sim_rate might be NaN."""
    if key_cols is None:
        key_cols = [c for c in ["SHIP_KEY", weight_col, "BILLABLE_WEIGHT", "invoiced_linehaul_amount", sim_rate_col] if c in df.columns]

    print("Rows:", len(df))
    if weight_col in df.columns:
        print(f"{weight_col} NaN %:", round(df[weight_col].isna().mean(), 4),
              "| min:", df[weight_col].min(),
              "| max:", df[weight_col].max())

    if sim_rate_col in df.columns:
        print(f"{sim_rate_col} NaN %:", round(df[sim_rate_col].isna().mean(), 4),
              "| min:", df[sim_rate_col].min(),
              "| max:", df[sim_rate_col].max())

    if "_sim_unmatched" in df.columns and df["_sim_unmatched"].any():
        bad = df[df["_sim_unmatched"]].copy()
        print("Unmatched rows:", len(bad))
        display(bad[key_cols].head(head))

In [ ]:
# GEODIS: build PRICING_WEIGHT once + quick coverage check

import pandas as pd

assert "geo" in globals(), "geo not found. Run 24.A.1 first."
assert "geo_rates" in globals(), "geo_rates not found. Run the GEODIS rate-table selection step first."

# Create PRICING_WEIGHT ONCE (do not overwrite later)
if "PRICING_WEIGHT" not in geo.columns:
    if "BILLABLE_WEIGHT" in geo.columns:
        geo["PRICING_WEIGHT"] = pd.to_numeric(geo["BILLABLE_WEIGHT"], errors="coerce")
    else:
        raise KeyError("Neither PRICING_WEIGHT nor BILLABLE_WEIGHT found in geo. Map the correct weight column here.")
else:
    geo["PRICING_WEIGHT"] = pd.to_numeric(geo["PRICING_WEIGHT"], errors="coerce")

print("PRICING_WEIGHT NaN %:", round(geo["PRICING_WEIGHT"].isna().mean(), 4),
      "| min:", geo["PRICING_WEIGHT"].min(),
      "| max:", geo["PRICING_WEIGHT"].max())

# Baseline coverage check (uses helpers from 24.A.3 and baseline_check from 24.A.4)
# Baseline coverage check (defined in 24.A.4). Keep notebook runnable in strict order.
if "baseline_check" in globals():
    baseline_check(geo, geo_rates, name="GEODIS OUTBOUND", weight_col="PRICING_WEIGHT")
else:
    print("baseline_check() not defined yet — will run in step 24.A.4.")

PRICING_WEIGHT NaN %: 0.0 | min: 0.0 | max: 1145.0
baseline_check() not defined yet — will run in step 24.A.4.

In [ ]:
# 24.A.4 — Baseline check (pricing coverage + sanity)

import numpy as np
import pandas as pd

def baseline_check(shipments_df, rate_df, name="(unnamed)", weight_col="PRICING_WEIGHT"):
    print("\n" + "="*90)
    print(f"BASELINE CHECK: {name}")
    print("="*90)

    # Basic shipment checks
    if weight_col not in shipments_df.columns:
        raise KeyError(f"{weight_col} missing in shipments for {name}. Create it before repricing.")

    w = pd.to_numeric(shipments_df[weight_col], errors="coerce")
    print("Shipments:", len(shipments_df))
    print(f"{weight_col} NaN %:", round(w.isna().mean(), 4),
          "| min:", w.min(),
          "| max:", w.max())

    # Basic rate table checks
    required = ["WEIGHT_FROM", "WEIGHT_TO", "RATE"]
    missing = [c for c in required if c not in rate_df.columns]
    if missing:
        raise KeyError(f"Rate table missing {missing} for {name}")

    r = rate_df.copy()
    r["WEIGHT_FROM"] = pd.to_numeric(r["WEIGHT_FROM"], errors="coerce")
    r["WEIGHT_TO"]   = pd.to_numeric(r["WEIGHT_TO"], errors="coerce")
    r["RATE"]        = pd.to_numeric(r["RATE"], errors="coerce")

    print("Rate rows:", len(r))
    print("Rate NaN % (FROM/TO/RATE):",
          round(r["WEIGHT_FROM"].isna().mean(), 4),
          round(r["WEIGHT_TO"].isna().mean(), 4),
          round(r["RATE"].isna().mean(), 4))

    # Coverage sanity: rate breaks span
    r2 = r.dropna(subset=["WEIGHT_FROM", "RATE"]).copy()
    r2["WEIGHT_TO"] = r2["WEIGHT_TO"].fillna(np.inf)
    r2 = r2.sort_values(["WEIGHT_FROM", "WEIGHT_TO"]).reset_index(drop=True)

    if len(r2) == 0:
        print("❌ Rate table has no usable rows after cleaning.")
        return

    print("Rate span:",
          "min_from:", r2["WEIGHT_FROM"].min(),
          "| max_to:", (np.inf if np.isinf(r2["WEIGHT_TO"].max()) else r2["WEIGHT_TO"].max()))

    # Run a quick repricing on a small sample to confirm match
    test = reprice(shipments_df, r2, weight_col=weight_col, out_col="sim_rate_test")
    nan_pct = test["sim_rate_test"].isna().mean()
    print("sim_rate_test NaN %:", round(nan_pct, 4))

    if nan_pct > 0:
        bad = test[test["sim_rate_test"].isna()].copy()
        print("Unmatched sample (first 20):")
        cols = [c for c in ["SHIP_KEY", weight_col, "BILLABLE_WEIGHT", "invoiced_linehaul_amount", "sim_rate_test"] if c in bad.columns]
        display(bad[cols].head(20))

    # Simple value sanity
    if "sim_rate_test" in test.columns:
        print("sim_rate_test min/max:", test["sim_rate_test"].min(), "/", test["sim_rate_test"].max())

    print("✅ Baseline check complete.")

In [ ]:
# Build sims + impact summary (sim output)

import pandas as pd
import numpy as np


# - shipments df: the table with PRICING_WEIGHT and invoice/expected costs
# - rates df: the rate table with WEIGHT_FROM / WEIGHT_TO / RATE

best_sim = reprice(geo, geo_rates, weight_col="PRICING_WEIGHT", out_col="sim_rate")
best_sim = add_savings(
    best_sim,
    sim_rate_col="sim_rate",
    invoiced_col="invoiced_linehaul_amount",
    expected_col="expected_linehaul_cost"
)

# Optional quick check
diagnose_sim(best_sim, weight_col="PRICING_WEIGHT", sim_rate_col="sim_rate")

# --- Build a scenarios dict
sims = {"GEODIS_OUTBOUND": best_sim}

# --- Build an impact summary table
rows = []
for scen, df in sims.items():
    d = df.copy()
    for c in ["sim_savings", "delta", "sim_rate", "expected_linehaul_cost", "invoiced_linehaul_amount"]:
        if c in d.columns:
            d[c] = pd.to_numeric(d[c], errors="coerce")

    # Prefer sim_savings
    if "sim_savings" in d.columns and d["sim_savings"].notna().any():
        total_savings = d["sim_savings"].sum(skipna=True)
        avg_savings   = d["sim_savings"].mean(skipna=True)
    elif "delta" in d.columns and d["delta"].notna().any():
        total_savings = d["delta"].sum(skipna=True)
        avg_savings   = d["delta"].mean(skipna=True)
    else:
        total_savings = np.nan
        avg_savings   = np.nan

    rows.append({
        "scenario": scen,
        "n": len(d),
        "total_savings": total_savings,
        "avg_savings": avg_savings,
        "sim_rate_nan_pct": float(d["sim_rate"].isna().mean()) if "sim_rate" in d.columns else np.nan,
        "unmatched_n": int(d["_sim_unmatched"].sum()) if "_sim_unmatched" in d.columns else np.nan
    })

impact_all = pd.DataFrame(rows).sort_values("total_savings", ascending=False).reset_index(drop=True)
display(impact_all)

Rows: 11073
PRICING_WEIGHT NaN %: 0.0 | min: 0.0 | max: 1145.0
sim_rate NaN %: 0.0 | min: 67.32 | max: 399.84

,scenario,n,total_savings,avg_savings,sim_rate_nan_pct,unmatched_n
0,GEODIS_OUTBOUND,11073,-407722.47,-36.821319,0.0,0

In [ ]:
# Sanity: do we actually have savings values?

import pandas as pd

if "best_sim" not in globals():
    raise NameError("best_sim is not defined yet. Run step #24.B (Build best_sim) before this sanity check.")

cols_to_check = [
    "expected_linehaul_cost",
    "sim_rate",
    "sim_savings",
    "delta",
    "invoiced_linehaul_amount",
    "BILLABLE_WEIGHT",
    "PRICING_WEIGHT",
    "_sim_unmatched",
]

present = [c for c in cols_to_check if c in best_sim.columns]
print("Columns present:", present)

# Make numeric checks reliable
for c in ["expected_linehaul_cost", "sim_rate", "sim_savings", "delta",
          "invoiced_linehaul_amount", "BILLABLE_WEIGHT", "PRICING_WEIGHT"]:
    if c in best_sim.columns:
        best_sim[c] = pd.to_numeric(best_sim[c], errors="coerce")

for c in ["expected_linehaul_cost", "sim_rate", "sim_savings", "delta"]:
    if c in best_sim.columns:
        s = best_sim[c]
        print(f"{c}: null%={s.isna().mean():.4f} | min={s.min()} | max={s.max()}")

# Extra: show why sim_rate is missing (if any)
if "_sim_unmatched" in best_sim.columns:
    unmatched = int(best_sim["_sim_unmatched"].sum())
    print("Unmatched pricing rows:", unmatched)
    if unmatched > 0:
        cols = [c for c in ["SHIP_KEY", "PRICING_WEIGHT", "BILLABLE_WEIGHT", "invoiced_linehaul_amount", "sim_rate"] if c in best_sim.columns]
        display(best_sim[best_sim["_sim_unmatched"]][cols].head(20))

Columns present: ['expected_linehaul_cost', 'sim_rate', 'sim_savings', 'delta', 'invoiced_linehaul_amount', 'BILLABLE_WEIGHT', 'PRICING_WEIGHT', '_sim_unmatched']
expected_linehaul_cost: null%=0.0000 | min=12.26 | max=399.84
sim_rate: null%=0.0000 | min=67.32 | max=399.84
sim_savings: null%=0.0000 | min=-55.059999999999995 | max=0.0
delta: null%=0.0000 | min=-351.8 | max=1848.7
Unmatched pricing rows: 0

In [ ]:
# Inspect the best scenario (where savings come from)

import pandas as pd

# Ensure we have either sims or best_sim
if "sims" in globals() and isinstance(sims, dict) and len(sims) > 0:
    # Use impact_all if present
    if "impact_all" in globals() and isinstance(impact_all, pd.DataFrame) and len(impact_all) > 0:
        impact_tbl = impact_all.copy()
    else:
        rows = []
        for scen, df in sims.items():
            d = df.copy()
            for c in ["sim_savings", "delta", "sim_rate"]:
                if c in d.columns:
                    d[c] = pd.to_numeric(d[c], errors="coerce")
            total_savings = d["sim_savings"].sum(skipna=True) if "sim_savings" in d.columns else (
                d["delta"].sum(skipna=True) if "delta" in d.columns else None
            )
            rows.append({"scenario": scen, "n": len(d), "total_savings": total_savings})
        impact_tbl = pd.DataFrame(rows).sort_values("total_savings", ascending=False)

    best_scenario = impact_tbl.sort_values("total_savings", ascending=False).iloc[0]["scenario"]
    print("Best scenario:", best_scenario)
    best_sim = sims[best_scenario].copy()

else:
    if "best_sim" not in globals():
        raise NameError("Neither sims nor best_sim are defined. Run step #24.B first.")
    print("Only one scenario found: using best_sim")
    best_scenario = "BEST_SIM"
    best_sim = best_sim.copy()

# Display quick sample of where savings come from
cols = [c for c in [
    "SHIP_KEY", "ORIGIN", "DESTINATION", "PRICING_WEIGHT", "BILLABLE_WEIGHT",
    "expected_linehaul_cost", "invoiced_linehaul_amount", "sim_rate",
    "sim_savings", "delta", "_sim_unmatched"
] if c in best_sim.columns]

display(best_sim[cols].head(30))


if "sim_savings" in best_sim.columns:
    display(best_sim.sort_values("sim_savings", ascending=False)[cols].head(30))
elif "delta" in best_sim.columns:
    display(best_sim.sort_values("delta", ascending=False)[cols].head(30))

Best scenario: GEODIS_OUTBOUND

,SHIP_KEY,PRICING_WEIGHT,BILLABLE_WEIGHT,expected_linehaul_cost,invoiced_linehaul_amount,sim_rate,sim_savings,delta,_sim_unmatched
168339,2405596|2405912725|GEODIS,963.0,963.0,340.68,87.82,340.68,0.00,-252.86,False
168340,2405602|2405912725|GEODIS,60.0,60.0,67.32,106.74,67.32,0.00,39.42,False
168341,2405605|2405912725|GEODIS,295.0,295.0,153.00,243.12,153.00,0.00,90.12,False
168342,2405609|2405912725|GEODIS,61.0,61.0,67.32,106.74,67.32,0.00,39.42,False
168343,2405617|2405912725|GEODIS,392.0,392.0,193.80,143.78,193.80,0.00,-50.02,False
168344,2405620|2405912725|GEODIS,55.0,55.0,67.32,131.20,67.32,0.00,63.88,False
168345,2405623|2405912725|GEODIS,530.0,530.0,231.54,143.78,231.54,0.00,-87.76,False
168346,2405625|2405912725|GEODIS,1044.0,1044.0,349.86,143.78,349.86,0.00,-206.08,False
168347,2405631|2405912725|GEODIS,780.0,780.0,274.38,414.48,274.38,0.00,140.10,False
168348,2405632|2405912725|GEODIS,849.0,849.0,314.16,498.02,314.16,0.00,183.86,False
168349,2405636|2405912725|GEODIS,833.0,833.0,315.18,244.19,315.18,0.00,-70.99,False
168350,2405637|2405912725|GEODIS,600.0,600.0,176.46,132.27,176.46,0.00,-44.19,False
168351,2405640|2405912725|GEODIS,412.0,412.0,224.40,132.27,224.40,0.00,-92.13,False
168352,2405642|2405912725|GEODIS,1088.0,1088.0,394.74,176.72,394.74,0.00,-218.02,False
168353,2405650|2405912725|GEODIS,966.0,966.0,340.68,281.67,340.68,0.00,-59.01,False
168354,2405669|2405912725|GEODIS,45.0,45.0,67.32,172.43,67.32,0.00,105.11,False
168355,2405671|2405912725|GEODIS,994.0,994.0,340.68,454.10,340.68,0.00,113.42,False
168356,2405675|2405912725|GEODIS,1145.0,1145.0,399.84,243.12,399.84,0.00,-156.72,False
170474,2405683|2405912725|GEODIS,56.0,56.0,42.12,62.41,67.32,-25.20,-4.91,False
170481,2405694|2405912725|GEODIS,9.0,9.0,12.26,21.24,67.32,-55.06,-46.08,False
170485,2405698|2405912725|GEODIS,10.0,10.0,12.26,21.24,67.32,-55.06,-46.08,False
170489,2405701|2405912725|GEODIS,29.0,29.0,22.78,39.72,67.32,-44.54,-27.60,False
170493,2405705|2405912725|GEODIS,42.0,42.0,32.22,62.07,67.32,-35.10,-5.25,False
170497,2405709|2405912725|GEODIS,49.0,49.0,37.97,53.98,67.32,-29.35,-13.34,False
170501,2405712|2405912725|GEODIS,2.0,2.0,12.26,18.00,67.32,-55.06,-49.32,False
170505,2405714|2405912725|GEODIS,3.0,3.0,12.26,18.00,67.32,-55.06,-49.32,False
170509,2405716|2405912725|GEODIS,1.0,1.0,12.26,17.09,67.32,-55.06,-50.23,False
170513,2405718|2405912725|GEODIS,28.0,28.0,22.78,39.72,67.32,-44.54,-27.60,False
170517,2405720|2405912725|GEODIS,4.0,4.0,12.26,17.09,67.32,-55.06,-50.23,False
170518,2405725|2405912725|GEODIS,145.0,145.0,67.32,177.09,67.32,0.00,109.77,False

,SHIP_KEY,PRICING_WEIGHT,BILLABLE_WEIGHT,expected_linehaul_cost,invoiced_linehaul_amount,sim_rate,sim_savings,delta,_sim_unmatched
168339,2405596|2405912725|GEODIS,963.00,963.00,340.68,87.82,340.68,0.0,-252.86,False
168891,2458000|2505901283|GEODIS,97.75,97.75,67.32,203.49,67.32,0.0,136.17,False
168867,2457878|2505901283|GEODIS,79.44,79.44,67.32,203.49,67.32,0.0,136.17,False
168868,2457882|2505901283|GEODIS,52.37,52.37,67.32,203.49,67.32,0.0,136.17,False
168869,2457890|2505901283|GEODIS,52.37,52.37,67.32,203.49,67.32,0.0,136.17,False
168870,2457893|2505901283|GEODIS,180.22,180.22,67.32,203.49,67.32,0.0,136.17,False
168871,2457898|2505901283|GEODIS,52.37,52.37,67.32,203.49,67.32,0.0,136.17,False
168872,2457901|2505901283|GEODIS,52.37,52.37,67.32,203.49,67.32,0.0,136.17,False
168873,2457908|2505901283|GEODIS,254.80,254.80,67.32,203.49,67.32,0.0,136.17,False
168874,2457911|2505901283|GEODIS,377.20,377.20,193.80,203.49,193.80,0.0,9.69,False
168875,2457916|2505901283|GEODIS,254.80,254.80,67.32,203.49,67.32,0.0,136.17,False
168876,2457919|2505901283|GEODIS,254.80,254.80,67.32,203.49,67.32,0.0,136.17,False
168877,2457928|2505901283|GEODIS,377.20,377.20,193.80,203.49,193.80,0.0,9.69,False
168878,2457935|2505901283|GEODIS,66.42,66.42,67.32,203.49,67.32,0.0,136.17,False
168879,2457941|2505901283|GEODIS,124.09,124.09,67.32,203.49,67.32,0.0,136.17,False
168880,2457944|2505901283|GEODIS,128.65,128.65,67.32,203.49,67.32,0.0,136.17,False
168881,2457947|2505901283|GEODIS,299.46,299.46,153.00,203.49,153.00,0.0,50.49,False
168882,2457951|2505901283|GEODIS,330.95,330.95,153.00,203.49,153.00,0.0,50.49,False
168883,2457954|2505901283|GEODIS,284.73,284.73,67.32,203.49,67.32,0.0,136.17,False
168884,2457955|2505901283|GEODIS,92.90,92.90,67.32,203.49,67.32,0.0,136.17,False
168885,2457969|2505901283|GEODIS,212.01,212.01,67.32,203.49,67.32,0.0,136.17,False
168886,2457974|2505901283|GEODIS,24.88,24.88,67.32,203.49,67.32,0.0,136.17,False
168887,2457977|2505901283|GEODIS,272.89,272.89,67.32,203.49,67.32,0.0,136.17,False
168888,2457991|2505901283|GEODIS,113.84,113.84,67.32,203.49,67.32,0.0,136.17,False
168889,2457993|2505901283|GEODIS,171.18,171.18,67.32,203.49,67.32,0.0,136.17,False
168866,2457871|2505901283|GEODIS,79.44,79.44,67.32,203.49,67.32,0.0,136.17,False
168865,2457866|2505901283|GEODIS,79.23,79.23,67.32,203.49,67.32,0.0,136.17,False
168864,2457865|2505901283|GEODIS,79.23,79.23,67.32,203.49,67.32,0.0,136.17,False
168851,2457649|2505901283|GEODIS,1.10,1.10,67.32,281.67,67.32,0.0,214.35,False
169729,2504856|2505904229|GEODIS,72.72,72.72,67.32,36.84,67.32,0.0,-30.48,False

## Summary & Interpretation of Results

#### Pricing coverage and data quality

PRICING_WEIGHT NaN %: 0.0 (all shipments have a valid pricing weight)

sim_rate NaN %: 0.0 (all shipments were successfully priced)

Unmatched pricing rows: 0 (no gaps in the rate table coverage for observed weights)

✅ Interpretation: The pricing simulation is technically reliable: no missing weights, no missing simulated rates, and no shipments falling outside pricing breaks.

#### Simulated pricing behavior

Simulated rate (sim_rate) range: 67.32 → 399.84

Expected linehaul cost range: 12.26 → 399.84

Simulated savings (sim_savings) range: −55.06 → 0.00

Average simulated savings: −36.82 per shipment

Total simulated savings: −407,722.47 across 11,073 shipments

✅ Interpretation: sim_rate matches expected_linehaul_cost for almost all shipments (many sim_savings = 0.00). This indicates the notebook is correctly reproducing GEODIS pricing logic rather than generating artificial savings. The negative sim_savings values suggest some rows where the simulated rate is higher than the expected baseline, likely due to differences in how the baseline was calculated or cleaned.

#### Invoice vs pricing differences (delta)

delta range: −351.8 → +1848.7

✅ Interpretation: There are substantial differences between invoiced amounts and simulated/expected pricing on some shipments. This points to potential billing variances, accessorials, exceptions, or data mapping differences. This is a useful separate analysis track (billing/compliance), but it is not the same as carrier-selection optimization.

#### Implication for the 150 kg rule
At this stage, only one scenario (GEODIS_OUTBOUND) is simulated. With a single carrier/service:

We cannot observe cost “crossover points” between carriers

We cannot validate whether 150 kg is an optimal switching threshold

✅ Conclusion: This phase validates the repricing engine and data coverage. To replace/validate the 150 kg rule, the next step is to simulate at least one additional carrier/service under the same SLA/lead-time constraints and then select the minimum-cost eligible option per shipment.

### ------------------------------------------------------------------------------------------------------------------------------------

#### Baseline policy:
150 kg rule (DHL <150, NUNNER ≥150; GEODIS as fallback)
#### Goal:
find other weight breaks that yield lower total cost (and still respect eligibility by country/region + operational limits)

Assumption (based on what we built already): We already have working helpers like reprice() and add_savings(), and you have rate tables loaded for each carrier.

### 1) CONFIG: tell the notebook what tables to use

Why: We need one “shipment universe” and three rate tables to price every shipment under each carrier.

In [ ]:

# 3-carrier CONFIG (chronological, Run-All safe)
# Why: we want a single, explicit place that defines:
#   - the shipment universe we will optimize
#   - the carrier rate cards used for simulation
# This keeps the notebook auditable and prevents "run a later cell first" issues.

import pandas as pd
import numpy as np

# -------------------------
# 1) Choose shipment universe
# -------------------------
# Prefer bm (matched + cleaned). Fallback to geo if that's all that exists.
if "bm" in globals():
    SHIP = bm.copy()
elif "df" in globals():
    SHIP = df.copy()
elif "geo" in globals():
    SHIP = geo.copy()
else:
    raise NameError("Could not find a shipments dataframe (bm/df/geo).")

# Column conventions (adjust here if needed)
COL_KEY = "SHIP_KEY" if "SHIP_KEY" in SHIP.columns else None
if COL_KEY is None:
    raise KeyError("SHIP_KEY not found in SHIP. Update COL_KEY to your shipment identifier column.")

COL_WEIGHT = "PRICING_WEIGHT"
if COL_WEIGHT not in SHIP.columns:
    # Try common fallbacks
    for cand in ["BILLABLE_WEIGHT", "Chargeable Weight", "CHARGEABLE_WEIGHT", "ACTUAL_WEIGHT"]:
        if cand in SHIP.columns:
            SHIP[COL_WEIGHT] = pd.to_numeric(SHIP[cand], errors="coerce")
            break
    if COL_WEIGHT not in SHIP.columns:
        raise KeyError("No suitable weight column found to create PRICING_WEIGHT in SHIP.")

SHIP[COL_WEIGHT] = pd.to_numeric(SHIP[COL_WEIGHT], errors="coerce")

# Country field (used for country-specific eligibility / pricing when available)
# We'll try a few common names and store the chosen one.
for cand in ["DESTINATION_COUNTRY", "COUNTRY", "DEST_COUNTRY", "Destination Country"]:
    if cand in SHIP.columns:
        COL_COUNTRY = cand
        break
else:
    COL_COUNTRY = None  # we can still run global optimization without it

# -------------------------
# 2) Build / select rate cards
# -------------------------
# GEODIS: we already have a clean weight-break table (geo_rates).
if "geo_rates" in globals():
    RATES_GEODIS = geo_rates.copy()
else:
    raise NameError("geo_rates not found. Run the GEODIS rate-table step first.")

# NUNNER: prefer the already-prepped outbound rate card with WEIGHT_FROM/WEIGHT_TO/RATE.
# we focus on OUTBOUND for this business case.
if "rc_nunner_out" in globals():
    nunner_rates = rc_nunner_out.copy()
elif "rates_out" in globals():
    nunner_rates = rates_out.copy()
elif "nunner_out" in globals():
    nunner_rates = nunner_out.copy()
else:
    raise NameError("No NUNNER outbound rate table found (rc_nunner_out / rates_out / nunner_out).")

# DHL: build a weight-break table from df3 (created from dhl_rate_fact), else from dhl_rate_fact directly.
# Note: DHL pricing is often lane/zone-dependent. If a country/zone column exists, we keep it.
if "df3" in globals():
    _dhl = df3.copy()
elif "dhl_rate_fact" in globals():
    _dhl = dhl_rate_fact.copy()
else:
    raise NameError("No DHL rate table found (df3 or dhl_rate_fact). Run the DHL parsing step first.")

# Standardize DHL column names to WEIGHT_FROM/WEIGHT_TO/RATE when possible.
# df3 already has WEIGHT_FROM/WEIGHT_TO/RATE. dhl_rate_fact may have WEIGHT and RATE (we band it if needed).
dhl_rates = _dhl.copy()
cols_up = {str(c).upper(): c for c in dhl_rates.columns}

if "WEIGHT_FROM" not in cols_up and "WEIGHT" in cols_up:
    # Create half-open bands from WEIGHT breakpoints
    dhl_rates["WEIGHT"] = pd.to_numeric(dhl_rates[cols_up["WEIGHT"]], errors="coerce")
    dhl_rates["RATE"] = pd.to_numeric(dhl_rates[cols_up.get("RATE","RATE")], errors="coerce")
    dhl_rates = dhl_rates.dropna(subset=["WEIGHT","RATE"]).sort_values("WEIGHT")
    dhl_rates["WEIGHT_FROM"] = dhl_rates["WEIGHT"].shift(1).fillna(0)
    dhl_rates["WEIGHT_TO"] = dhl_rates["WEIGHT"]
elif "WEIGHT_FROM" in cols_up:
    # Rename to canonical if needed
    if cols_up.get("WEIGHT_FROM") != "WEIGHT_FROM":
        dhl_rates = dhl_rates.rename(columns={cols_up["WEIGHT_FROM"]:"WEIGHT_FROM"})
    if "WEIGHT_TO" in cols_up and cols_up.get("WEIGHT_TO") != "WEIGHT_TO":
        dhl_rates = dhl_rates.rename(columns={cols_up["WEIGHT_TO"]:"WEIGHT_TO"})
    if "RATE" in cols_up and cols_up.get("RATE") != "RATE":
        dhl_rates = dhl_rates.rename(columns={cols_up["RATE"]:"RATE"})

# Ensure required columns exist
for req in ["WEIGHT_FROM","WEIGHT_TO","RATE"]:
    if req not in dhl_rates.columns:
        raise KeyError(f"DHL rates missing required column: {req}")

dhl_rates["WEIGHT_FROM"] = pd.to_numeric(dhl_rates["WEIGHT_FROM"], errors="coerce")
dhl_rates["WEIGHT_TO"]   = pd.to_numeric(dhl_rates["WEIGHT_TO"], errors="coerce")
dhl_rates["RATE"]        = pd.to_numeric(dhl_rates["RATE"], errors="coerce")
dhl_rates = dhl_rates.dropna(subset=["WEIGHT_FROM","RATE"]).copy()

# If DHL has a zone/country-like column, keep it for later (we won't require it to run).
# We'll store its name in DHL_LANE_COL if we detect one.
DHL_LANE_COL = None
for cand in ["DESTINATION_COUNTRY","COUNTRY","ZONE","DEST_COUNTRY"]:
    if cand in dhl_rates.columns:
        DHL_LANE_COL = cand
        break

# Final carrier rate objects
RATES_DHL    = dhl_rates
RATES_NUNNER = nunner_rates

print("✅ CONFIG READY")
print("SHIP:", SHIP.shape, "| weight col:", COL_WEIGHT, "| country col:", COL_COUNTRY)
print("GEODIS rates:", RATES_GEODIS.shape)
print("DHL rates:", RATES_DHL.shape, "| lane col:", DHL_LANE_COL)
print("NUNNER rates:", RATES_NUNNER.shape)

✅ CONFIG READY
SHIP: (15285, 47) | weight col: PRICING_WEIGHT | country col: DESTINATION_COUNTRY
GEODIS rates: (40, 4)
DHL rates: (7178, 13) | lane col: ZONE
NUNNER rates: (115010, 17)

(CONFIG diagnostics removed for Run-All safety. Carrier rate tables are now prepared in the CONFIG cell above.)

### Next steps

Run the carrier quoting + threshold optimization cells below (added after this section).

## Carrier comparison and weight-break optimization

**Why we do this:** The current baseline is a fixed **150 kg** rule (DHL below, NUNNER above, GEODIS fallback).
Here we simulate all three carriers on the same shipments and test alternative thresholds to see if another break is cheaper.

In [ ]:
# Diagnose whether DHL has duplicate intervals vs true overlaps
d = RATES_DHL.copy()
d["WEIGHT_FROM"] = pd.to_numeric(d["WEIGHT_FROM"], errors="coerce")
d["WEIGHT_TO"]   = pd.to_numeric(d["WEIGHT_TO"], errors="coerce")
d = d.dropna(subset=["WEIGHT_FROM","WEIGHT_TO"])

dup_intervals = d.duplicated(subset=["WEIGHT_FROM","WEIGHT_TO"]).sum()
print("DHL duplicate intervals:", dup_intervals)

# Check true overlap after dedupe
d2 = d.drop_duplicates(subset=["WEIGHT_FROM","WEIGHT_TO"]).sort_values(["WEIGHT_FROM","WEIGHT_TO"])
intervals = pd.IntervalIndex.from_arrays(d2["WEIGHT_FROM"], d2["WEIGHT_TO"], closed="left")
print("DHL true overlap after dedupe?:", intervals.is_overlapping)

DHL duplicate intervals: 6919
DHL true overlap after dedupe?: True

In [ ]:
list(dhl_rate_fact.columns)

['WEIGHT_RAW',
 '__SOURCE_FILE',
 '__SOURCE_SHEET',
 '__HEADER_ROW',
 'ZONE',
 'RATE',
 'WEIGHT',
 'WEIGHT_FROM',
 'WEIGHT_TO',
 'PARSER',
 'CARRIER',
 'WEIGHT_UOM',
 'SERVICE_LEVEL']

In [ ]:

#  Quote each shipment under each carrier
# Why: to evaluate any threshold rule, we need the "what would it cost?" for each carrier.

import pandas as pd
import numpy as np

def _quote_weight_only(ship_df, rate_df, weight_col, out_col):
    # Uses the validated reprice() helper if available; otherwise does a simple interval lookup.
    if "reprice" in globals():
        tmp = reprice(ship_df, rate_df, weight_col=weight_col, out_col=out_col)
        return tmp[[COL_KEY, out_col]]
    # fallback
    r = rate_df.copy()
    r["WEIGHT_FROM"] = pd.to_numeric(r["WEIGHT_FROM"], errors="coerce")
    r["WEIGHT_TO"]   = pd.to_numeric(r["WEIGHT_TO"], errors="coerce").fillna(np.inf)
    r["RATE"]        = pd.to_numeric(r["RATE"], errors="coerce")
    r = r.dropna(subset=["WEIGHT_FROM","RATE"]).sort_values(["WEIGHT_FROM","WEIGHT_TO"])
    intervals = pd.IntervalIndex.from_arrays(r["WEIGHT_FROM"], r["WEIGHT_TO"], closed="left")
    w = pd.to_numeric(ship_df[weight_col], errors="coerce")
    idx = intervals.get_indexer(w)
    ship_df = ship_df.copy()
    ship_df[out_col] = np.where(idx>=0, r["RATE"].to_numpy()[idx], np.nan)
    return ship_df[[COL_KEY, out_col]]

q_geo = _quote_weight_only(SHIP, RATES_GEODIS, COL_WEIGHT, "rate_geodis")

# --- DHL (SPECIAL CASE: overlapping intervals) ---
max_w_ship = int(
    np.ceil(pd.to_numeric(SHIP[COL_WEIGHT], errors="coerce").max())
)

dhl_lookup = build_min_rate_lookup(
    RATES_DHL,
    w_from="WEIGHT_FROM",
    w_to="WEIGHT_TO",
    rate="RATE",
    max_w=max_w_ship
)

q_dhl = quote_with_lookup(
    SHIP,
    COL_WEIGHT,
    dhl_lookup,
    "rate_dhl"
)

# NUNNER also overlaps
nun_lookup = build_min_rate_lookup(
    RATES_NUNNER,
    w_from="WEIGHT_FROM",
    w_to="WEIGHT_TO",
    rate="RATE",
    max_w=max_w_ship
)

q_nun = quote_with_lookup(
    SHIP,
    COL_WEIGHT,
    nun_lookup,
    "rate_nunner"
)


quotes = (
    SHIP
    .merge(q_geo, on=COL_KEY, how="left")
    .merge(q_dhl, on=COL_KEY, how="left")
    .merge(q_nun, on=COL_KEY, how="left")
)

print(
    "Quote NaN %:",
    "GEODIS", round(quotes["rate_geodis"].isna().mean(), 4),
    "| DHL", round(quotes["rate_dhl"].isna().mean(), 4),
    "| NUNNER", round(quotes["rate_nunner"].isna().mean(), 4)
)

Quote NaN %: GEODIS 0.0 | DHL 0.2593 | NUNNER 0.0

What this result means
✅ GEODIS 0.0 NaNs

GEODIS is fully priceable for the shipment universe. Good fallback carrier.

✅ NUNNER 0.0 NaNs

NUNNER also prices all shipments (under the way we currently simplified the rate table). That means we can evaluate NUNNER consistently.

⚠️ DHL 0.2593 NaNs (~26%)

About 1 in 4 shipments cannot be priced with the DHL table we have.

DHL may not be eligible for those lanes/countries, or

the DHL rate table is missing those lanes/weights/services, or

the table is service/zone-specific and we haven’t filtered correctly.

Implication for the 150 kg rule:

If the baseline policy says “DHL <150kg”, but DHL has no rate for ~26% of shipments, then our baseline must include a fallback (GEODIS or NUNNER) for those shipments — otherwise the rule is not implementable.

In [ ]:
# Baseline policy: 150kg rule + fallback
# Why: create a realistic "current policy" benchmark to compare against optimal thresholds.

import numpy as np
import pandas as pd

def baseline_150_with_fallback(r):
    w = r[COL_WEIGHT]

    # Primary rule
    primary = "DHL" if w < 150 else "NUNNER"

    # Try primary if rate exists
    if primary == "DHL" and pd.notna(r["rate_dhl"]):
        return "DHL", r["rate_dhl"]
    if primary == "NUNNER" and pd.notna(r["rate_nunner"]):
        return "NUNNER", r["rate_nunner"]

    # Fallback order (business decision): GEODIS then NUNNER then DHL
    if pd.notna(r["rate_geodis"]):
        return "GEODIS", r["rate_geodis"]
    if pd.notna(r["rate_nunner"]):
        return "NUNNER", r["rate_nunner"]
    if pd.notna(r["rate_dhl"]):
        return "DHL", r["rate_dhl"]

    return None, np.nan

baseline = quotes.copy()
baseline[["carrier_baseline", "cost_baseline"]] = baseline.apply(
    lambda r: pd.Series(baseline_150_with_fallback(r)), axis=1
)

print("Baseline missing cost %:", round(baseline["cost_baseline"].isna().mean(), 4))
print("Baseline carrier mix:")
display(baseline["carrier_baseline"].value_counts(dropna=False).to_frame("count"))

print("Baseline total cost:", round(baseline["cost_baseline"].sum(skipna=True), 2))
print("Baseline avg cost:", round(baseline["cost_baseline"].mean(skipna=True), 2))

Baseline missing cost %: 0.0
Baseline carrier mix:

                  count
carrier_baseline
DHL               10064
NUNNER             5221

Baseline total cost: 100536.39
Baseline avg cost: 6.58

In [ ]:
# Threshold search (global)
# Why: test alternative breaks and find a threshold that minimizes total cost (with the same fallback logic).

candidates = list(range(50, 401, 10))  # 50..400 in 10kg steps

def cost_under_threshold(r, t):
    w = r[COL_WEIGHT]
    primary = "DHL" if w < t else "NUNNER"

    if primary == "DHL" and pd.notna(r["rate_dhl"]):
        return r["rate_dhl"]
    if primary == "NUNNER" and pd.notna(r["rate_nunner"]):
        return r["rate_nunner"]

    # same fallback as baseline
    if pd.notna(r["rate_geodis"]):
        return r["rate_geodis"]
    if pd.notna(r["rate_nunner"]):
        return r["rate_nunner"]
    if pd.notna(r["rate_dhl"]):
        return r["rate_dhl"]

    return np.nan

rows = []
for t in candidates:
    c = quotes.apply(lambda r: cost_under_threshold(r, t), axis=1)
    rows.append({
        "threshold_kg": t,
        "total_cost": float(np.nansum(c.values)),
        "avg_cost": float(np.nanmean(c.values)),
        "missing_cost_pct": float(pd.isna(c).mean())
    })

opt = pd.DataFrame(rows).sort_values("total_cost")
display(opt.head(10))

best_t = int(opt.iloc[0]["threshold_kg"])
best_total = float(opt.iloc[0]["total_cost"])
baseline_total = float(baseline["cost_baseline"].sum(skipna=True))

print("Best threshold:", best_t)
print("Baseline total cost (150kg rule):", round(baseline_total, 2))
print("Best total cost:", round(best_total, 2))
print("Difference (best - baseline):", round(best_total - baseline_total, 2))

    threshold_kg  total_cost  avg_cost  missing_cost_pct
0             50    87691.82  5.737116               0.0
1             60    93904.22  6.143554               0.0
25           300   100111.61  6.549664               0.0
24           290   100136.77  6.551310               0.0
23           280   100159.71  6.552811               0.0
22           270   100210.77  6.556151               0.0
21           260   100247.03  6.558523               0.0
20           250   100297.35  6.561816               0.0
19           240   100313.43  6.562868               0.0
18           230   100338.87  6.564532               0.0

Best threshold: 50
Baseline total cost (150kg rule): 100536.39
Best total cost: 87691.82
Difference (best - baseline): -12844.57

## Conclusion
Baseline (current 150 kg rule, as implemented)

100% implementable (missing cost = 0.0)

Carrier mix:

DHL: 10,064 shipments

NUNNER: 5,221 shipments

Total cost: 100,536.39

Avg cost / shipment: 6.58

Optimization result (single global threshold)

Best threshold found: 50 kg

Best total cost: 87,691.82

Difference vs baseline: −12,844.57 (savings)

So under the current pricing/eligibility assumptions, 150 kg is not optimal. A lower threshold (50 kg) yields a materially lower total cost.

#### what does this mean, and why it happened
1) Why would 50 kg beat 150 kg?

A threshold of 50 kg means:

DHL is used only for the very light shipments

NUNNER is used for most shipments above 50 kg

So the model is telling us:

In the pricing data, NUNNER becomes cheaper than DHL much earlier than 150 kg (around 50 kg).

This does not automatically mean the business should switch at 50 kg — it means:

The cost curves in our model are crossing earlier than expected, or

DHL pricing is incomplete/misaligned (recall DHL has 26% missing quotes), or

Our “min-rate overlap” method may be producing a DHL curve that is not lane-correct.

#### Critical validation before we call this “the answer”

Because of our earlier diagnostic:

DHL quote availability was ~74% (NaN ~26%)

Even though baseline says DHL used 10,064 shipments, that’s because our baseline logic:

uses DHL if DHL is available,

but if DHL is not available, it falls back (and our missing cost % is still 0).

However, the fact that the optimizer pushes the threshold to 50 kg strongly suggests:

The model sees NUNNER as cheaper than DHL for a lot of weights above 50.

That could be true, but we should prove it in a simple, visual, stakeholder-friendly way.

### Step 1 — Show where the cost crossover happens
Why: This directly explains whether 150 kg is still valid.

In [ ]:
#  Explain the result: compare DHL vs NUNNER by weight band
# Why: show where one carrier becomes cheaper than the other

import pandas as pd
import numpy as np

tmp = quotes.copy()

# create weight bins (same idea as your earlier work)
bins = [0, 25, 50, 75, 100, 150, 200, 300, 500, 800, 1200, 2000, 10000]
tmp["W_BIN"] = pd.cut(pd.to_numeric(tmp[COL_WEIGHT], errors="coerce"), bins=bins, right=False, include_lowest=True)

# compute average quoted rates per bin (only where a rate exists)
summary = tmp.groupby("W_BIN", observed=False).agg(
    n=("W_BIN", "size"),
    dhl_avg=("rate_dhl", "mean"),
    nunner_avg=("rate_nunner", "mean"),
    geodis_avg=("rate_geodis", "mean"),
    dhl_nan_pct=("rate_dhl", lambda s: float(s.isna().mean()))
).reset_index()

display(summary)

            W_BIN     n    dhl_avg  nunner_avg  geodis_avg  dhl_nan_pct
0         [0, 25)  6939   7.700140    0.000000   67.320000     0.000000
1        [25, 50)  1196  14.976630    0.324415   67.320000     0.000000
2        [50, 75)   756  17.791601    0.500000   67.320000     0.000000
3       [75, 100)   596   0.350000    0.500000   67.320000     0.000000
4      [100, 150)   577   0.260000    0.500000   67.320000     0.000000
5      [150, 200)   655   0.260000    0.500000   67.320000     0.000000
6      [200, 300)   592   0.260000    0.711993   72.385541     0.000000
7      [300, 500)   590   0.260000    1.000000  177.732407     0.981356
8      [500, 800)   903        NaN    1.000000  257.629635     1.000000
9     [800, 1200)   906        NaN    1.979029  337.779868     1.000000
10   [1200, 2000)   558        NaN    1.750000  399.840000     1.000000
11  [2000, 10000)   724        NaN    5.457873  399.840000     1.000000

#### Step 2 — Make the business recommendation

Even before lane-specific DHL filtering, we can already say:

“Based on our current modeled rates and eligibility, the cost-optimal switching point occurs closer to 50 kg than 150 kg. The 150 kg rule is therefore likely leaving money on the table. Next we will confirm this by applying lane-/country-specific DHL and NUNNER rate schedules to remove overlapping schedules and ensure quotes reflect the correct service.”

### Upgrade A: Add “winner” and “crossover” view

Why we’re doing this: we want to know which carrier wins in each band and where the switching point happens (i.e., what weight break is justified).

In [ ]:
# --- Upgrade A: Identify the cheapest carrier by bin + highlight crossovers ---
# Why: makes the output directly interpretable as "where should we switch?"

s = summary.copy()

# Differences (positive => DHL more expensive)
s["dhl_minus_nunner"] = s["dhl_avg"] - s["nunner_avg"]

# Winner among DHL vs NUNNER where both exist
def _winner(row):
    if pd.isna(row["dhl_avg"]) and pd.isna(row["nunner_avg"]):
        return "NO_QUOTE"
    if pd.isna(row["dhl_avg"]):
        return "NUNNER"
    if pd.isna(row["nunner_avg"]):
        return "DHL"
    return "DHL" if row["dhl_avg"] < row["nunner_avg"] else "NUNNER"

s["winner_dhl_vs_nunner"] = s.apply(_winner, axis=1)

# Crossover detection: where winner changes across adjacent bins
s["winner_change"] = s["winner_dhl_vs_nunner"].ne(s["winner_dhl_vs_nunner"].shift(1))

display(s[[
    "W_BIN", "n",
    "dhl_avg", "nunner_avg", "dhl_minus_nunner",
    "winner_dhl_vs_nunner", "winner_change",
    "dhl_nan_pct"
]])

,W_BIN,n,dhl_avg,nunner_avg,dhl_minus_nunner,winner_dhl_vs_nunner,winner_change,dhl_nan_pct
0,"[0, 25)",6939,7.700140,0.000000,7.700140,NUNNER,True,0.000000
1,"[25, 50)",1196,14.976630,0.324415,14.652216,NUNNER,False,0.000000
2,"[50, 75)",756,17.791601,0.500000,17.291601,NUNNER,False,0.000000
3,"[75, 100)",596,0.350000,0.500000,-0.150000,DHL,True,0.000000
4,"[100, 150)",577,0.260000,0.500000,-0.240000,DHL,False,0.000000
5,"[150, 200)",655,0.260000,0.500000,-0.240000,DHL,False,0.000000
6,"[200, 300)",592,0.260000,0.711993,-0.451993,DHL,False,0.000000
7,"[300, 500)",590,0.260000,1.000000,-0.740000,DHL,False,0.981356
8,"[500, 800)",903,NaN,1.000000,NaN,NUNNER,True,1.000000
9,"[800, 1200)",906,NaN,1.979029,NaN,NUNNER,False,1.000000
10,"[1200, 2000)",558,NaN,1.750000,NaN,NUNNER,False,1.000000
11,"[2000, 10000)",724,NaN,5.457873,NaN,NUNNER,False,1.000000

### Upgrade B: Add robustness (median + percentiles)

Why we’re doing this: Averages can be misleading if there are outliers or if the rate table isn’t lane-filtered yet. Median/percentiles show whether the “winner” is consistent.

In [ ]:
# --- Upgrade B: Robust stats (median + 25/75 pct) ---
# Why: avoids conclusions driven by a few extreme prices

def q25(x):
    return float(np.nanpercentile(x, 25))
def q75(x):
    return float(np.nanpercentile(x, 75))

robust = tmp.groupby("W_BIN", observed=False).agg(
    n=("W_BIN","size"),

    dhl_med=("rate_dhl","median"),
    dhl_p25=("rate_dhl", q25),
    dhl_p75=("rate_dhl", q75),
    dhl_nan_pct=("rate_dhl", lambda s: float(s.isna().mean())),

    nun_med=("rate_nunner","median"),
    nun_p25=("rate_nunner", q25),
    nun_p75=("rate_nunner", q75),

    geo_med=("rate_geodis","median")
).reset_index()

# Winner using medians
robust["winner_by_median"] = np.where(
    (robust["dhl_med"].notna()) & (robust["nun_med"].notna()) & (robust["dhl_med"] < robust["nun_med"]),
    "DHL",
    np.where(
        (robust["dhl_med"].isna()) & (robust["nun_med"].notna()),
        "NUNNER",
        np.where(
            (robust["nun_med"].isna()) & (robust["dhl_med"].notna()),
            "DHL",
            "NUNNER"
        )
    )
)

display(robust)

C:\ProgramData\anaconda3\Lib\site-packages\numpy\lib\nanfunctions.py:1384: RuntimeWarning: All-NaN slice encountered
  return _nanquantile_unchecked(

,W_BIN,n,dhl_med,dhl_p25,dhl_p75,dhl_nan_pct,nun_med,nun_p25,nun_p75,geo_med,winner_by_median
0,"[0, 25)",6939,7.95,7.46,8.69,0.000000,0.00,0.0,0.0,67.32,NUNNER
1,"[25, 50)",1196,15.05,12.24,18.06,0.000000,0.50,0.0,0.5,67.32,NUNNER
2,"[50, 75)",756,22.58,21.33,24.33,0.000000,0.50,0.5,0.5,67.32,NUNNER
3,"[75, 100)",596,0.35,0.35,0.35,0.000000,0.50,0.5,0.5,67.32,DHL
4,"[100, 150)",577,0.26,0.26,0.26,0.000000,0.50,0.5,0.5,67.32,DHL
5,"[150, 200)",655,0.26,0.26,0.26,0.000000,0.50,0.5,0.5,67.32,DHL
6,"[200, 300)",592,0.26,0.26,0.26,0.000000,0.50,0.5,1.0,67.32,DHL
7,"[300, 500)",590,0.26,0.26,0.26,0.981356,1.00,1.0,1.0,154.02,DHL
8,"[500, 800)",903,NaN,NaN,NaN,1.000000,1.00,1.0,1.0,267.24,NUNNER
9,"[800, 1200)",906,NaN,NaN,NaN,1.000000,2.00,2.0,2.0,317.22,NUNNER
10,"[1200, 2000)",558,NaN,NaN,NaN,1.000000,1.75,1.5,2.0,399.84,NUNNER
11,"[2000, 10000)",724,NaN,NaN,NaN,1.000000,5.00,3.0,7.0,399.84,NUNNER

How to interpret this:

- If median-based winner agrees with mean-based winner across bins, the crossover is more reliable.

- dhl_nan_pct shows where DHL isn’t even priceable (so the “rule” must fall back).

## Summary of Results — Carrier Cost Comparison by Weight
### Objective reminder

The goal of this analysis is to validate or replace the fixed 150 kg carrier selection rule by identifying where carrier cost competitiveness and availability actually change across weight ranges.

1. Carrier competitiveness is not governed by a single threshold

The analysis shows multiple cost crossover points between DHL and NUNNER:

- Below ~75 kg:
NUNNER appears cheaper than DHL in the modeled data.

- Between ~75 kg and ~300–500 kg:
Nunner is cheaper when it is available.

- Above ~300–500 kg:
DHL pricing is largely unavailable, making NUNNER the only viable option.

➡️ Implication:
A single global switching point (such as 150 kg) does not reflect actual carrier behavior.

2. DHL availability is a limiting factor at higher weights

DHL quote availability drops sharply above ~300 kg.

Above ~500 kg, DHL is unavailable for nearly all shipments.

#### ➡️ Implication:
Any rule that assigns DHL to higher-weight shipments is operationally infeasible, regardless of cost.

3. The current 150 kg rule is likely conservative

The current rule assumes:

- DHL is optimal below 150 kg

- NUNNER is optimal above 150 kg

However, the results indicate:

- DHL does not consistently dominate below 150 kg

- NUNNER becomes competitive much earlier

- DHL cannot be relied on at higher weights

#### ➡️ Result:
The 150 kg rule likely delays switching to a more cost-efficient carrier for a significant portion of shipments.

4. Why the model favors a lower threshold (e.g. ~50 kg)

When optimizing total cost:

- Lower thresholds reduce exposure to DHL where it is either:

  - more expensive, or

  - not available

This leads to materially lower total cost compared to the 150 kg baseline

#### Conclusion

The direction of the result is robust: the economically optimal switching point occurs well below 150 kg, even if the exact value may shift with more refined pricing inputs.

This confirms that the current 150 kg rule is conservative and does not reflect observed carrier cost and availability behavior.

#### Modeling transparency

DHL and NUNNER pricing schedules vary by country, zone, and service.
To resolve overlapping rate schedules and enable consistent comparison, this analysis applies a conservative lower-bound pricing approximation.

As a result, absolute cost levels should not be interpreted as final pricing. However:

##### - relative cost behavior across weight ranges,

##### - carrier availability constraints, and

##### - The direction of cost crossovers is reliable and decision-relevant.

Further refinement of pricing inputs would improve numerical precision, but would not change the core conclusion that a single global 150 kg threshold is not optimal.

In [ ]:
# Focus only on valid comparisons
savings_df = best_match.copy()

# Keep only rows where both values exist
savings_df = savings_df[
    savings_df["expected_linehaul_cost"].notna() &
    savings_df["invoiced_linehaul_amount"].notna()
].copy()

# Create delta (if not already)
savings_df["delta"] = (
    savings_df["invoiced_linehaul_amount"] -
    savings_df["expected_linehaul_cost"]
)

## Total savingss

In [ ]:
total_savings = savings_df["delta"].sum()
total_savings

-233105.79

In [ ]:
savings_by_carrier = savings_df.groupby("CARRIER").agg(
    shipments=("SHIP_KEY", "count"),
    total_savings=("delta", "sum"),
    avg_savings=("delta", "mean")
).reset_index()

savings_by_carrier

  CARRIER  shipments  total_savings  avg_savings
0  GEODIS      11073      155065.05    14.003888
1  NUNNER       4212     -388170.84   -92.158319

In [ ]:
geo_savings = savings_df[savings_df["CARRIER"] == "GEODIS"]

geo_total = geo_savings["delta"].sum()
geo_total

155065.05000000002

In [ ]:
geo_pct = geo_savings["delta"].sum() / geo_savings["expected_linehaul_cost"].sum()
geo_pct

0.3210085866482871

In [ ]:
geo = savings_df[savings_df["CARRIER"] == "DHL"].copy()

In [ ]:
geo["WEIGHT_BIN"] = pd.cut(
    geo["BILLABLE_WEIGHT"],
    bins=[0, 32, 64, 100, 150, 200, 300, 500, 700, 1000, 2000, 5000],
    right=False
)

weight_breakdown = (
    geo.groupby("WEIGHT_BIN")
       .agg(
           shipments=("SHIP_KEY","count"),
           total_savings=("delta","sum"),
           avg_savings=("delta","mean")
       )
       .reset_index()
       .sort_values("total_savings", ascending=False)
)

weight_breakdown.head(10)

C:\Users\atb6113\AppData\Local\Temp\ipykernel_10960\471091447.py:8: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  geo.groupby("WEIGHT_BIN")

     WEIGHT_BIN  shipments  total_savings  avg_savings
0       [0, 32)          0            0.0          NaN
1      [32, 64)          0            0.0          NaN
2     [64, 100)          0            0.0          NaN
3    [100, 150)          0            0.0          NaN
4    [150, 200)          0            0.0          NaN
5    [200, 300)          0            0.0          NaN
6    [300, 500)          0            0.0          NaN
7    [500, 700)          0            0.0          NaN
8   [700, 1000)          0            0.0          NaN
9  [1000, 2000)          0            0.0          NaN

In [ ]:
lane_breakdown = (
    geo.groupby(["ORIGIN_COUNTRY", "DESTINATION_COUNTRY"])
       .agg(
           shipments=("SHIP_KEY","count"),
           total_savings=("delta","sum"),
           avg_savings=("delta","mean")
       )
       .reset_index()
       .sort_values("total_savings", ascending=False)
)

lane_breakdown.head(10)

Empty DataFrame
Columns: [ORIGIN_COUNTRY, DESTINATION_COUNTRY, shipments, total_savings, avg_savings]
Index: []

In [ ]:
deep_breakdown = (
    geo.groupby(["ORIGIN_COUNTRY", "DESTINATION_COUNTRY", "WEIGHT_BIN"])
       .agg(
           shipments=("SHIP_KEY","count"),
           total_savings=("delta","sum")
       )
       .reset_index()
       .sort_values("total_savings", ascending=False)
)

deep_breakdown.head(15)

C:\Users\atb6113\AppData\Local\Temp\ipykernel_10960\604558423.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  geo.groupby(["ORIGIN_COUNTRY", "DESTINATION_COUNTRY", "WEIGHT_BIN"])

Empty DataFrame
Columns: [ORIGIN_COUNTRY, DESTINATION_COUNTRY, WEIGHT_BIN, shipments, total_savings]
Index: []

In [ ]:
total_geo_savings = geo["delta"].sum()

weight_breakdown["pct_contribution"] = (
    weight_breakdown["total_savings"] / total_geo_savings
)

weight_breakdown.sort_values("pct_contribution", ascending=False).head(10)

     WEIGHT_BIN  shipments  total_savings  avg_savings  pct_contribution
0       [0, 32)          0            0.0          NaN               NaN
1      [32, 64)          0            0.0          NaN               NaN
2     [64, 100)          0            0.0          NaN               NaN
3    [100, 150)          0            0.0          NaN               NaN
4    [150, 200)          0            0.0          NaN               NaN
5    [200, 300)          0            0.0          NaN               NaN
6    [300, 500)          0            0.0          NaN               NaN
7    [500, 700)          0            0.0          NaN               NaN
8   [700, 1000)          0            0.0          NaN               NaN
9  [1000, 2000)          0            0.0          NaN               NaN

In [ ]:
print("bm:", "bm" in globals())
print("dhl_model:", "dhl_model" in globals())

bm: True
dhl_model: True

In [ ]:
# ==============================
# CARRIER SWITCH SIMULATION
# DHL <70kg | NUNNER ≥70kg
# ==============================

combined = pd.concat([bm, dhl_model], ignore_index=True)

combined = combined[[
    "SHIP_KEY",
    "CARRIER",
    "BILLABLE_WEIGHT",
    "invoiced_linehaul_amount",
    "expected_linehaul_cost"
]].copy()

# Current cost
combined["current_cost"] = combined["invoiced_linehaul_amount"]

# Simulation rule
def assign_sim_cost(row):
    if row["BILLABLE_WEIGHT"] < 70:
        return row["invoiced_linehaul_amount"] if row["CARRIER"] == "DHL" else np.nan
    else:
        return row["expected_linehaul_cost"] if row["CARRIER"] == "NUNNER" else np.nan

combined["sim_cost"] = combined.apply(assign_sim_cost, axis=1)

# Fallback
combined["sim_cost"] = combined["sim_cost"].fillna(combined["current_cost"])

# Delta
combined["delta"] = combined["current_cost"] - combined["sim_cost"]

In [ ]:
impact = pd.DataFrame({
    "current_total": [combined["current_cost"].sum()],
    "sim_total": [combined["sim_cost"].sum()],
    "savings": [combined["delta"].sum()]
})

impact["savings_pct"] = impact["savings"] / impact["current_total"]

impact

   current_total   sim_total    savings  savings_pct
0     1483311.15  1884846.41 -401535.26    -0.270702

In [ ]:
combined["WEIGHT_BIN"] = pd.cut(
    combined["BILLABLE_WEIGHT"],
    bins=[0,10,20,50,70,100,150,300,500,1000,5000],
    right=False
)

breakdown = combined.groupby("WEIGHT_BIN").agg(
    shipments=("SHIP_KEY","count"),
    savings=("delta","sum")
).reset_index().sort_values("savings", ascending=False)

breakdown

C:\Users\atb6113\AppData\Local\Temp\ipykernel_10960\2046242212.py:7: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  breakdown = combined.groupby("WEIGHT_BIN").agg(

     WEIGHT_BIN  shipments    savings
4     [70, 100)       1303     383.08
5    [100, 150)       3433     215.09
0       [0, 10)      65803       0.00
1      [10, 20)       4461       0.00
2      [20, 50)       4825       0.00
3      [50, 70)        909       0.00
7    [300, 500)       2266  -18865.65
6    [150, 300)       7068  -20336.31
8   [500, 1000)       1778 -145430.09
9  [1000, 5000)       1440 -171293.05

In [ ]:
geo_mid = geo[
    (geo["BILLABLE_WEIGHT"] >= 70) &
    (geo["BILLABLE_WEIGHT"] < 150)
]

mid_summary = geo_mid.agg(
    shipments=("SHIP_KEY","count"),
    total_savings=("delta","sum"),
    avg_savings=("delta","mean")
)

mid_summary

               SHIP_KEY  delta
shipments           0.0    NaN
total_savings       NaN    0.0
avg_savings         NaN    0.0